"""GENERATED by extensions/python/tools/protocolgen.py --write from extensions/python/tools/protocol_sources/**, extensions/python/tools/protocol_source.py, extensions/python/tools/protocolgen.py, extensions/python/metta/_atoms/operators.py: the protocol-sync artifact in extensions/python/tools/artifacts.py, whose protocol-sync lane refuses drift."""

import operator


def protocol_add_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a + b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_add_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.add(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_and__syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a & b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_and__call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.and_(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_contains_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = b in a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_contains_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.contains(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_eq_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a == b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_eq_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.eq(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_floordiv_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a // b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_floordiv_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.floordiv(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ge_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a >= b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ge_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ge(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_gt_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a > b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_gt_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.gt(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_iadd_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a += b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_iadd_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.iadd(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_iand_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a &= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_iand_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.iand(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ifloordiv_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a //= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ifloordiv_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ifloordiv(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ilshift_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a <<= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ilshift_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ilshift(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_imatmul_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a @= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_imatmul_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.imatmul(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_imod_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a %= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_imod_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.imod(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_imul_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a *= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_imul_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.imul(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_invert_syntax(a):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = ~a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_invert_call(a):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.invert(a)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ior_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a |= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ior_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ior(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ipow_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a **= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ipow_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ipow(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_irshift_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a >>= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_irshift_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.irshift(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_isub_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a -= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_isub_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.isub(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_itruediv_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a /= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_itruediv_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.itruediv(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ixor_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        a ^= b
        result = a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ixor_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ixor(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_le_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a <= b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_le_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.le(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_lshift_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a << b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_lshift_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.lshift(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_lt_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a < b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_lt_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.lt(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_matmul_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a @ b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_matmul_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.matmul(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_mod_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a % b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_mod_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.mod(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_mul_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a * b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_mul_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.mul(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ne_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a != b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_ne_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ne(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_neg_syntax(a):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = -a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_neg_call(a):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.neg(a)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_or__syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a | b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_or__call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.or_(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_pos_syntax(a):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = +a
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_pos_call(a):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.pos(a)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_pow_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a ** b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_pow_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.pow(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_rshift_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a >> b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_rshift_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.rshift(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_sub_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a - b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_sub_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.sub(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_truediv_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a / b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_truediv_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.truediv(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_xor_syntax(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = a ^ b
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_xor_call(a, b):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.xor(a, b)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


PROGRAMS = (
    (('object', '__add__'), 'BinOp', 'Add', protocol_add_syntax, protocol_add_call),
    (('object', '__and__'), 'BinOp', 'BitAnd', protocol_and__syntax, protocol_and__call),
    (('object', '__contains__'), 'Compare', 'In', protocol_contains_syntax, protocol_contains_call),
    (('object', '__eq__'), 'Compare', 'Eq', protocol_eq_syntax, protocol_eq_call),
    (('object', '__floordiv__'), 'BinOp', 'FloorDiv', protocol_floordiv_syntax, protocol_floordiv_call),
    (('object', '__ge__'), 'Compare', 'GtE', protocol_ge_syntax, protocol_ge_call),
    (('object', '__gt__'), 'Compare', 'Gt', protocol_gt_syntax, protocol_gt_call),
    (('object', '__iadd__'), 'AugAssign', 'Add', protocol_iadd_syntax, protocol_iadd_call),
    (('object', '__iand__'), 'AugAssign', 'BitAnd', protocol_iand_syntax, protocol_iand_call),
    (('object', '__ifloordiv__'), 'AugAssign', 'FloorDiv', protocol_ifloordiv_syntax, protocol_ifloordiv_call),
    (('object', '__ilshift__'), 'AugAssign', 'LShift', protocol_ilshift_syntax, protocol_ilshift_call),
    (('object', '__imatmul__'), 'AugAssign', 'MatMult', protocol_imatmul_syntax, protocol_imatmul_call),
    (('object', '__imod__'), 'AugAssign', 'Mod', protocol_imod_syntax, protocol_imod_call),
    (('object', '__imul__'), 'AugAssign', 'Mult', protocol_imul_syntax, protocol_imul_call),
    (('object', '__invert__'), 'UnaryOp', 'Invert', protocol_invert_syntax, protocol_invert_call),
    (('object', '__ior__'), 'AugAssign', 'BitOr', protocol_ior_syntax, protocol_ior_call),
    (('object', '__ipow__'), 'AugAssign', 'Pow', protocol_ipow_syntax, protocol_ipow_call),
    (('object', '__irshift__'), 'AugAssign', 'RShift', protocol_irshift_syntax, protocol_irshift_call),
    (('object', '__isub__'), 'AugAssign', 'Sub', protocol_isub_syntax, protocol_isub_call),
    (('object', '__itruediv__'), 'AugAssign', 'Div', protocol_itruediv_syntax, protocol_itruediv_call),
    (('object', '__ixor__'), 'AugAssign', 'BitXor', protocol_ixor_syntax, protocol_ixor_call),
    (('object', '__le__'), 'Compare', 'LtE', protocol_le_syntax, protocol_le_call),
    (('object', '__lshift__'), 'BinOp', 'LShift', protocol_lshift_syntax, protocol_lshift_call),
    (('object', '__lt__'), 'Compare', 'Lt', protocol_lt_syntax, protocol_lt_call),
    (('object', '__matmul__'), 'BinOp', 'MatMult', protocol_matmul_syntax, protocol_matmul_call),
    (('object', '__mod__'), 'BinOp', 'Mod', protocol_mod_syntax, protocol_mod_call),
    (('object', '__mul__'), 'BinOp', 'Mult', protocol_mul_syntax, protocol_mul_call),
    (('object', '__ne__'), 'Compare', 'NotEq', protocol_ne_syntax, protocol_ne_call),
    (('object', '__neg__'), 'UnaryOp', 'USub', protocol_neg_syntax, protocol_neg_call),
    (('object', '__or__'), 'BinOp', 'BitOr', protocol_or__syntax, protocol_or__call),
    (('object', '__pos__'), 'UnaryOp', 'UAdd', protocol_pos_syntax, protocol_pos_call),
    (('object', '__pow__'), 'BinOp', 'Pow', protocol_pow_syntax, protocol_pow_call),
    (('object', '__rshift__'), 'BinOp', 'RShift', protocol_rshift_syntax, protocol_rshift_call),
    (('object', '__sub__'), 'BinOp', 'Sub', protocol_sub_syntax, protocol_sub_call),
    (('object', '__truediv__'), 'BinOp', 'Div', protocol_truediv_syntax, protocol_truediv_call),
    (('object', '__xor__'), 'BinOp', 'BitXor', protocol_xor_syntax, protocol_xor_call),
)

_protocol_binding_abs = vars(operator).get('abs')


def protocol_exact_abs_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.abs(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_abs_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_abs(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_add = vars(operator).get('add')


def protocol_exact_add_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.add(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_add_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_add(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_and_ = vars(operator).get('and_')


def protocol_exact_and__2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.and_(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_and__2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_and_(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_call = vars(operator).get('call')


def protocol_exact_call_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.call(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_call_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_call(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_exact_call_3(a0, a1, a2):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.call(a0, a1, a2)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_call_3(a0, a1, a2):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_call(a0, a1, a2)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_concat = vars(operator).get('concat')


def protocol_exact_concat_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.concat(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_concat_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_concat(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_contains = vars(operator).get('contains')


def protocol_exact_contains_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.contains(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_contains_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_contains(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_countof = vars(operator).get('countOf')


def protocol_exact_countof_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.countOf(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_countof_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_countof(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_delitem = vars(operator).get('delitem')


def protocol_exact_delitem_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.delitem(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_delitem_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_delitem(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_eq = vars(operator).get('eq')


def protocol_exact_eq_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.eq(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_eq_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_eq(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_floordiv = vars(operator).get('floordiv')


def protocol_exact_floordiv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.floordiv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_floordiv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_floordiv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ge = vars(operator).get('ge')


def protocol_exact_ge_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ge(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ge_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ge(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_getitem = vars(operator).get('getitem')


def protocol_exact_getitem_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.getitem(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_getitem_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_getitem(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_gt = vars(operator).get('gt')


def protocol_exact_gt_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.gt(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_gt_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_gt(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_iadd = vars(operator).get('iadd')


def protocol_exact_iadd_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.iadd(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_iadd_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_iadd(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_iand = vars(operator).get('iand')


def protocol_exact_iand_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.iand(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_iand_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_iand(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_iconcat = vars(operator).get('iconcat')


def protocol_exact_iconcat_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.iconcat(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_iconcat_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_iconcat(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ifloordiv = vars(operator).get('ifloordiv')


def protocol_exact_ifloordiv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ifloordiv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ifloordiv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ifloordiv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ilshift = vars(operator).get('ilshift')


def protocol_exact_ilshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ilshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ilshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ilshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_imatmul = vars(operator).get('imatmul')


def protocol_exact_imatmul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.imatmul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_imatmul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_imatmul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_imod = vars(operator).get('imod')


def protocol_exact_imod_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.imod(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_imod_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_imod(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_imul = vars(operator).get('imul')


def protocol_exact_imul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.imul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_imul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_imul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_index = vars(operator).get('index')


def protocol_exact_index_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.index(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_index_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_index(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_indexof = vars(operator).get('indexOf')


def protocol_exact_indexof_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.indexOf(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_indexof_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_indexof(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_inv = vars(operator).get('inv')


def protocol_exact_inv_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.inv(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_inv_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_inv(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_invert = vars(operator).get('invert')


def protocol_exact_invert_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.invert(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_invert_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_invert(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ior = vars(operator).get('ior')


def protocol_exact_ior_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ior(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ior_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ior(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ipow = vars(operator).get('ipow')


def protocol_exact_ipow_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ipow(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ipow_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ipow(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_irshift = vars(operator).get('irshift')


def protocol_exact_irshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.irshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_irshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_irshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_is_ = vars(operator).get('is_')


def protocol_exact_is__2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.is_(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_is__2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_is_(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_is_none = vars(operator).get('is_none')


def protocol_exact_is_none_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.is_none(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_is_none_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_is_none(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_is_not = vars(operator).get('is_not')


def protocol_exact_is_not_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.is_not(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_is_not_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_is_not(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_is_not_none = vars(operator).get('is_not_none')


def protocol_exact_is_not_none_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.is_not_none(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_is_not_none_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_is_not_none(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_isub = vars(operator).get('isub')


def protocol_exact_isub_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.isub(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_isub_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_isub(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_itruediv = vars(operator).get('itruediv')


def protocol_exact_itruediv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.itruediv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_itruediv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_itruediv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ixor = vars(operator).get('ixor')


def protocol_exact_ixor_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ixor(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ixor_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ixor(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_le = vars(operator).get('le')


def protocol_exact_le_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.le(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_le_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_le(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_length_hint = vars(operator).get('length_hint')


def protocol_exact_length_hint_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.length_hint(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_length_hint_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_length_hint(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_exact_length_hint_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.length_hint(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_length_hint_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_length_hint(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_lshift = vars(operator).get('lshift')


def protocol_exact_lshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.lshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_lshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_lshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_lt = vars(operator).get('lt')


def protocol_exact_lt_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.lt(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_lt_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_lt(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_matmul = vars(operator).get('matmul')


def protocol_exact_matmul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.matmul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_matmul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_matmul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_mod = vars(operator).get('mod')


def protocol_exact_mod_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.mod(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_mod_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_mod(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_mul = vars(operator).get('mul')


def protocol_exact_mul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.mul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_mul_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_mul(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_ne = vars(operator).get('ne')


def protocol_exact_ne_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.ne(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_ne_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_ne(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_neg = vars(operator).get('neg')


def protocol_exact_neg_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.neg(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_neg_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_neg(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_not_ = vars(operator).get('not_')


def protocol_exact_not__1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.not_(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_not__1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_not_(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_or_ = vars(operator).get('or_')


def protocol_exact_or__2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.or_(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_or__2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_or_(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_pos = vars(operator).get('pos')


def protocol_exact_pos_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.pos(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_pos_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_pos(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_pow = vars(operator).get('pow')


def protocol_exact_pow_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.pow(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_pow_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_pow(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_rshift = vars(operator).get('rshift')


def protocol_exact_rshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.rshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_rshift_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_rshift(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_setitem = vars(operator).get('setitem')


def protocol_exact_setitem_3(a0, a1, a2):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.setitem(a0, a1, a2)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_setitem_3(a0, a1, a2):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_setitem(a0, a1, a2)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_sub = vars(operator).get('sub')


def protocol_exact_sub_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.sub(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_sub_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_sub(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_truediv = vars(operator).get('truediv')


def protocol_exact_truediv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.truediv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_truediv_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_truediv(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_truth = vars(operator).get('truth')


def protocol_exact_truth_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.truth(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_truth_1(a0):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_truth(a0)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


_protocol_binding_xor = vars(operator).get('xor')


def protocol_exact_xor_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = operator.xor(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


def protocol_alias_xor_2(a0, a1):
    """Observe the source operation or its exception as ordinary data."""
    try:
        result = _protocol_binding_xor(a0, a1)
    except Exception as error:
        return ('raise', error.__class__.__name__, str(error))
    return ('return', result)


CALL_PROGRAMS = (
    (('operator', 'abs'), 1, protocol_exact_abs_1),
    (('operator', 'add'), 2, protocol_exact_add_2),
    (('operator', 'and_'), 2, protocol_exact_and__2),
    (('operator', 'call'), 1, protocol_exact_call_1),
    (('operator', 'call'), 3, protocol_exact_call_3),
    (('operator', 'concat'), 2, protocol_exact_concat_2),
    (('operator', 'contains'), 2, protocol_exact_contains_2),
    (('operator', 'countOf'), 2, protocol_exact_countof_2),
    (('operator', 'delitem'), 2, protocol_exact_delitem_2),
    (('operator', 'eq'), 2, protocol_exact_eq_2),
    (('operator', 'floordiv'), 2, protocol_exact_floordiv_2),
    (('operator', 'ge'), 2, protocol_exact_ge_2),
    (('operator', 'getitem'), 2, protocol_exact_getitem_2),
    (('operator', 'gt'), 2, protocol_exact_gt_2),
    (('operator', 'iadd'), 2, protocol_exact_iadd_2),
    (('operator', 'iand'), 2, protocol_exact_iand_2),
    (('operator', 'iconcat'), 2, protocol_exact_iconcat_2),
    (('operator', 'ifloordiv'), 2, protocol_exact_ifloordiv_2),
    (('operator', 'ilshift'), 2, protocol_exact_ilshift_2),
    (('operator', 'imatmul'), 2, protocol_exact_imatmul_2),
    (('operator', 'imod'), 2, protocol_exact_imod_2),
    (('operator', 'imul'), 2, protocol_exact_imul_2),
    (('operator', 'index'), 1, protocol_exact_index_1),
    (('operator', 'indexOf'), 2, protocol_exact_indexof_2),
    (('operator', 'inv'), 1, protocol_exact_inv_1),
    (('operator', 'invert'), 1, protocol_exact_invert_1),
    (('operator', 'ior'), 2, protocol_exact_ior_2),
    (('operator', 'ipow'), 2, protocol_exact_ipow_2),
    (('operator', 'irshift'), 2, protocol_exact_irshift_2),
    (('operator', 'is_'), 2, protocol_exact_is__2),
    (('operator', 'is_none'), 1, protocol_exact_is_none_1),
    (('operator', 'is_not'), 2, protocol_exact_is_not_2),
    (('operator', 'is_not_none'), 1, protocol_exact_is_not_none_1),
    (('operator', 'isub'), 2, protocol_exact_isub_2),
    (('operator', 'itruediv'), 2, protocol_exact_itruediv_2),
    (('operator', 'ixor'), 2, protocol_exact_ixor_2),
    (('operator', 'le'), 2, protocol_exact_le_2),
    (('operator', 'length_hint'), 1, protocol_exact_length_hint_1),
    (('operator', 'length_hint'), 2, protocol_exact_length_hint_2),
    (('operator', 'lshift'), 2, protocol_exact_lshift_2),
    (('operator', 'lt'), 2, protocol_exact_lt_2),
    (('operator', 'matmul'), 2, protocol_exact_matmul_2),
    (('operator', 'mod'), 2, protocol_exact_mod_2),
    (('operator', 'mul'), 2, protocol_exact_mul_2),
    (('operator', 'ne'), 2, protocol_exact_ne_2),
    (('operator', 'neg'), 1, protocol_exact_neg_1),
    (('operator', 'not_'), 1, protocol_exact_not__1),
    (('operator', 'or_'), 2, protocol_exact_or__2),
    (('operator', 'pos'), 1, protocol_exact_pos_1),
    (('operator', 'pow'), 2, protocol_exact_pow_2),
    (('operator', 'rshift'), 2, protocol_exact_rshift_2),
    (('operator', 'setitem'), 3, protocol_exact_setitem_3),
    (('operator', 'sub'), 2, protocol_exact_sub_2),
    (('operator', 'truediv'), 2, protocol_exact_truediv_2),
    (('operator', 'truth'), 1, protocol_exact_truth_1),
    (('operator', 'xor'), 2, protocol_exact_xor_2),
)

ALIAS_PROGRAMS = (
    (('operator', 'abs'), 1, protocol_alias_abs_1),
    (('operator', 'add'), 2, protocol_alias_add_2),
    (('operator', 'and_'), 2, protocol_alias_and__2),
    (('operator', 'call'), 1, protocol_alias_call_1),
    (('operator', 'call'), 3, protocol_alias_call_3),
    (('operator', 'concat'), 2, protocol_alias_concat_2),
    (('operator', 'contains'), 2, protocol_alias_contains_2),
    (('operator', 'countOf'), 2, protocol_alias_countof_2),
    (('operator', 'delitem'), 2, protocol_alias_delitem_2),
    (('operator', 'eq'), 2, protocol_alias_eq_2),
    (('operator', 'floordiv'), 2, protocol_alias_floordiv_2),
    (('operator', 'ge'), 2, protocol_alias_ge_2),
    (('operator', 'getitem'), 2, protocol_alias_getitem_2),
    (('operator', 'gt'), 2, protocol_alias_gt_2),
    (('operator', 'iadd'), 2, protocol_alias_iadd_2),
    (('operator', 'iand'), 2, protocol_alias_iand_2),
    (('operator', 'iconcat'), 2, protocol_alias_iconcat_2),
    (('operator', 'ifloordiv'), 2, protocol_alias_ifloordiv_2),
    (('operator', 'ilshift'), 2, protocol_alias_ilshift_2),
    (('operator', 'imatmul'), 2, protocol_alias_imatmul_2),
    (('operator', 'imod'), 2, protocol_alias_imod_2),
    (('operator', 'imul'), 2, protocol_alias_imul_2),
    (('operator', 'index'), 1, protocol_alias_index_1),
    (('operator', 'indexOf'), 2, protocol_alias_indexof_2),
    (('operator', 'inv'), 1, protocol_alias_inv_1),
    (('operator', 'invert'), 1, protocol_alias_invert_1),
    (('operator', 'ior'), 2, protocol_alias_ior_2),
    (('operator', 'ipow'), 2, protocol_alias_ipow_2),
    (('operator', 'irshift'), 2, protocol_alias_irshift_2),
    (('operator', 'is_'), 2, protocol_alias_is__2),
    (('operator', 'is_none'), 1, protocol_alias_is_none_1),
    (('operator', 'is_not'), 2, protocol_alias_is_not_2),
    (('operator', 'is_not_none'), 1, protocol_alias_is_not_none_1),
    (('operator', 'isub'), 2, protocol_alias_isub_2),
    (('operator', 'itruediv'), 2, protocol_alias_itruediv_2),
    (('operator', 'ixor'), 2, protocol_alias_ixor_2),
    (('operator', 'le'), 2, protocol_alias_le_2),
    (('operator', 'length_hint'), 1, protocol_alias_length_hint_1),
    (('operator', 'length_hint'), 2, protocol_alias_length_hint_2),
    (('operator', 'lshift'), 2, protocol_alias_lshift_2),
    (('operator', 'lt'), 2, protocol_alias_lt_2),
    (('operator', 'matmul'), 2, protocol_alias_matmul_2),
    (('operator', 'mod'), 2, protocol_alias_mod_2),
    (('operator', 'mul'), 2, protocol_alias_mul_2),
    (('operator', 'ne'), 2, protocol_alias_ne_2),
    (('operator', 'neg'), 1, protocol_alias_neg_1),
    (('operator', 'not_'), 1, protocol_alias_not__1),
    (('operator', 'or_'), 2, protocol_alias_or__2),
    (('operator', 'pos'), 1, protocol_alias_pos_1),
    (('operator', 'pow'), 2, protocol_alias_pow_2),
    (('operator', 'rshift'), 2, protocol_alias_rshift_2),
    (('operator', 'setitem'), 3, protocol_alias_setitem_3),
    (('operator', 'sub'), 2, protocol_alias_sub_2),
    (('operator', 'truediv'), 2, protocol_alias_truediv_2),
    (('operator', 'truth'), 1, protocol_alias_truth_1),
    (('operator', 'xor'), 2, protocol_alias_xor_2),
)
