"""Purpose: the refusal table: one row per kind, as data with no engine running.

GENERATED by extensions/python/tools/refusalgen.py from the engine's own
`(refusal ...)` rows in engine/spaces/catalog.pl joined with this seat's
spellings in tests/data/error-kinds.json. Edit those two and rerun with
--write, never this file; the `refusal-sync` gate lane fails when they drift.

`metta.errors.refuse(kind, message, **fields)` is the door that reads this: it
takes the class from the row, the ground from the row, and the remedy from the
row's template with the `<field>` holes filled from the fields the site passed.
The engine renders the same template for a ball it raises itself, through
`metta_host_refusal/6`; the two are held to each other by
extensions/python/tests/repository/test_refusal_rows.py.

This module imports nothing from the package on purpose. `metta.errors` is the
base layer and builds `Ground` and `Remedy` from these rows, so a row that
carried either object would be a cycle.

Guarantees:
  - every row here is the engine's own, in the catalog's order
    [tested: test_the_refusal_table_is_generated;
    commit=c26b6a4d28ef8fb50742440feed2c0578ebb0f58]
  - `cls` is the class THIS seat raises and `departure` says why when it is
    not the row's own name [tested: test_every_seat_raises_the_rows_class_or_says_why;
    commit=c26b6a4d28ef8fb50742440feed2c0578ebb0f58]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final, NamedTuple

#: One act of a remedy, as the term it is: the head, then each part, with a
#: nested tuple for a nested expression and `<name>` for a hole. `metta.errors`
#: turns one into `(edit (pragma! max-time 5))` once the holes are filled.
type Act = tuple["str | Act", ...]


class Refusal(NamedTuple):
    """One refusal kind, as every seat's own table needs it.

    `kind` is the engine's word, `cls` the class THIS seat raises for it and
    `declared` the seat-independent name the row gives; `departure` is why the
    two differ, or None when they agree. `origin` is the ball's shape --
    `signal` for the reserved control envelope, `term` for a ball whose functor
    names the refusal, `default` for the one kind nothing shaped, which is the
    taxonomy's catch-all. `fields` are the names this kind's refusal carries,
    which are both the remedy template's holes and the keywords `refuse()`
    passes to the class.
    """

    kind: str
    cls: str
    declared: str
    departure: str | None
    origin: str
    ground_kind: str
    citation: str
    title: str
    remedy_kind: str
    applicability: str
    acts: tuple[Act, ...]
    fields: tuple[str, ...]


#: Every refusal kind, in the catalog's own order.
REFUSALS: Final[Mapping[str, Refusal]] = MappingProxyType({
    'syntax': Refusal(
        kind='syntax',
        cls='MettaSyntaxError',
        declared='MettaSyntaxError',
        departure=None,
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/filereader.pl metta_host_rethrow_syntax/1 -- text the reader cannot read stops the load, at the line it stopped on',
        title='close or correct the form that starts at line <line>',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=('line',),
    ),
    'time_limit': Refusal(
        kind='time_limit',
        cls='TimeLimitError',
        declared='TimeLimitError',
        departure=None,
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/metta/control.pl metta_pragma_key/2 max-time -- a wall-clock bound stops the evaluation where it stands, and the writes it already made stand with it',
        title='raise the bound past <limit> seconds, or narrow the query',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(('edit', ('pragma!', 'max-time', '<seconds>')),),
        fields=('limit',),
    ),
    'inference_limit': Refusal(
        kind='inference_limit',
        cls='InferenceLimitError',
        declared='InferenceLimitError',
        departure=None,
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/metta/control.pl metta_pragma_key/2 max-inferences -- an inference bound stops the evaluation where it stands, and the writes it already made stand with it',
        title='raise the bound past <limit> inferences, or narrow the query',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(('edit', ('pragma!', 'max-inferences', '<inferences>')),),
        fields=('limit',),
    ),
    'restraint': Refusal(
        kind='restraint',
        cls='RestraintError',
        declared='RestraintError',
        departure=None,
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/spaces/catalog.pl (cache F (max-answers N)) -- a bound a program declared for one of its own tables stops the call that passed it, naming the bound rather than answering fewer rows in silence',
        title='raise the <restraint> bound past <bound> in the row that declares it, or ask <call> for fewer answers',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=('restraint', 'bound', 'call'),
    ),
    'interrupted': Refusal(
        kind='interrupted',
        cls='Interrupted',
        declared='Interrupted',
        departure=None,
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/metta/registration.pl metta_host_error_kind_row/3 interrupted -- a run stopped from outside reports the stop, so a caller tells it from a fault',
        title='start the run again if the stop was not meant',
        remedy_kind='source',
        applicability='prose',
        acts=(),
        fields=(),
    ),
    'value': Refusal(
        kind='value',
        cls='ValueError',
        declared='WireError',
        departure="Python's own word for a value it cannot use; the refusal is about the caller's data rather than about MeTTa, so the language's class is the one a caller writes in except",
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/json_codec.pl -- the crossing carries only values JSON can carry and refuses the rest by name, rather than coercing them',
        title='give the crossing a value JSON can carry, or carry the whole thing as a grounded atom',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=(),
    ),
    'type': Refusal(
        kind='type',
        cls='TypeError',
        declared='CastError',
        departure="Python's own word for a term of the wrong type; metta.convert.CastError already names a different meaning on this seat, a cast() refusal, so the row's name is taken here",
        origin='signal',
        ground_kind='metta-law',
        citation='HostLaws: engine/json_codec.pl -- a term that is not JSON data at all is refused as a type rather than as a value, so a caller tells a bad number from a bad shape',
        title='carry this term whole as a grounded atom instead of as data',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=(),
    ),
    'assertion': Refusal(
        kind='assertion',
        cls='AssertionFailure',
        declared='AssertionFailure',
        departure=None,
        origin='term',
        ground_kind='metta-law',
        citation='HostLaws: engine/metta/runtime.pl report_failed_assertion/4 -- a false claim is printed and thrown under the MeTTa head the program wrote, so a harness separates it from a broken engine',
        title='correct the claim <operation> makes, or the equations it reads',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=('operation',),
    ),
    'capability': Refusal(
        kind='capability',
        cls='SpaceCapabilityError',
        declared='SpaceCapabilityError',
        departure=None,
        origin='term',
        ground_kind='metta-law',
        citation='HostLaws: engine/spaces/lifecycle.pl metta_space_capability_required/3 -- a restricted space answers only for the capabilities its (grants ...) rows name',
        title='grant <capability> to <space>, which <operation> needs',
        remedy_kind='quickfix',
        applicability='maybe',
        acts=(('edit', ('grants', '<space>', '<capability>')),),
        fields=('space', 'operation', 'capability'),
    ),
    'operation': Refusal(
        kind='operation',
        cls='MettaOperationError',
        declared='MettaOperationError',
        departure=None,
        origin='term',
        ground_kind='arbiter',
        citation='upstream PeTTa at the parity pin: tests/conformance/petta/expected/he_error.metta.out answers Error to (catch (+ 40 a)), so a builtin refusing a value is a VALUE inside MeTTa and becomes a host exception only at the crossing',
        title='give <operation> a <expected> where it got <culprit>',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=('operation', 'kind', 'expected', 'culprit'),
    ),
    'stack': Refusal(
        kind='stack',
        cls='StackLimitError',
        declared='StackLimitError',
        departure=None,
        origin='term',
        ground_kind='metta-law',
        citation='HostLaws: engine/metta/control.pl metta_pragma_key/2 stack-limit -- the ceiling in force when the stack ran out is the one the refusal names, not the one in force now',
        title='raise the ceiling past <limit> bytes, or make the recursion shallower',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(('edit', ('pragma!', 'stack-limit', '<bytes>')),),
        fields=('limit',),
    ),
    'source': Refusal(
        kind='source',
        cls='SourceNotFound',
        declared='SourceNotFound',
        departure=None,
        origin='term',
        ground_kind='metta-law',
        citation='HostLaws: engine/filereader.pl -- a source a program names is read only once it exists, and the refusal carries the path rather than the sentence about it',
        title='create <source>, or correct the path that names it',
        remedy_kind='quickfix',
        applicability='prose',
        acts=(),
        fields=('source',),
    ),
    'engine': Refusal(
        kind='engine',
        cls='EngineError',
        declared='EngineError',
        departure=None,
        origin='default',
        ground_kind='metta-law',
        citation='HostLaws: engine/metta/registration.pl metta_host_error_kind/3 -- a ball this engine did not shape is reported as itself rather than classified by guess',
        title='report the ball with the message it carries; this engine did not shape it',
        remedy_kind='source',
        applicability='prose',
        acts=(),
        fields=(),
    ),
})
