"""Purpose: expose catalog vocabularies as generated StrEnum classes.

Each class corresponds to one (vocabulary ...) row in &metta.

GENERATED by extensions/python/tools/vocabgen.py from the running engine's catalog
presets; edit the presets in engine/spaces/catalog.pl and rerun with --write, never
this file. The vocab-sync gate lane fails when the two drift.

Each member IS its wire string, so it passes every membership test a bare
word passes and crosses as the symbol it always was; bare words remain the
runtime escape hatch at every consuming call.

Guarantees:
  - every class here exactly matches its catalog vocabulary row, values in
    declared order
    [tested: test_the_vocabulary_module_is_generated;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - every member encodes as its MeTTa symbol
    [tested: test_every_vocabulary_member_crosses_as_its_symbol;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - Visibility is the catalog's exact PUBLIC/INTERNAL discriminator
    [tested: test_visibility_is_a_generated_catalog_vocabulary;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - EffectClass compares by catalog rank and joins a plan to its strongest
    member [tested: test_effect_class_is_the_public_five_rank_join_lattice,
    test_effect_join_obeys_the_lattice_laws;
    commit=3cfbe0d7417b1c453c2dc12d47e2e47e7de461f7]
  - a class name IS the MeTTa type name the engine writes: `(: EffectClass
    Type)` and `(: pureStructural EffectClass)` are atoms in `&metta`, and the
    name comes from the row rather than from a map kept here
    [tested: test_every_vocabulary_is_typed_by_the_engine; commit=7f9c810e5f4a2023ad98de34e848667dd72bc4a7]
  - a class the engine declares OPEN accepts a word registered through
    `(add-atom &metta (vocabulary-member <vocab> <word>))`
    [tested: test_an_open_vocabulary_accepts_a_registered_word; commit=7f9c810e5f4a2023ad98de34e848667dd72bc4a7]
  - WIRE_TAGS is the wire grammar as the engine states it, one row per tag
    [tested: test_the_wire_tag_table_is_the_engines_own; commit=7f9c810e5f4a2023ad98de34e848667dd72bc4a7]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from collections.abc import Iterable, Mapping
from enum import StrEnum
from types import MappingProxyType
from typing import Final, NamedTuple

from .atoms import Symbol


class _AtomStrEnum(StrEnum):
    """A closed Python option whose wire identity is its MeTTa symbol."""

    def __metta__(self):
        return Symbol(self.value)


class _OpenStrEnum(_AtomStrEnum):
    """An option set the engine's row declares OPEN, so a word a library
    registered is a member too.

    The members written out below are what the engine ships. A word registered
    through `(add-atom &metta (vocabulary-member <vocab> <word>))` reaches this
    class through `_missing_`, which mints a member for it exactly as
    `enum.IntFlag` mints one for a composite nobody wrote down.

    The rung below is the engine's own refusal. This class does not ask the
    engine whether the word is registered, because the catalog checks it at the
    write and refuses an unregistered one there, naming the row; asking here
    would buy a crossing per call to say the same thing earlier. Protocol
    Buffers draws the same line for its open enums: an undeclared value is
    carried, and what it means is the application's business.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

    @classmethod
    def _missing_(cls, value):
        if not isinstance(value, str):
            return None
        member = str.__new__(cls, value)
        member._name_ = value
        member._value_ = value
        return cls._value2member_map_.setdefault(value, member)


class _EffectStrEnum(_AtomStrEnum):
    """One member of an ordered effect lattice, strongest value winning."""

    @property
    def rank(self) -> int:
        """The catalog position, from structural purity to host I/O."""
        return tuple(type(self)).index(self)

    # The reason is here rather than beside the pragma because pylint reads
    # everything after disable= as message names: this is the effect
    # lattice's own operation, which shares a name with str.join on a
    # str-derived enum, and the docstring below says why that is deliberate.
    # pylint: disable-next=arguments-renamed
    def join(self, other):
        """The least upper bound of two effects: their strongest member.

        This shadows ``str.join`` on a str-derived enum deliberately: join
        is the lattice operation's own name and its laws are tested
        (commutative, idempotent, associative, with the weakest rank as
        identity). Anything that is not an effect refuses by naming both
        readings, so a caller who wanted the string operation is told which
        operation they called rather than seeing a bad-enum-value error.
        """
        try:
            other = type(self)(other)
        except ValueError:
            msg = (
                f"{other!r} is not {type(self).__name__} member; this join "
                f"is the effect lattice's least upper bound, not str.join. "
                f"To join strings, call str.join on a plain string."
            )
            raise TypeError(msg) from None
        return self if self.rank >= other.rank else other

    @classmethod
    def compose(cls, effects: Iterable):
        """Join a plan's effects; an empty plan has no observable effect."""
        result = next(iter(cls))
        for effect in effects:
            result = result.join(effect)
        return result

    def _other_rank(self, other):
        try:
            return type(self)(other).rank
        except (TypeError, ValueError):
            return NotImplemented

    def __lt__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank < rank

    def __le__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank <= rank

    def __gt__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank > rank

    def __ge__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank >= rank

__all__ = [
    "WIRE_TAGS",
    "AgendaPolicy",
    "AlgebraLaw",
    "AnswerPolicy",
    "Applicability",
    "ArgumentDelivery",
    "Atomicity",
    "CachePolicy",
    "ClauseFailedEnum",
    "CostClass",
    "Delivery",
    "DeltaKind",
    "Determinism",
    "EffectClass",
    "EvaluationOrderEnum",
    "EventOrder",
    "Fidelity",
    "FunctionResultEnum",
    "GroundKind",
    "ImageMode",
    "JournalSync",
    "Limit",
    "LiveStrategy",
    "MemoAggregate",
    "MemoStrategy",
    "MismatchEnum",
    "NoMatchEnum",
    "NumericType",
    "OnError",
    "OpKind",
    "OutOfClausesEnum",
    "ProviderCapability",
    "Refinement",
    "RefusalKind",
    "RegistryImage",
    "RemedyKind",
    "RouteKey",
    "SaveFormat",
    "Semiring",
    "SemiringOrder",
    "SourceKind",
    "SpaceCapability",
    "SubscriptionEdge",
    "Visibility",
    "Volatility",
    "WireClass",
    "WirePayload",
    "WireTag",
    "World",
]

#: (vocabulary ClauseFailedEnum ClauseFailNonDet ClauseFailDet)
class ClauseFailedEnum(_AtomStrEnum):
    """Typed values of the ClauseFailedEnum vocabulary."""
    ClauseFailNonDet = "ClauseFailNonDet"
    ClauseFailDet = "ClauseFailDet"

#: (vocabulary EvaluationOrderEnum OrderClause OrderFittest)
class EvaluationOrderEnum(_AtomStrEnum):
    """Typed values of the EvaluationOrderEnum vocabulary."""
    OrderClause = "OrderClause"
    OrderFittest = "OrderFittest"

#: (vocabulary FunctionResultEnum Nondeterministic Deterministic)
class FunctionResultEnum(_AtomStrEnum):
    """Typed values of the FunctionResultEnum vocabulary."""
    Nondeterministic = "Nondeterministic"
    Deterministic = "Deterministic"

#: (vocabulary MismatchEnum MismatchOriginal MismatchError MismatchFail)
class MismatchEnum(_AtomStrEnum):
    """Typed values of the MismatchEnum vocabulary."""
    MismatchOriginal = "MismatchOriginal"
    MismatchError = "MismatchError"
    MismatchFail = "MismatchFail"

#: (vocabulary NoMatchEnum NoMatchOriginal NoMatchFail NoMatchError)
class NoMatchEnum(_AtomStrEnum):
    """Typed values of the NoMatchEnum vocabulary."""
    NoMatchOriginal = "NoMatchOriginal"
    NoMatchFail = "NoMatchFail"
    NoMatchError = "NoMatchError"

#: (vocabulary OutOfClausesEnum FailureOriginal FailureEmpty FailureError)
class OutOfClausesEnum(_AtomStrEnum):
    """Typed values of the OutOfClausesEnum vocabulary."""
    FailureOriginal = "FailureOriginal"
    FailureEmpty = "FailureEmpty"
    FailureError = "FailureError"

#: (vocabulary agenda-policy declaration recency specificity priority user)
class AgendaPolicy(_AtomStrEnum):
    """Typed values of the agenda-policy vocabulary."""
    declaration = "declaration"
    recency = "recency"
    specificity = "specificity"
    priority = "priority"
    user = "user"

#: (vocabulary algebra-law combine-associative combine-commutative extend-associative extend-commutative left-distributive right-distributive combine-idempotent combine-zero-identity extend-one-identity extend-zero-annihilates contraction roundtrip equivalent associative commutative distributive idempotent identity distributes-over)
class AlgebraLaw(_AtomStrEnum):
    """Typed values of the algebra-law vocabulary."""
    combine_associative = "combine-associative"
    combine_commutative = "combine-commutative"
    extend_associative = "extend-associative"
    extend_commutative = "extend-commutative"
    left_distributive = "left-distributive"
    right_distributive = "right-distributive"
    combine_idempotent = "combine-idempotent"
    combine_zero_identity = "combine-zero-identity"
    extend_one_identity = "extend-one-identity"
    extend_zero_annihilates = "extend-zero-annihilates"
    contraction = "contraction"
    roundtrip = "roundtrip"
    equivalent = "equivalent"
    associative = "associative"
    commutative = "commutative"
    distributive = "distributive"
    idempotent = "idempotent"
    identity = "identity"
    distributes_over = "distributes-over"

#: (vocabulary answer-policy depth fair best-first)
class AnswerPolicy(_AtomStrEnum):
    """Typed values of the answer-policy vocabulary."""
    depth = "depth"
    fair = "fair"
    best_first = "best-first"

#: (vocabulary applicability machine maybe prose)
class Applicability(_AtomStrEnum):
    """Typed values of the applicability vocabulary."""
    machine = "machine"
    maybe = "maybe"
    prose = "prose"

#: (vocabulary argument-delivery atoms values)
class ArgumentDelivery(_AtomStrEnum):
    """Typed values of the argument-delivery vocabulary."""
    atoms = "atoms"
    values = "values"

#: (vocabulary atomicity transactional atomic-single best-effort)
class Atomicity(_AtomStrEnum):
    """Typed values of the atomicity vocabulary."""
    transactional = "transactional"
    atomic_single = "atomic-single"
    best_effort = "best-effort"

#: (vocabulary cache-policy force refuse plain incremental monotonic lazy shared private subsumptive lattice max-answers subgoal-abstract answer-abstract)
class CachePolicy(_AtomStrEnum):
    """Typed values of the cache-policy vocabulary."""
    force = "force"
    refuse = "refuse"
    plain = "plain"
    incremental = "incremental"
    monotonic = "monotonic"
    lazy = "lazy"
    shared = "shared"
    private = "private"
    subsumptive = "subsumptive"
    lattice = "lattice"
    max_answers = "max-answers"
    subgoal_abstract = "subgoal-abstract"
    answer_abstract = "answer-abstract"

#: (vocabulary cost-class constant log linear linearithmic quadratic exponential)
class CostClass(_AtomStrEnum):
    """Typed values of the cost-class vocabulary."""
    constant = "constant"
    log = "log"
    linear = "linear"
    linearithmic = "linearithmic"
    quadratic = "quadratic"
    exponential = "exponential"

#: (vocabulary delivery at-most-once at-least-once per-write-exactly)
class Delivery(_AtomStrEnum):
    """Typed values of the delivery vocabulary."""
    at_most_once = "at-most-once"
    at_least_once = "at-least-once"
    per_write_exactly = "per-write-exactly"

#: (vocabulary delta-kind add remove progress)
class DeltaKind(_AtomStrEnum):
    """Typed values of the delta-kind vocabulary."""
    add = "add"
    remove = "remove"
    progress = "progress"

#: (vocabulary determinism det semidet nondet)
class Determinism(_AtomStrEnum):
    """Typed values of the determinism vocabulary."""
    det = "det"
    semidet = "semidet"
    nondet = "nondet"

#: (vocabulary effect-class pureStructural readOnlyLookup nondeterministicReadOnly writesState oracleIO)
class EffectClass(_EffectStrEnum):
    """Typed values of the effect-class vocabulary."""
    pureStructural = "pureStructural"  # noqa: N815  -- the member keeps the catalog's public wire spelling
    readOnlyLookup = "readOnlyLookup"  # noqa: N815  -- the member keeps the catalog's public wire spelling
    nondeterministicReadOnly = "nondeterministicReadOnly"  # noqa: N815  -- the member keeps the catalog's public wire spelling
    writesState = "writesState"  # noqa: N815  -- the member keeps the catalog's public wire spelling
    oracleIO = "oracleIO"  # noqa: N815  -- the member keeps the catalog's public wire spelling

#: (vocabulary event-order ordered unordered)
class EventOrder(_AtomStrEnum):
    """Typed values of the event-order vocabulary."""
    ordered = "ordered"
    unordered = "unordered"

#: (vocabulary fidelity Exact Partial Sound Refuse)
class Fidelity(_AtomStrEnum):
    """Typed values of the fidelity vocabulary."""
    Exact = "Exact"
    Partial = "Partial"
    Sound = "Sound"
    Refuse = "Refuse"

#: (vocabulary ground-kind host-reference metta-law arbiter)
class GroundKind(_AtomStrEnum):
    """Typed values of the ground-kind vocabulary."""
    host_reference = "host-reference"
    metta_law = "metta-law"
    arbiter = "arbiter"

#: (vocabulary image-mode opaque transparent auto)
class ImageMode(_AtomStrEnum):
    """Typed values of the image-mode vocabulary."""
    opaque = "opaque"
    transparent = "transparent"
    auto = "auto"

#: (vocabulary journal-sync none flush close)
class JournalSync(_AtomStrEnum):
    """Typed values of the journal-sync vocabulary."""
    none = "none"
    flush = "flush"
    close = "close"

#: (vocabulary limit events memory inferences timeout stack)
class Limit(_AtomStrEnum):
    """Typed values of the limit vocabulary."""
    events = "events"
    memory = "memory"
    inferences = "inferences"
    timeout = "timeout"
    stack = "stack"

#: (vocabulary live-strategy pattern heads tabled)
class LiveStrategy(_AtomStrEnum):
    """Typed values of the live-strategy vocabulary."""
    pattern = "pattern"
    heads = "heads"
    tabled = "tabled"

#: (vocabulary memo-aggregate none min max sum count)
class MemoAggregate(_AtomStrEnum):
    """Typed values of the memo-aggregate vocabulary."""
    none = "none"
    min = "min"
    max = "max"
    sum = "sum"
    count = "count"  # type: ignore[assignment]  # the member deliberately shadows a str method; the word is the API

#: (vocabulary memo-strategy wtinylfu lru)
class MemoStrategy(_AtomStrEnum):
    """Typed values of the memo-strategy vocabulary."""
    wtinylfu = "wtinylfu"
    lru = "lru"

#: (vocabulary numeric-type Number BigInt)
class NumericType(_AtomStrEnum):
    """Typed values of the numeric-type vocabulary."""
    Number = "Number"
    BigInt = "BigInt"

#: (vocabulary on-error-mode keep empty abort)
class OnError(_AtomStrEnum):
    """Typed values of the on-error-mode vocabulary."""
    keep = "keep"
    empty = "empty"
    abort = "abort"

#: (vocabulary op-kind det many async raw_det raw_many)
class OpKind(_AtomStrEnum):
    """Typed values of the op-kind vocabulary."""
    det = "det"
    many = "many"
    async_ = "async"
    raw_det = "raw_det"
    raw_many = "raw_many"

#: (vocabulary provider-capability match enumerate add add-many remove clear subscribe plan rules)
class ProviderCapability(_OpenStrEnum):
    """Typed values of the provider-capability vocabulary, which the engine
    declares OPEN: a word registered through
    `(add-atom &metta (vocabulary-member provider-capability <word>))` is
    accepted too, and the members below are the ones it ships.
    """  # noqa: D205  -- the contract is one claim, not summary-and-body prose
    match = "match"
    enumerate = "enumerate"
    add = "add"
    add_many = "add-many"
    remove = "remove"
    clear = "clear"
    subscribe = "subscribe"
    plan = "plan"
    rules = "rules"

#: (vocabulary refinement Gt Ge Lt Le Interval MultipleOf MinLen MaxLen Len Predicate Unit)
class Refinement(_AtomStrEnum):
    """Typed values of the refinement vocabulary."""
    Gt = "Gt"
    Ge = "Ge"
    Lt = "Lt"
    Le = "Le"
    Interval = "Interval"
    MultipleOf = "MultipleOf"
    MinLen = "MinLen"
    MaxLen = "MaxLen"
    Len = "Len"
    Predicate = "Predicate"
    Unit = "Unit"

#: (vocabulary refusal-kind syntax time_limit inference_limit restraint interrupted value type assertion capability operation stack source engine)
class RefusalKind(_AtomStrEnum):
    """Typed values of the refusal-kind vocabulary."""
    syntax = "syntax"
    time_limit = "time_limit"
    inference_limit = "inference_limit"
    restraint = "restraint"
    interrupted = "interrupted"
    value = "value"
    type = "type"
    assertion = "assertion"
    capability = "capability"
    operation = "operation"
    stack = "stack"
    source = "source"
    engine = "engine"

#: (vocabulary registry-image expression symbol handle operations)
class RegistryImage(_AtomStrEnum):
    """Typed values of the registry-image vocabulary."""
    expression = "expression"
    symbol = "symbol"
    handle = "handle"
    operations = "operations"

#: (vocabulary remedy-kind quickfix refactor source)
class RemedyKind(_AtomStrEnum):
    """Typed values of the remedy-kind vocabulary."""
    quickfix = "quickfix"
    refactor = "refactor"
    source = "source"

#: (vocabulary route-key context global)
class RouteKey(_AtomStrEnum):
    """Typed values of the route-key vocabulary."""
    context = "context"
    global_ = "global"

#: (vocabulary save-format metta fast)
class SaveFormat(_AtomStrEnum):
    """Typed values of the save-format vocabulary."""
    metta = "metta"
    fast = "fast"

#: (vocabulary semiring bool bag counting set ranked tropical prob prov budget amplitude)
class Semiring(_OpenStrEnum):
    """Typed values of the semiring vocabulary, which the engine
    declares OPEN: a word registered through
    `(add-atom &metta (vocabulary-member semiring <word>))` is
    accepted too, and the members below are the ones it ships.
    """  # noqa: D205  -- the contract is one claim, not summary-and-body prose
    bool = "bool"
    bag = "bag"
    counting = "counting"
    set = "set"
    ranked = "ranked"
    tropical = "tropical"
    prob = "prob"
    prov = "prov"
    budget = "budget"
    amplitude = "amplitude"

#: (vocabulary semiring-order ascending descending)
class SemiringOrder(_AtomStrEnum):
    """Typed values of the semiring-order vocabulary."""
    ascending = "ascending"
    descending = "descending"

#: (vocabulary source-kind linear repeated peek)
class SourceKind(_AtomStrEnum):
    """Typed values of the source-kind vocabulary."""
    linear = "linear"
    repeated = "repeated"
    peek = "peek"

#: (vocabulary space-capability file process network)
class SpaceCapability(_AtomStrEnum):
    """Typed values of the space-capability vocabulary."""
    file = "file"
    process = "process"
    network = "network"

#: (vocabulary subscription-edge add remove both)
class SubscriptionEdge(_AtomStrEnum):
    """Typed values of the subscription-edge vocabulary."""
    add = "add"
    remove = "remove"
    both = "both"

#: (vocabulary visibility PUBLIC INTERNAL)
class Visibility(_AtomStrEnum):
    """Typed values of the visibility vocabulary."""
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"

#: (vocabulary volatility volatile stable immutable)
class Volatility(_AtomStrEnum):
    """Typed values of the volatility vocabulary."""
    volatile = "volatile"
    stable = "stable"
    immutable = "immutable"

#: (vocabulary wire-class term frame reply)
class WireClass(_AtomStrEnum):
    """Typed values of the wire-class vocabulary."""
    term = "term"
    frame = "frame"
    reply = "reply"

#: (vocabulary wire-payload text number boolean term terms host handle truth bindings control)
class WirePayload(_AtomStrEnum):
    """Typed values of the wire-payload vocabulary."""
    text = "text"
    number = "number"
    boolean = "boolean"
    term = "term"
    terms = "terms"
    host = "host"
    handle = "handle"
    truth = "truth"
    bindings = "bindings"
    control = "control"

#: (vocabulary world closed-world open-world)
class World(_AtomStrEnum):
    """Typed values of the world vocabulary."""
    closed_world = "closed-world"
    open_world = "open-world"

class WireTag(NamedTuple):
    """One tag of the wire grammar: what class of thing it is, what
    class its payload is, and the sentence CODEC.md shows for it.
    """  # noqa: D205  -- the row is one claim, not summary-and-body prose

    kind: WireClass
    payload: WirePayload
    means: str


#: Every wire tag, in the catalog's own order. A `term` tag nests inside an
#: atom, a `frame` tag wraps a whole answer, and a `reply` tag is one door's
#: answer shape. metta._projection reads the term tags for its OpenAPI atom
#: schema and metta._schemas reads the payload class for each arm, so the
#: shim's clauses and both of those follow one grammar.
WIRE_TAGS: Final[Mapping[str, WireTag]] = MappingProxyType({
    "s": WireTag(
        WireClass.term,
        WirePayload.text,
        "a symbol: a name that denotes itself",
    ),
    "g": WireTag(
        WireClass.term,
        WirePayload.text,
        "a grounded value carried as text; a string crosses this way",
    ),
    "n": WireTag(
        WireClass.term,
        WirePayload.number,
        "a grounded Number or BigInt; signed-i64 width fixes an integer's language type",
    ),
    "b": WireTag(
        WireClass.term,
        WirePayload.boolean,
        "a grounded boolean; the engine writes true and false, and reads True and False as the same two constants",
    ),
    "v": WireTag(
        WireClass.term,
        WirePayload.text,
        "a variable, the payload an identity within this term",
    ),
    "e": WireTag(
        WireClass.term,
        WirePayload.terms,
        "an expression, its children in order; the empty one is unit",
    ),
    "p": WireTag(
        WireClass.term,
        WirePayload.text,
        "an executable space reference carried by its portable engine name, ampersand-prefixed or not; the tag is a species and a name that is no space keeps s",
    ),
    "o": WireTag(
        WireClass.term,
        WirePayload.host,
        "a live host value crossing by reference, in process only",
    ),
    "h": WireTag(
        WireClass.term,
        WirePayload.handle,
        "a native engine value held by reference",
    ),
    "u": WireTag(
        WireClass.frame,
        WirePayload.truth,
        "an answer whose truth is undefined under the well-founded semantics",
    ),
    "a": WireTag(
        WireClass.frame,
        WirePayload.bindings,
        "an answer together with the bindings it is returned under",
    ),
    "x": WireTag(
        WireClass.frame,
        WirePayload.control,
        "stream control: exhaustion, no answer at all, or a failure kept as a value",
    ),
    "r": WireTag(
        WireClass.reply,
        WirePayload.term,
        "the refinement constraint a cast violated, answered when the base type admits the value and the refinement does not",
    ),
})
