"""Purpose: the catalog's value vocabularies as StrEnum classes, one per
(vocabulary ...) row in &petta.

GENERATED by bindings/python/tools/vocabgen.py from the running engine's catalog
presets; edit the presets in engine/spaces.pl and rerun with --write, never
this file. The vocab-sync gate lane fails when the two drift.

Each member IS its wire string, so it passes every membership test a bare
word passes and crosses as the symbol it always was; bare words remain the
runtime escape hatch at every consuming door.

Guarantees:
  - every class here exactly matches its catalog vocabulary row, values in
    declared order
    [tested: test_the_vocabulary_module_is_generated; commit=WORKTREE]
  - every member encodes as its MeTTa symbol
    [tested: test_every_vocabulary_member_crosses_as_its_symbol; commit=WORKTREE]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""  # noqa: D205  -- the API contract is one continuous invariant, not summary-and-body prose

from enum import StrEnum

from .atoms import Symbol


class _AtomStrEnum(StrEnum):
    """A closed Python option whose wire identity is its MeTTa symbol."""

    def __metta__(self):
        return Symbol(self.value)

__all__ = [
    "AgendaPolicy",
    "AnswerPolicy",
    "Atomicity",
    "CacheMode",
    "ClauseFailedEnum",
    "Delivery",
    "Determinism",
    "EffectClass",
    "EvaluationOrderEnum",
    "EventOrder",
    "Fidelity",
    "FunctionResultEnum",
    "ImageMode",
    "MemoAggregate",
    "MemoStrategy",
    "MismatchEnum",
    "NoMatchEnum",
    "NumericType",
    "OnError",
    "OpKind",
    "OutOfClausesEnum",
    "RegistryImage",
    "RouteKey",
    "SaveFormat",
    "Semiring",
    "SourceKind",
    "SpaceCapability",
    "SubscriptionEdge",
    "Volatility",
    "World",
]

#: (vocabulary ClauseFailedEnum ClauseFailNonDet ClauseFailDet)
class ClauseFailedEnum(_AtomStrEnum):
    """Typed values of the ClauseFailedEnum vocabulary."""
    ClauseFailNonDet = "ClauseFailNonDet"
    ClauseFailDet = "ClauseFailDet"

#: (vocabulary EvaluationOrderEnum OrderClause OrderFittest)
class EvaluationOrderEnum(_AtomStrEnum):
    """Typed values of the EvaluationOrderEnum vocabulary."""
    OrderClause = "OrderClause"
    OrderFittest = "OrderFittest"

#: (vocabulary FunctionResultEnum Nondeterministic Deterministic)
class FunctionResultEnum(_AtomStrEnum):
    """Typed values of the FunctionResultEnum vocabulary."""
    Nondeterministic = "Nondeterministic"
    Deterministic = "Deterministic"

#: (vocabulary MismatchEnum MismatchOriginal MismatchError MismatchFail)
class MismatchEnum(_AtomStrEnum):
    """Typed values of the MismatchEnum vocabulary."""
    MismatchOriginal = "MismatchOriginal"
    MismatchError = "MismatchError"
    MismatchFail = "MismatchFail"

#: (vocabulary NoMatchEnum NoMatchOriginal NoMatchFail NoMatchError)
class NoMatchEnum(_AtomStrEnum):
    """Typed values of the NoMatchEnum vocabulary."""
    NoMatchOriginal = "NoMatchOriginal"
    NoMatchFail = "NoMatchFail"
    NoMatchError = "NoMatchError"

#: (vocabulary OutOfClausesEnum FailureOriginal FailureEmpty FailureError)
class OutOfClausesEnum(_AtomStrEnum):
    """Typed values of the OutOfClausesEnum vocabulary."""
    FailureOriginal = "FailureOriginal"
    FailureEmpty = "FailureEmpty"
    FailureError = "FailureError"

#: (vocabulary agenda-policy declaration recency specificity priority user)
class AgendaPolicy(_AtomStrEnum):
    """Typed values of the agenda-policy vocabulary."""
    declaration = "declaration"
    recency = "recency"
    specificity = "specificity"
    priority = "priority"
    user = "user"

#: (vocabulary answer-policy depth fair best-first)
class AnswerPolicy(_AtomStrEnum):
    """Typed values of the answer-policy vocabulary."""
    depth = "depth"
    fair = "fair"
    best_first = "best-first"

#: (vocabulary atomicity transactional atomic-single best-effort)
class Atomicity(_AtomStrEnum):
    """Typed values of the atomicity vocabulary."""
    transactional = "transactional"
    atomic_single = "atomic-single"
    best_effort = "best-effort"

#: (vocabulary cache-mode unchecked force refuse)
class CacheMode(_AtomStrEnum):
    """Typed values of the cache-mode vocabulary."""
    unchecked = "unchecked"
    force = "force"
    refuse = "refuse"

#: (vocabulary delivery at-most-once at-least-once per-write-exactly)
class Delivery(_AtomStrEnum):
    """Typed values of the delivery vocabulary."""
    at_most_once = "at-most-once"
    at_least_once = "at-least-once"
    per_write_exactly = "per-write-exactly"

#: (vocabulary determinism det semidet nondet)
class Determinism(_AtomStrEnum):
    """Typed values of the determinism vocabulary."""
    det = "det"
    semidet = "semidet"
    nondet = "nondet"

#: (vocabulary effect-class immutable)
class EffectClass(_AtomStrEnum):
    """Typed values of the effect-class vocabulary."""
    immutable = "immutable"

#: (vocabulary event-order ordered unordered)
class EventOrder(_AtomStrEnum):
    """Typed values of the event-order vocabulary."""
    ordered = "ordered"
    unordered = "unordered"

#: (vocabulary fidelity Exact Partial Sound Refuse)
class Fidelity(_AtomStrEnum):
    """Typed values of the fidelity vocabulary."""
    Exact = "Exact"
    Partial = "Partial"
    Sound = "Sound"
    Refuse = "Refuse"

#: (vocabulary image-mode opaque transparent auto)
class ImageMode(_AtomStrEnum):
    """Typed values of the image-mode vocabulary."""
    opaque = "opaque"
    transparent = "transparent"
    auto = "auto"

#: (vocabulary memo-aggregate none min max sum count)
class MemoAggregate(_AtomStrEnum):
    """Typed values of the memo-aggregate vocabulary."""
    none = "none"
    min = "min"
    max = "max"
    sum = "sum"
    count = "count"  # type: ignore[assignment]  # the member deliberately shadows a str method; the word is the API

#: (vocabulary memo-strategy wtinylfu lru)
class MemoStrategy(_AtomStrEnum):
    """Typed values of the memo-strategy vocabulary."""
    wtinylfu = "wtinylfu"
    lru = "lru"

#: (vocabulary numeric-type Number BigInt)
class NumericType(_AtomStrEnum):
    """Typed values of the numeric-type vocabulary."""
    Number = "Number"
    BigInt = "BigInt"

#: (vocabulary on-error-mode keep empty abort)
class OnError(_AtomStrEnum):
    """Typed values of the on-error-mode vocabulary."""
    keep = "keep"
    empty = "empty"
    abort = "abort"

#: (vocabulary op-kind det many raw_det raw_many)
class OpKind(_AtomStrEnum):
    """Typed values of the op-kind vocabulary."""
    det = "det"
    many = "many"
    raw_det = "raw_det"
    raw_many = "raw_many"

#: (vocabulary registry-image expression symbol handle operations)
class RegistryImage(_AtomStrEnum):
    """Typed values of the registry-image vocabulary."""
    expression = "expression"
    symbol = "symbol"
    handle = "handle"
    operations = "operations"

#: (vocabulary route-key context global)
class RouteKey(_AtomStrEnum):
    """Typed values of the route-key vocabulary."""
    context = "context"
    global_ = "global"

#: (vocabulary save-format metta fast)
class SaveFormat(_AtomStrEnum):
    """Typed values of the save-format vocabulary."""
    metta = "metta"
    fast = "fast"

#: (vocabulary semiring bool bag set ranked prob prov)
class Semiring(_AtomStrEnum):
    """Typed values of the semiring vocabulary."""
    bool = "bool"
    bag = "bag"
    set = "set"
    ranked = "ranked"
    prob = "prob"
    prov = "prov"

#: (vocabulary source-kind linear repeated peek)
class SourceKind(_AtomStrEnum):
    """Typed values of the source-kind vocabulary."""
    linear = "linear"
    repeated = "repeated"
    peek = "peek"

#: (vocabulary space-capability file process network)
class SpaceCapability(_AtomStrEnum):
    """Typed values of the space-capability vocabulary."""
    file = "file"
    process = "process"
    network = "network"

#: (vocabulary subscription-edge add remove both)
class SubscriptionEdge(_AtomStrEnum):
    """Typed values of the subscription-edge vocabulary."""
    add = "add"
    remove = "remove"
    both = "both"

#: (vocabulary volatility volatile stable immutable)
class Volatility(_AtomStrEnum):
    """Typed values of the volatility vocabulary."""
    volatile = "volatile"
    stable = "stable"
    immutable = "immutable"

#: (vocabulary world closed-world open-world)
class World(_AtomStrEnum):
    """Typed values of the world vocabulary."""
    closed_world = "closed-world"
    open_world = "open-world"
