"""Purpose: expose the generated MeTTa door face.

GENERATED by extensions/python/tools/aiogen.py --write from
extensions/python/metta/**/*.py, extensions/python/ext/metta-*/*.py: the aio-
mirror artifact in extensions/python/tools/artifacts.py, whose aio-mirror lane
refuses drift.
Edit the inputs and regenerate this file.
"""

from __future__ import annotations

import builtins as _body_builtins
import builtins as _builtins
import collections.abc as _body_collections_abc
import os as _body_os
import typing as _body_typing
from typing import TYPE_CHECKING
from typing import Protocol as _Protocol
from typing import Self as _Self
from typing import cast as _cast
from typing import overload as _overload

import metta._atoms.designation as _body_metta__atoms_designation
import metta._atoms.factories as _body_metta__atoms_factories
import metta._declare.define as _body_metta__declare_define
import metta._declare.operations as _body_metta__declare_operations
import metta._observe.debug as _body_metta__observe_debug
import metta._observe.recording as _body_metta__observe_recording
import metta._observe.trace as _body_metta__observe_trace
import metta._spaces.execution as _body_metta__spaces_execution
import metta._spaces.profile as _body_metta__spaces_profile
import metta._spaces.scope as _body_metta__spaces_scope
import metta.doors as _body_metta_doors
import metta.vocabularies as _body_metta_vocabularies
from metta._lazy import lazy as _lazy
from metta._spaces.context import MeTTaBase
from metta.doors import _namespaces


class _ImplementationSpaceEvalBound(_Protocol):
    def __call__(
        self,
        target: _body_typing.Any,
        /,
        *more: _body_typing.Any,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        under: _body_typing.Any=_body_metta__atoms_designation._UNSET,
        theory: _body_typing.Any | None=None,
        interpreter: _body_typing.Any | None=None,
        answer: _body_metta_doors.EvaluationAnswer | _builtins.str='all',
        delivery: _body_metta_vocabularies.ArgumentDelivery | _builtins.str='atoms',
        limit: _builtins.int | None=None,
        image: _body_metta_vocabularies.ImageMode | _builtins.str | None=None,
        on_error: _body_metta_vocabularies.OnError | _builtins.str='keep',
        determinism: _body_metta_vocabularies.Determinism | _builtins.str='nondet',
        **values: _body_typing.Any,
    ) -> _body_typing.Any:
        ...

class _ImplementationSpaceDefineBound(_Protocol):
    def __call__(
        self,
        /,
        fn: _body_collections_abc.Callable[..., _body_typing.Any] | None=None,
        *,
        prolog: _builtins.str | _body_os.PathLike[_builtins.str] | None=None,
        name: _builtins.str | None=None,
        accessors: _builtins.bool=True,
        methods: _builtins.bool=True,
    ) -> _body_typing.Any:
        ...

class _ImplementationSpaceOpBound(_Protocol):
    def __call__(
        self,
        /,
        fn: _body_collections_abc.Callable | None=None,
        *,
        name: _builtins.str | None=None,
        transport: _body_metta__declare_operations.Transport='encoded',
        effect: _body_metta_vocabularies.EffectClass | _builtins.str | None=None,
        declarations: _body_collections_abc.Iterable[_body_metta__atoms_factories.Atom]=(),
        arities: _builtins.list[_builtins.int] | None=None,
        inverse: _body_collections_abc.Callable | None=None,
    ) -> _body_typing.Any:
        ...

class MeTTa(MeTTaBase):
    """The MeTTa operations declared beside their implementations."""

    __slots__ = ()

    arrays: _namespaces.ArraysContext
    live: _namespaces.LiveContext
    remote: _namespaces.RemoteContext
    tables: _namespaces.TablesContext

    @_overload
    def eval(
        self,
        target: _body_typing.Any,
        /,
        *more: _body_typing.Any,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        under: _body_typing.Any=_body_metta__atoms_designation._UNSET,
        theory: _body_typing.Any | None=None,
        interpreter: _body_typing.Any | None=None,
        answer: _body_metta_doors.EvaluationAnswer | _builtins.str='all',
        delivery: _body_metta_vocabularies.ArgumentDelivery | _builtins.str,
        limit: _builtins.int | None=None,
        image: _body_metta_vocabularies.ImageMode | _builtins.str | None=None,
        on_error: _body_metta_vocabularies.OnError | _builtins.str='keep',
        determinism: _body_metta_vocabularies.Determinism | _builtins.str='nondet',
        **values: _body_typing.Any,
    ) -> _body_typing.Any:
        ...
    @_overload
    def eval(
        self,
        target: _body_typing.Any,
        /,
        *more: _body_typing.Any,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        under: _body_typing.Any=_body_metta__atoms_designation._UNSET,
        theory: _body_typing.Any | None=None,
        interpreter: _body_typing.Any | None=None,
        answer: _body_metta_doors.EvaluationAnswer | _builtins.str,
        delivery: _body_metta_vocabularies.ArgumentDelivery | _builtins.str='atoms',
        limit: _builtins.int | None=None,
        image: _body_metta_vocabularies.ImageMode | _builtins.str | None=None,
        on_error: _body_metta_vocabularies.OnError | _builtins.str='keep',
        determinism: _body_metta_vocabularies.Determinism | _builtins.str='nondet',
        **values: _body_typing.Any,
    ) -> _body_typing.Any:
        ...
    @_overload
    def eval(
        self,
        target: _body_typing.Any,
        /,
        *,
        timeout: _builtins.float | None=...,
        inferences: _builtins.int | None=...,
        under: _body_typing.Any=...,
        theory: _body_typing.Any | None=...,
        interpreter: _body_typing.Any | None=...,
        **values: _body_typing.Any,
    ) -> _builtins.list[_body_metta__atoms_factories.Atom | _body_metta__atoms_factories.Undefined]:
        ...
    @_overload
    def eval(
        self,
        target: _body_typing.Any,
        _second: _body_typing.Any,
        /,
        *more: _body_typing.Any,
        timeout: _builtins.float | None=...,
        inferences: _builtins.int | None=...,
        under: _body_typing.Any=...,
        theory: _body_typing.Any | None=...,
        interpreter: _body_typing.Any | None=...,
        **values: _body_typing.Any,
    ) -> _builtins.list[_builtins.list[_body_metta__atoms_factories.Atom | _body_metta__atoms_factories.Undefined]]:
        ...
    def eval(
        self,
        target: _body_typing.Any,
        /,
        *more: _body_typing.Any,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        under: _body_typing.Any=_body_metta__atoms_designation._UNSET,
        theory: _body_typing.Any | None=None,
        interpreter: _body_typing.Any | None=None,
        answer: _body_metta_doors.EvaluationAnswer | _builtins.str='all',
        delivery: _body_metta_vocabularies.ArgumentDelivery | _builtins.str='atoms',
        limit: _builtins.int | None=None,
        image: _body_metta_vocabularies.ImageMode | _builtins.str | None=None,
        on_error: _body_metta_vocabularies.OnError | _builtins.str='keep',
        determinism: _body_metta_vocabularies.Determinism | _builtins.str='nondet',
        **values: _body_typing.Any,
    ) -> _body_typing.Any:
        """Evaluate a term, returning every answer.

        This is what !(...) runs, minus the printing: the engine's
        translate_expr over the term, then its goals. Nondeterminism means
        the list can hold any number of answers, including none.

        Variadic, and that is how evaluation BATCHES: several terms ride
        one engine crossing and the answer is one group per term in call
        order, run()'s own grouping carried to the term form. One term
        keeps its flat list, so the scalar reading never changes shape.

        Every answer carries its truth: an answer that is undefined under
        Well Founded Semantics (a tabled loop through tnot, reachable via
        translatePredicate or injected Prolog) arrives as an Undefined
        holding the answer and the delay condition that makes it
        undefined, never as an ordinary-looking value. A term to which no
        rule applies is the ordinary answer itself; `eval_status()` names
        that path `not-reducible`. run() does not carry the third truth
        value; evaluate through eval() when it matters.

        A text target may carry HOLES, exactly as run()'s source may:
        `m.eval(t"(decide {tensor})")` and `m.eval("(decide {x})", x=tensor)`
        hand the object itself to the rule, by identity. One call's holes are
        numbered together, so a batch and a nested template cannot collide.

        `bind()` binds named host values into the term before it evaluates,
        exactly as it does for run(): inside `with m.bind({"x": tensor})`,
        `m.eval("(decide x)")` hands the tensor itself to the rule, by
        identity, rather than a printed form of it. The name is the SYMBOL x
        and not the variable $x, in this call and the source form alike. The
        evaluation calls take the same vocabulary as the source form, so using
        a term instead of source text costs no change of spelling.

        A key may be a NAME or an ATOM. A name means the symbol of that name,
        which is what the engine's own substitution matches and what run()
        takes. An atom means exactly that atom, so `bind({V.x: 5})` fills a
        VARIABLE hole -- the one substitution `unify` reports and the one no
        evaluation call could apply, because a variable crosses the wire as ['v', 'x']
        where a symbol crosses as ['s', 'x'] and the engine matches names.

        `timeout` (seconds) and `inferences` (engine steps) bound the call,
        raising TimeLimitError or InferenceLimitError when hit. A surrounding
        `capture()` scope collects printed text without changing the list.

        `under`, `theory` and `interpreter` are answers()' three, and mean
        exactly what they mean there; `eval()` materialises that query as a list. A
        surrounding `with metta.under(carrier)` reaches here too, which it did
        not before: match() and answers() both honoured such a scope while
        eval() ignored it in silence.

        The answer, delivery, limit, image, on_error and determinism options
        select one evaluation contract. answer=answers retains a replayable
        cursor; answer=stream returns a closable single-pass stream. count,
        exists and none consume only the requested shape. A determinism
        promise is checked before a limit truncates the answers. Image
        projection publishes the type declarations its values require.

        Runs against this context's self space.
        """
        return _cast(_ImplementationSpaceEvalBound, self.self.eval)(target, *more, timeout=timeout, inferences=inferences, under=under, theory=theory, interpreter=interpreter, answer=answer, delivery=delivery, limit=limit, image=image, on_error=on_error, determinism=determinism, **values)

    def stats(self) -> _body_metta__spaces_profile._StatsBlock:
        """The engine's own counters over a with-block, as deltas.

            with m.stats() as s:
                m.match(S.edge(V.x, V.y), S.edge(V.y, V.z))
            s.inferences        # engine steps the block spent
            s.cputime           # engine CPU seconds
            s.walltime          # wall seconds, Python's clock
            s.gc_count, s.gc_freed, s.gc_time
            s.table_bytes       # answer-table bytes grown, tabling's memory

        The counters are SWI's statistics/2 read on the CALLING thread, so
        a block that runs other threads' engine work counts that work too;
        the honest reading is "what this thread saw the engine do while the
        block ran". A lazy cursor is the exception, and a large one: its
        goal runs in an SWI engine, an engine counts its own inferences,
        and this thread cannot see them. Draining 20,000 rows through the
        match cursor reports 40,049 inferences against about 381,000 the
        cursor's engine really spent, 10.5% of the work; the real cost is
        readable off the `inferences` budget, which does count the engine
        [measured 2026-08-27]. The evaluation cursor behind `answers()`
        does report its engine's spend, so that one is whole. The z3py
        Solver.statistics() reading, on the engine this library actually
        has.

        Runs against this context's self space.
        """
        return self.self.stats()

    def get_property(
        self,
        head: _builtins.str | _body_metta__atoms_factories.Symbol,
        /,
    ) -> _builtins.tuple[_body_metta__atoms_factories.Atom, ...]:
        """Return visibility, origins and declared properties of a head.

            space.get_property("car-atom")

        The answers are the atoms ``(get-property car-atom)`` enumerates, including
        every defining origin. An unknown file is empty text and an unknown line
        is -1. The query does not compile a lazy definition.

        Runs against this context's self space.
        """
        return self.self.get_property(head)

    def match(
        self,
        *patterns: _body_typing.Any,
        where: _body_typing.Any | None=None,
        limit: _builtins.int | None=None,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        under: _body_typing.Any=_body_metta__atoms_designation._UNSET,
        into: _body_builtins.type | None=None,
        **values: _body_typing.Any,
    ) -> _body_typing.Any:
        """Lazily match patterns against this space as one conjunction.

        Variables shared between patterns join, the engine's own match/4
        doing the joining. Columns are the variable names in first
        appearance order. `where` is a guard term over the same variables,
        evaluated per join and required true, so restrictions a pattern
        cannot spell (an inequality) compose onto the match:

            m.match(S.person(V.name, V.age), where=V.age.ge(18))

        `limit` bounds the answers, the engine stopping at the count
        rather than trimming afterwards. `timeout` (seconds) and
        `inferences` (engine steps) bound the whole call, raising
        TimeLimitError or InferenceLimitError when hit, for joins whose
        size is not known in advance.

        The returned Answers view pulls only what Python observes. ``bool``
        pulls one row, exact-one operations pull at most two, and slicing
        retains an Answers view. ``len`` uses an engine-side aggregate when
        no row has yet been pulled.

        ``under=`` interprets the same ask through an annotation algebra.
        ``under=counting`` answers one ``TaggedAnswer`` whose annotation is
        the engine-computed count, including duplicate derivations without
        crossing their rows into Python. Ordered carriers sort in their
        declared direction before slicing, so
        ``m.match(q, under=ranked)[:3]`` is top-k and
        ``under=tropical`` puts the cheapest annotation first. Other carriers
        answer ``TaggedAnswer`` values with ``annotation``, ``why()`` and
        ``under(other)``; the latter two reuse the retained derivation rather
        than querying the space again. ``with metta.under(carrier)`` supplies
        the carrier when this call has no explicit ``under=``.

        `into=Rows` explicitly chooses the eager Rows face. Other `into=`
        values shape each row into a dataclass, NamedTuple, or
        TypedDict matched by field name, sqlite3's row_factory reading:
        `m.match(S.edge(V.a, V.b), into=Edge)` answers `list[Edge]`,
        and Rows stays the default so nothing is lost. A one-variable query
        whose column holds complete constructor expressions rebuilds those
        expressions instead: `m.match(V.edge, into=Edge)`.

            m.match(S.Edge(V.x, V.y), S.Edge(V.y, V.z))

        A text pattern may carry HOLES, as run()'s source may:
        `m.match(t"(person {name} $age)")` matches the value itself, so a name
        holding a space stays one String atom rather than reading as two
        symbols. Keyword values apply across every pattern of the call.

        Runs against this context's self space.
        """
        return self.self.match(*patterns, where=where, limit=limit, timeout=timeout, inferences=inferences, under=under, into=into, **values)

    def solve(self, pattern: _body_typing.Any, subject: _body_typing.Any) -> _body_typing.Any:
        """Run relational ``let`` and return bindings keyed by its variables.

        ``solve(4, V.x - 1).x`` places the known value on let's pattern side,
        lets the arithmetic relation solve backwards, and projects ``x``.
        The answer template is derived from the pattern's variables followed
        by any new subject variables, so either relational direction can
        introduce the bindings and the third hand-written ``let`` argument
        disappears.

        Runs against this context's self space.
        """
        return self.self.solve(pattern, subject)

    def limits(
        self,
        *,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        stack: _builtins.int | None=None,
    ) -> _body_metta__spaces_scope.ScopedLimits:
        """Scoped default bounds for every call in the with-block:

            with m.limits(inferences=1_000_000, timeout=2.0):
                m.match(...)      # bounded without saying so again

        decimal.localcontext's shape, contextvars underneath, so the
        scope is async-correct and per-task. A per-call timeout= or
        inferences= still overrides, which is the whole ladder: one
        block replaces the parameter forest, and the forest remains
        for whoever wants per-call control.

        stack= is SWI's combined stack ceiling in BYTES, the bound a
        runaway recursion hits as a StackOverflow error atom. It is NOT
        MeTTa's reduction depth: that is the max-stack-depth pragma,
        `(with-pragma! ((max-stack-depth N)) expr)`, which counts
        reduction steps and is scoped in the program text.

        Runs against this context's self space.
        """  # noqa: D415 -- preserve the declared documentation
        return self.self.limits(timeout=timeout, inferences=inferences, stack=stack)

    def speculate(self) -> _body_metta__spaces_execution.ScopedExecution:
        """Run each CALL against a snapshot and discard its writes.

        Per call, the write doors included: ``m.add(atom)`` inside the block
        leaves nothing behind, exactly as ``m.run("!(add-atom &self ...)")``
        in the same block does, and a later call in the block does not see
        what an earlier one wrote, because each call is its own what-if.

        Runs against this context's self space.
        """
        return self.self.speculative()

    def run(
        self,
        source: _builtins.str | _body_metta__atoms_designation.TemplateLike,
        /,
        *,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
        **values: _body_typing.Any,
    ) -> _builtins.list[_builtins.list[_body_metta__atoms_factories.Atom]]:
        """Run MeTTa source: one list of answers per ! directive.

        The pipeline is the engine's own reader, compiler and evaluator, so
        the answers are exactly what the CLI would print, kept grouped per
        directive instead of flattened. Equations and facts in the source
        land in this space.

        The source may carry HOLES, which are bindings by position:

            m.run(t"!(fib {n})")            # a 3.14 t-string literal
            m.run("!(fib {n})", n=10)       # the same on every version

        Each hole is spliced into the text as a generated symbol and bound to
        its value, so a str stays one String atom and never has to be escaped.
        Values enter through `encode`: an int is a Number, a str a String, an
        Atom itself, a Space its handle. The markers at a hole are the atom
        constructors, `{Symbol(name)}`, `{Grounded(obj)}` and `{parse(text)}`,
        with the specs `:sym`, `:py` and `:expr` as their short forms; `!r`
        and `!s` convert in Python first and enter the result as text. A hole
        inside a string literal, a comment or a symbol is refused with its
        line and column.

        `bind()` is the same substitution by NAME, for a value several calls
        share, the way DuckDB reads a local dataframe by its variable name:

            with m.bind({"graph": my_graph}):
                m.run("!(py-len graph)")

        Each named symbol substitutes to its value (objects by identity),
        after reading, before anything runs. It is a BLOCK rather than a
        keyword because a binding mapping is the kind of value that grows,
        and a block grows down the page where a keyword has to fit beside
        everything else on the call. Every call that accepts a target reads the
        same scope, so one block covers run(), eval(), and answers() together.
        A binding names a symbol and so replaces EVERY occurrence of it,
        including one the author meant as a symbol; a hole is positional and
        cannot reach anything but itself.

        `timeout` (seconds) and `inferences` (engine steps) bound the call
        with the engine's own guards; passing either raises TimeLimitError
        or InferenceLimitError when the bound is hit, and whatever the
        source completed before the stop, writes included, stands.

        `with m.capture() as output` collects printed text in `output.text`
        without changing this method's return shape. `with m.atomic()`
        and `with m.speculative()` scope execution policy without boolean
        combinations on each call. Atomic commits or rolls
        back each complete source; speculative answers and discards its
        writes. Both cover engine state; Python side effects and subscription
        callbacks already fired stay where they happened.

        A term the engine hands back unevaluated is an ordinary MeTTa value,
        not a failure: `!(hello world)` answers `(hello world)` and that is
        the whole of hello world in this language. eval_status() reports
        which answers reduced and which did not, as data, for a caller who
        wants to decide about it.

        Runs against this context's self space.
        """
        return self.self.run(source, timeout=timeout, inferences=inferences, **values)

    def load(
        self,
        path: _builtins.str | _body_os.PathLike[_builtins.str],
        *,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
    ) -> _builtins.list[_builtins.list[_body_metta__atoms_factories.Atom]]:
        """Add a text program or trusted fast cache to this space.

        This is a consult, so it always loads and what it loads REPLACES
        what the same file put in this space before. Edit the file, load it
        again, and the space holds the new definitions and not both; the
        engine says on stderr which file it replaced and how many atoms
        went. Atoms from other sources, and ones you added yourself, stay.
        A load that raises leaves the previous definitions standing, so a
        broken edit costs nothing but the error.

        `!(import! &self path)` is the other form and loads a file that is
        new or edited, skipping one that is neither. The two agree on what
        a reload means and differ only in whether an unchanged file runs
        again, which is SWI's consult/1 against its if(changed).

        A .gz path is detected and read through the decompressed bytes.

        `timeout` (seconds) and `inferences` (engine steps) bound the load
        with the engine's own guards, raising TimeLimitError or
        InferenceLimitError. A load is all or nothing: a stop takes back
        everything the file had put in a space, the same way a load that
        fails on a bad form does, because a file the space holds half of is
        not a file it can replace later. run() is the entry point that
        keeps finished work when a bound stops it. This is the one most
        likely to be handed code the caller did not write, since a file can
        carry `!` directives and an import graph, so it takes the same pair
        its siblings take.

        Program text with holes is refused here. A hole is a binding, and a
        PATH has nowhere to bind one: run() takes holes, and an f-string or a
        Path builds a computed filename.

        Runs against this context's self space.
        """
        return self.self.load(path, timeout=timeout, inferences=inferences)

    def add(self, *atoms: _body_typing.Any) -> None:
        """Add atoms to this space, one engine round-trip for the lot.
        An (= ...) atom compiles as an equation. Every Atom shape crosses
        unchanged, including a bare Symbol, Grounded value, and empty
        Expression; a free Variable receives the engine's own
        insufficient-instantiation refusal. The MeTTa longhand is
        `!(add-atoms <space> (<atom> ...))`. It is NOT `add-atom`, which is
        upstream PeTTa's spelling and takes upstream's domain: a headless atom
        cannot become a fact in a space there, so `!(add-atom &self b)` has no
        answer on either engine. This space is wider and `add-atoms` is the
        door onto the wider part.

        A variable's NAME is not stored. `(rule $x $y)` reads back as
        `(rule $_17902 $_17904)`, because a variable is an identity and not a
        spelling. That is the right property for a logic engine and it is the
        one thing about storage that surprises everybody once.

        A library IS knowledge, so the same operator imports it: ``m += lib.he``
        performs ``!(import! <m> (library lib_he))`` with this space as the
        target. An import is an effect, so it refuses to hide inside an atom
        batch or share a call with stored atoms.

        Runs against this context's self space.
        """  # noqa: D205 -- preserve the declared documentation
        return self.self.add(*atoms)

    def from_(self, source: _body_typing.Any, map: _body_typing.Any=None) -> None:  # noqa: A002 -- the declared public spelling
        """Reference a library or space through a stored ``(from source map)`` row.

            target.from_(metta.lib.string, metta.parse("(prefix str-)"))
            target.from_(home)

        A missing map uses this space's ``from-map`` pragma. Definitions run in
        their home and later additions follow the standing row. Removing the row
        withdraws its links. Loading follows this space's ``load`` pragma.

        Runs against this context's self space.
        """
        return self.self.from_(source, map)

    def remove(
        self,
        atom: _body_typing.Any,
        *more: _body_typing.Any,
    ) -> _builtins.bool | _builtins.int:
        """Remove ONE unifying occurrence and say whether one was there,
        which is Python's own `list.remove` grain.

        Variadic like `add` and `transfer`: several atoms ride one engine
        crossing inside one transaction, and the answer counts the found,
        so the one-atom call still reads as the truth value it always
        was.

        `space -= atom` is this same grain without the report, the way
        `+=` is `add` without one: Python's in-place difference over a
        MULTISET, whose own Python spelling is `collections.Counter`,
        subtracts the multiplicity given rather than clearing the key.
        That is the only reading under which the operators are inverses,
        so `s += a; s -= a` leaves the space it found. `-=` classifies its
        operand exactly as `+=` does, so `-=` subtracts the same fact stream
        `+=` stores, one occurrence per element, in one
        transactional crossing.

        `del m[pattern]` is the draining form: it takes every
        unifying occurrence in one crossing and raises when nothing
        matched, as Python's `del` does, and MeTTa spells it `remove-atom`
        [source: engine/spaces/foreign.pl, remove_matching_atoms/2].
        MeTTa spells this method's grain `subtract-atom`. This is the one
        method that reports absence.

        A bare variable is the remove-everything reading a multiset space
        gives it, each atom leaving through its own proper path, equations
        and their compiled clauses included.

        Runs against this context's self space.
        """  # noqa: D205 -- preserve the declared documentation
        return self.self.remove(atom, *more)

    def __len__(self) -> _builtins.int:
        """Read Space.__len__.

        Runs against this context's self space.
        """
        return self.self.__len__()

    def __bool__(self) -> _builtins.bool:
        """Always true: a space is a handle to a store, not a value that
        dwindles. Without this, bool() falls through to __len__ and an
        empty space is falsy, so `if space:` skips a perfectly good empty
        space, the bug class that made datetime stop treating midnight as
        false in 3.5. Existence is an ask: use
        ``bool(space.match(V.x))`` rather than ``bool(space)``.

        Runs against this context's self space.
        """  # noqa: D205 -- preserve the declared documentation
        return self.self.__bool__()

    def __contains__(self, atom: _body_typing.Any) -> _builtins.bool:
        """Read Space.__contains__.

        Runs against this context's self space.
        """
        return self.self.__contains__(atom)

    def __iadd__(self, atom: _body_typing.Any) -> _Self:
        """add()'s operator spelling for one atom or one fact stream.

        ``m += (S.Edge, a, b)`` adds one fact. ``m += [(S.Edge, a, b),
        (S.Edge, b, c)]`` and a generator yielding those rows add two. A built
        Expression is always one atom even though it implements Sequence.
        Dataframes use ``iter_rows`` or ``itertuples(index=False)``. The
        explicit ``add(list_value)`` method remains available when a list itself
        is intended as one transparent expression.

        Relative ``S.admits(Type)``, ``S.capacity(n)``, and
        ``S.covers(effect)`` values are declared data: they install the same
        contract as the receiver methods and are not stored in this space.
        Explicit ``add(...)`` remains the raw storage method for those shapes.

        Runs against this context's self space.
        """
        self.self.__iadd__(atom)
        return self

    def __isub__(self, atom: _body_typing.Any) -> _Self:
        """Read Space.__isub__.

        Runs against this context's self space.
        """
        self.self.__isub__(atom)
        return self

    def __ior__(self, other: _body_typing.Any) -> _Self:
        """Merge into this space in one bulk crossing: every atom of
        another space, of a registered space name, or of an iterable.

            m |= other_space     # every atom, equations included
            m |= "&kb"           # the space registered under this name
            m |= [a, b, c]       # each element becomes one atom

        Equations in the merge compile on arrival, the same rule add()
        enforces. A space is a multiset, so merging a space into itself
        doubles every atom. A Mapping is refused because add(d) reads the
        same dict as ONE grounded atom and its values would silently
        vanish here; spell the reading you mean. Strings name spaces, so
        an unregistered name is a KeyError rather than a parse.

        Runs against this context's self space.
        """  # noqa: D205 -- preserve the declared documentation
        self.self.__ior__(other)
        return self

    def __iter__(self):
        """Iterate one assembly-order snapshot of the stored atoms.

        A native or inherited-native space materializes its readable chain
        when ``iter(space)`` is called, so later additions and removals do not
        alter that iterator. A Python-backed space likewise materializes its
        provider's ``atoms()`` result before returning the iterator; the
        provider owns and must document how concurrent mutation behaves while
        that one enumeration itself is being produced.

        Runs against this context's self space.
        """
        return self.self.__iter__()

    def __getitem__(self, i: _body_typing.Any) -> _body_metta.Rows:
        """Subscription is query. A tuple headed by an atom is one built
        expression pattern; a tuple of complete expression patterns is a join:

            m[(S.Parent, V.x, S.Bob)]
            m[S.edge(V.a, V.b), S.edge(V.b, V.c)]

        Python hands both spellings to ``__getitem__`` as a tuple, so shape is
        the visible classifier. A mixed tuple beginning with a complete
        pattern and followed by a bare atom can only be the tuple mistake; it
        raises and names the one-pattern and join spellings instead of
        silently asking an impossible bare-atom conjunct.

        A str key parses first, matching match()'s tolerance. A slice is
        refused: a slice of a space has no one meaning, and the bounded
        readings have their own methods, match(limit=) for a bounded answer
        set and stream() for rows pulled until you have seen enough.

        Runs against this context's self space.
        """  # noqa: D415, D205 -- preserve the declared documentation
        return self.self.__getitem__(i)

    def __delitem__(self, pattern: _body_typing.Any) -> None:
        """Del m[pattern] removes every unifying occurrence, the bulk
        spelling of remove()'s multiset subtraction: m[pattern] is a
        query answering many rows, so deleting it deletes them all, the
        way DELETE WHERE does. Nothing unifying raises KeyError, as
        del d[k] does on a missing key; remove() is the method that
        reports absence as False instead.

        It asks the engine's own drain, so the whole pattern costs ONE
        crossing rather than one per removed atom.

        Runs against this context's self space.
        """  # noqa: D205 -- preserve the declared documentation
        return self.self.__delitem__(pattern)

    @_overload
    @_body_typing.dataclass_transform(eq_default=False)
    def define(  # type: ignore[overload-overlap]
        self,
        fn: _body_builtins.type[_body_metta__atoms_designation._T],
        /,
        *,
        accessors: _builtins.bool=...,
        methods: _builtins.bool=...,
    ) -> _body_builtins.type[_body_metta__atoms_designation._T]:
        ...
    @_overload
    def define(
        self,
        fn: _body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R],
        /,
        *,
        name: _builtins.str | None=...,
        accessors: _builtins.bool=...,
        methods: _builtins.bool=...,
    ) -> _body_metta.Defined[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]:
        ...
    @_overload
    def define(
        self,
        *,
        name: _builtins.str,
    ) -> _body_collections_abc.Callable[[_body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]], _body_metta.Defined[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]]:
        ...
    @_overload
    def define(
        self,
        *,
        prolog: _builtins.str | _body_os.PathLike[_builtins.str],
        name: _builtins.str | None=None,
    ) -> _body_collections_abc.Callable[[_body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]], _body_metta__declare_define.PrologBacked[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]]:
        ...
    def define(
        self,
        fn: _body_collections_abc.Callable[..., _body_typing.Any] | None=None,
        *,
        prolog: _builtins.str | _body_os.PathLike[_builtins.str] | None=None,
        name: _builtins.str | None=None,
        accessors: _builtins.bool=True,
        methods: _builtins.bool=True,
    ) -> _body_typing.Any:
        """Compile a Python function into MeTTa equations, decorator-style.

        With `prolog=`, the Prolog file is registered and becomes the
        function, and the Python stays as the reference twin rather than
        being compiled:

            @m.define(prolog=Path(__file__).parent / "fast.pl")
            def vec_dot(a, b):
                return sum(x * y for x, y in zip(a, b))

            m.eval("(vec-dot (1 2) (3 4))")[0] # the Prolog answer
            vec_dot.py((1, 2), (3, 4))          # the reference answers

        Rewriting a defined function in Prolog for speed used to mean
        deleting the Python and the differential oracle with it. Here both
        are declared together and `metta.testing.check_twin` proves they
        agree on ground inputs. The file must register the function's own
        MeTTa name and at the twin's arity, inputs then one output, and
        says so if it does not; its `metta_export` declaration owns the
        types, so annotations on the Python are documentation only.

        Written for whoever is fluent in Python rather than s-expressions:
        the body is read as syntax and lowered deterministically, refusals
        name the construct, the line and what to write instead, and the
        original stays reachable as .py, a twin the equations can be checked
        against on any ground input.

            @m.define
            def add_one(n):
                return n + 1

            add_one(5)                  # [6], evaluated by the engine
            S.add_one(5)                # (add_one 5), staged as data
            add_one.py(5)               # 6, ordinary Python

        The equation's implicit name applies the factories' total mechanical
        map, replacing each underscore with a hyphen. ``name=`` is the exact
        quoted-name escape for punctuation that map cannot preserve:

            @m.define(name="add-one")
            def add_one(n):
                return n + 1

        The same attribute mapping applies to the definition name itself:
        ``def not_provable`` lands as ``not-provable``. An authored
        MeTTa underscore therefore uses explicit ``name="not_provable"``.

        A generator compiles to nondeterminism (each yield one answer), a
        lambda to the engine's own |->, a comprehension to map-atom and
        filter-atom, and match(Pattern(x, y), template) to a match against
        the running space, lowercase free names in the pattern binding as
        variables.

        Runs against this context's self space.
        """
        return _cast(_ImplementationSpaceDefineBound, self.self.define)(fn, prolog=prolog, name=name, accessors=accessors, methods=methods)

    def doc(self, atom: _body_typing.Any) -> _body_metta__atoms_factories.Atom:
        """Return this space's structured ``get-doc`` answer for one subject.

        The answer is the ``(@doc ...)`` atom the engine holds for the
        subject, whether it was documented in MeTTa source or built from a
        Python docstring:

            m.doc(S.area)
            # (@doc-formal (@item area) (@kind function) (@desc "Circle area.") ...)

        A subject with no documentation raises, exactly as ``type`` raises
        for a subject ``get-type`` cannot answer.

        Runs against this context's self space.
        """
        return self.self.doc(atom)

    @_overload
    def op(
        self,
        fn: _body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R],
        /,
        *,
        name: _builtins.str | None=...,
        transport: _body_metta__declare_operations.Transport=...,
        effect: _body_metta_vocabularies.EffectClass | _builtins.str,
        declarations: _body_collections_abc.Iterable[_body_metta__atoms_factories.Atom]=...,
        arities: _builtins.list[_builtins.int] | None=...,
        inverse: _body_collections_abc.Callable | None=...,
    ) -> _body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]:
        ...
    @_overload
    def op(
        self,
        *,
        name: _builtins.str | None=...,
        transport: _body_metta__declare_operations.Transport=...,
        effect: _body_metta_vocabularies.EffectClass | _builtins.str,
        declarations: _body_collections_abc.Iterable[_body_metta__atoms_factories.Atom]=...,
        arities: _builtins.list[_builtins.int] | None=...,
        inverse: _body_collections_abc.Callable | None=...,
    ) -> _body_collections_abc.Callable[[_body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]], _body_collections_abc.Callable[_body_metta__atoms_designation._P, _body_metta__atoms_designation._R]]:
        ...
    def op(
        self,
        fn: _body_collections_abc.Callable | None=None,
        *,
        name: _builtins.str | None=None,
        transport: _body_metta__declare_operations.Transport='encoded',
        effect: _body_metta_vocabularies.EffectClass | _builtins.str | None=None,
        declarations: _body_collections_abc.Iterable[_body_metta__atoms_factories.Atom]=(),
        arities: _builtins.list[_builtins.int] | None=None,
        inverse: _body_collections_abc.Callable | None=None,
    ) -> _body_typing.Any:
        """Register a Python callable as a MeTTa function, decorator-style.

            @m.op(effect=EffectClass.pureStructural)
            def double(x: int) -> int:
                return 2 * x                    # !(double 21) -> 42

            @m.op(effect=EffectClass.nondeterministicReadOnly)
            def neighbours(n: int):
                yield n - 1                     # a generator is nondeterministic
                yield n + 1

        An implicit Python name maps underscores to MeTTa hyphens. ``name=``
        is exact, for source vocabularies that deliberately use underscores.

        A name must read back as one MeTTa symbol. A space, parenthesis,
        quote, comment opener, variable spelling, number, boolean, or another
        registered reader token is refused before any registry changes, with
        the name and the conflicting character in the error.

        Annotations become ordinary `(: ...)` declarations. An unannotated
        callable makes no type claim. `transport="raw"` skips wire encoding
        both ways and is reflected as raw_det or raw_many in `(op ...)`;
        symbols then reach Python as strings, so encoded transport is the
        fidelity-preserving default. unregister_op(name) removes every
        registered arity and every declaration the registration owns.

        An `Atom` parameter changes evaluation order. The declaration tells
        the compiler to pass the argument as written, before it reduces:

            @m.op(effect=EffectClass.pureStructural)
            def anyatom(term: Atom) -> Atom:
                return term

            # with (= (side) 42), !(anyatom (side)) answers (side)

        An unconstrained parameter receives the evaluated value instead, so
        the otherwise identical `def anyval(term): return term` answers 42.
        Use `Atom` only when the operation deliberately implements syntax or
        a control form; it is not just a static hint.

        An encoded generator may instead yield exact tuples as positional
        relation rows, or exact dicts keyed by parameter name as sparse rows.
        The engine unifies each candidate against the written call, so one
        implementation serves free, partially bound, and ground arguments:

            @m.op
            def route(origin, destination):
                yield (S.paris, S.lyon)
                yield {"destination": S.nice}  # origin is unconstrained

            # route(V.origin, S.lyon).rows[0].origin == S.paris

        Each matching occurrence answers unit and duplicate yields remain
        duplicate answers. Use `Answer(value=...)` when an exact tuple or dict
        is the result value rather than a parameter row. Relational rows
        require encoded transport; raw calls cannot carry unbound argument
        positions.

        When evaluation order stays ordinary but the callable needs the
        resulting Atom wrappers, declare that policy as data:

            m.op(
                inspect_atom,
                name="inspect-atom",
                effect=EffectClass.pureStructural,
                declarations=[parse("(arguments inspect-atom atoms)")],
            )

        The declaration is matchable in &metta and is retired with the
        operation. Raw transport refuses this declaration because it bypasses
        the atom codec entirely.

        The cost ladder, measured on the maintained box in inferences per
        call, explains the transport choice:

            native MeTTa function            9.11   the floor
            transport="raw"                10.11   opaque handles, near-native
            encoded                        17.11   encoded values
            encoded, typed literal         17.11   the check hoists to compile
            py-call, dotted                 22.11   the ad-hoc escape hatch

        The ergonomic default (encoded, typed) costs about 1.7x raw on the
        counter and more on wall clock, since encoding walks the value both
        ways; a registered raw operation measured 0.85us against 2.26us
        encoded. Bulk data should stay opaque: one transparent 64-float
        crossing costs 330 inferences where the handle costs 10.

        `inverse=` remains the distinct-output form. Use it when the forward
        operation returns a result and a separate callable must recover the
        arguments from that result:

            m.op(
                cons,
                name="cons",
                inverse=uncons,
                effect=EffectClass.pureStructural,
            )
            # !(let (cons $h $t) (1 2 3) ($h $t))  ->  (1 (2 3))

        It takes the result and returns the arguments, as a tuple, or the
        bare value at arity one; a generator enumerates every preimage, and
        None or NotReducible means there is none. It runs only when the arguments
        are not ground and the result is, so a forward call never reaches it,
        and an operation without one compiles exactly what it did before.

        A parameter annotated `metta.MeTTa` is the framework's to fill,
        FastAPI's Depends read with the house convention that the
        annotation is the request. The engine injects itself bound to the
        CALLING context's space, so an operation invoked from a program
        running in &kb queries &kb; the slot never counts toward MeTTa
        arities or the declared arrow, and only operations that ask pay
        the weaving:

            @m.op(effect=EffectClass.nondeterministicReadOnly)
            def related(term, engine: metta.MeTTa):
                for row in engine.match(Expression(S.link, term, V.x)):
                    yield row[0]

        Every operation declares its strongest observable effect. The five
        ordered choices are ``pureStructural``, ``readOnlyLookup``,
        ``nondeterministicReadOnly``, ``writesState``, and ``oracleIO``:

            m.op(
                len,
                name="size",
                effect=EffectClass.pureStructural,
            )
            # (= (count-of $x) (size $x))  is cacheable

        It is an allow-list on purpose. An operation that does not say so is
        refused by name in a cached body, loudly, rather than cached and
        quietly wrong.

        Runs against this context's self space.
        """
        return _cast(_ImplementationSpaceOpBound, self.self.op)(fn, name=name, transport=transport, effect=effect, declarations=declarations, arities=arities, inverse=inverse)

    def pure(
        self,
        fn: _body_collections_abc.Callable | None=None,
        /,
        **options: _body_typing.Any,
    ) -> _body_typing.Any:
        """An operation whose answer depends only on its arguments.

            @m.pure
            def double(x: int) -> int:
                return 2 * x

        The cache-safe class, and the only one memoization and tabling admit
        without an explicit policy.

        A GENERATOR written this way is lifted to `nondeterministicReadOnly`,
        because a generator is nondeterministic whatever it declares, and the
        registration reads that off the function rather than asking. The lift
        only ever raises the rank, so it widens the answer-count claim and
        never weakens the effect claim -- but it does mean a generator is not
        cache-safe, which is the whole reason it is lifted out of this class
        [tested: test_a_generator_is_lifted_to_the_nondeterministic_rank;
        commit=7e5091540a8dc0903bcee24f3e5b8b85a19f805f].

        Every ``op`` keyword applies: ``name``, ``arities``,
        ``declarations``, ``inverse`` and ``transport``. They arrive as
        ``**options`` and forward unchanged, so the signature above shows
        the mechanism and this line shows the surface.

        Runs against this context's self space.
        """
        return self.self.pure(fn, **options)

    def reads(
        self,
        fn: _body_collections_abc.Callable | None=None,
        /,
        **options: _body_typing.Any,
    ) -> _body_typing.Any:
        """An operation that reads stable state without changing it.

        Every ``op`` keyword applies: ``name``, ``arities``,
        ``declarations``, ``inverse`` and ``transport``. They arrive as
        ``**options`` and forward unchanged, so the signature above shows
        the mechanism and this line shows the surface.

        Runs against this context's self space.
        """
        return self.self.reads(fn, **options)

    def writes(
        self,
        fn: _body_collections_abc.Callable | None=None,
        /,
        **options: _body_typing.Any,
    ) -> _body_typing.Any:
        """An operation that changes engine or host state.

        Every ``op`` keyword applies: ``name``, ``arities``,
        ``declarations``, ``inverse`` and ``transport``. They arrive as
        ``**options`` and forward unchanged, so the signature above shows
        the mechanism and this line shows the surface.

        Runs against this context's self space.
        """
        return self.self.writes(fn, **options)

    def io(
        self,
        fn: _body_collections_abc.Callable | None=None,
        /,
        **options: _body_typing.Any,
    ) -> _body_typing.Any:
        """An operation that observes an external oracle.

        A clock, randomness, a network, a file, another runtime.

            @m.io
            def now() -> float:
                return time.time()

        The fail-closed top of the lattice. Declare it when what the operation
        reaches is decided at run time or by a library the engine cannot bound.

        Every ``op`` keyword applies: ``name``, ``arities``,
        ``declarations``, ``inverse`` and ``transport``. They arrive as
        ``**options`` and forward unchanged, so the signature above shows
        the mechanism and this line shows the surface.

        Runs against this context's self space.
        """
        return self.self.io(fn, **options)

    def debug(
        self,
        source: _body_metta__atoms_factories.Atom | _builtins.str,
        *,
        on: _body_typing.Any=None,
        inferences: _builtins.int | None=None,
        at: _builtins.int | None=None,
    ) -> _body_metta__observe_debug.Debugger:
        """Run a TERM, or source, under breakpoints, stepped from Python.

        Iterating the Debugger runs the program to each breakpoint, the loop
        body is where the program is SUSPENDED, and leaving the body resumes
        that same execution:

            with m.debug(S.quad(3), on=[S.double]) as d:
                for stop in d:
                    print(stop)      # halted here
                    if stop.depth > 2:
                        d.step()     # stop at the next reduction instead
                print(d.answers)

        on= names the functions that stop it, the way every door here names a
        head; naming none runs the program to the end in one advance.
        `step()` stops at the very next reduction, breakpoint or not, and
        lasts one advance. `breakpoints` is a live set, so one added while
        the program is suspended stops it.

        at= is the third kind of breakpoint, a COUNT: it stops at the event
        with that sequence number, numbering reductions from 0 the way a
        Recording numbers them, so `at=200` is "put me where event 200 is".
        `Recording.debug(at=k)` is the convenience over this one.

        inferences bound the WHOLE session cumulatively, so a resume that
        would never reach another breakpoint stops. There is no timeout:
        the session is suspended by design and a clock would run while a
        person reads a stop. What is debugged executes for real, writes
        included, and inherits the caller's scope. Close it, or leave its
        with-block: the session holds a wrapper on every compiled function
        until it does.

        Runs against this context's self space.
        """
        return self.self.debug(source, on=on, inferences=inferences, at=at)

    def record(
        self,
        source: _body_metta__atoms_factories.Atom | _builtins.str,
        *,
        seed: _builtins.int | None=None,
        max_events: _builtins.int | None=None,
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
    ) -> _body_metta__observe_recording.Recording:
        """Run a TERM, or source, and keep the whole run as data.

        The data walks backwards, saves to a file, and re-runs.
        `m.trace` is the rung below: it answers the events alone. A Recording
        is those events plus the state that produced them, which is what makes
        them re-runnable rather than only readable:

            rec = m.record(S.fib(12))
            rec.save("fib.metta-rec.json")
            rec.at(-1)               # the last event, with its call stack
            rec.back()               # a step backwards costs a lookup
            rec.replay(other)        # the same run, in another engine
            with rec.debug(at=17) as d:   # live, stopped where event 17 is
                print(d.stop)

        A recorded run always has a seed, minted when you do not name one,
        because a replay that cannot reproduce the draws is not a replay; the
        generator is restored afterwards. `(with-seed S expr)` is the MeTTa
        spelling of the same scope.

        max_events bounds the RECORDING and timeout and inferences bound the
        RUN, exactly as on trace(); a cut recording says so through
        `rec.events.stopped` and replays to the same length. A program whose
        effect plan reaches oracleIO is recorded with `replayable` false and
        the reason naming what it reached, and replay() then refuses rather
        than re-reading the host.

        Runs against this context's self space.
        """
        return self.self.record(source, seed=seed, max_events=max_events, timeout=timeout, inferences=inferences)

    def trace(
        self,
        source: _body_metta__atoms_factories.Atom | _builtins.str,
        max_events: _builtins.int | None=None,
        *,
        filter: _body_metta__atoms_factories.Symbol | _builtins.str | _body_collections_abc.Iterable[_body_metta__atoms_factories.Symbol | _builtins.str] | None=None,  # noqa: A002 -- the declared public parameter spelling
        timeout: _builtins.float | None=None,
        inferences: _builtins.int | None=None,
    ) -> _body_metta__observe_trace.Trace:
        """Run a TERM, or source, under the engine's reduction trace and
        answer TraceEvent records: what entered reduction at which depth,
        what it answered, and which reductions failed (a call with no
        exit). `m.trace(S.fib(10))` is the ordinary spelling, the same
        argument `answers` and `eval` take; a string is still a string.
        What is traced executes for real, writes included, like run();
        the wrap exists only while tracing, so untraced calls pay
        nothing and the wrapping itself is not charged to the bounds
        below. max_events bounds the RECORDING and timeout,
        inferences and stack bound the RUN, defaulting to whatever
        `m.limits()` scopes; they are independent because a program can
        retire millions of inferences inside a handful of recorded
        events. Whichever one stops it, the events already recorded are
        ANSWERED and `stopped` names the bound, so a caller told a trace
        was cut knows which bound to raise.
        filter selects exact function Symbols or names, singly or in an iterable.
        None records all functions; [] records none. Selection happens before
        the recording bounds, while excluded calls still execute and add depth.

        Runs against this context's self space.
        """  # noqa: D205 -- preserve the declared documentation
        return self.self.trace(source, max_events, filter=filter, timeout=timeout, inferences=inferences)



if TYPE_CHECKING:
    import metta as _body_metta
else:
    _body_metta = _lazy('metta')
