# Purpose: declare every generated fn attribute to static type checkers.
# Guarantees:
#   - every safe runtime alias is explicit and no dynamic Any fallback exists
#     [tested: test_the_fn_namespace_is_generated; commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
# Open Obligations:
#   To Do: None
#   Hacks: None
#   Future Enhancements: None.

from typing import Final

from .atoms import Symbol

class _FunctionNamespace:
    abs_math: Symbol
    acos_math: Symbol
    add_atom: Symbol
    add_atoms: Symbol
    add_reduct: Symbol
    add_reducts: Symbol
    add_translator_rule: Symbol
    add_typing_rule: Symbol
    alpha_unique: Symbol
    alpha_unique_atom: Symbol
    and_then: Symbol
    annotation: Symbol
    append: Symbol
    argv: Symbol
    asin_math: Symbol
    atan_math: Symbol
    atomically: Symbol
    bind: Symbol
    call: Symbol
    car_atom: Symbol
    case: Symbol
    catch: Symbol
    cdr_atom: Symbol
    ceil_math: Symbol
    chain: Symbol
    change_state: Symbol
    collapse: Symbol
    cons: Symbol
    cons_atom: Symbol
    context_space: Symbol
    cos_math: Symbol
    current_time: Symbol
    cut: Symbol
    declare_post_add: Symbol
    declare_pre_add: Symbol
    decons: Symbol
    decons_atom: Symbol
    defined_name: Symbol
    dif: Symbol
    documented: Symbol
    documented_space: Symbol
    elapsed: Symbol
    empty: Symbol
    eval: Symbol
    evalc: Symbol
    exclude_item: Symbol
    exp: Symbol
    exp_math: Symbol
    explain: Symbol
    filter_atom: Symbol
    first: Symbol
    first_from_pair: Symbol
    floor_math: Symbol
    foldall: Symbol
    foldl: Symbol
    foldl_atom: Symbol
    for_each_in_atom: Symbol
    forall: Symbol
    format_args: Symbol
    format_time: Symbol
    get_atoms: Symbol
    get_doc: Symbol
    get_doc_atom: Symbol
    get_doc_function: Symbol
    get_doc_params: Symbol
    get_doc_single_atom: Symbol
    get_doc_space: Symbol
    get_metatype: Symbol
    get_state: Symbol
    get_type: Symbol
    get_type_space: Symbol
    git_import: Symbol
    has_declared_type: Symbol
    help: Symbol
    hyperpose: Symbol
    id: Symbol
    if_equal: Symbol
    if_equal2: Symbol
    if_error: Symbol
    implies: Symbol
    include: Symbol
    index_atom: Symbol
    inferences: Symbol
    intersection: Symbol
    intersection_atom: Symbol
    is_alpha_member: Symbol
    is_expr: Symbol
    is_function: Symbol
    is_ground: Symbol
    is_member: Symbol
    is_space: Symbol
    is_var: Symbol
    isinf_math: Symbol
    isnan_math: Symbol
    last: Symbol
    length: Symbol
    let: Symbol
    library: Symbol
    log_math: Symbol
    map_atom: Symbol
    maplist: Symbol
    match: Symbol
    match_type_or: Symbol
    match_types: Symbol
    max: Symbol
    max_atom: Symbol
    member: Symbol
    metta: Symbol
    min: Symbol
    min_atom: Symbol
    mm2_exec: Symbol
    mork_add_atoms: Symbol
    mork_flush: Symbol
    msort: Symbol
    new_space: Symbol
    new_state: Symbol
    noeval: Symbol
    nop: Symbol
    noreduce_eq: Symbol
    not_provable: Symbol
    once: Symbol
    or_else: Symbol
    parse: Symbol
    pow_math: Symbol
    pragma: Symbol
    pretty_atom: Symbol
    println: Symbol
    prog1: Symbol
    progn: Symbol
    py_at: Symbol
    py_atom: Symbol
    py_call: Symbol
    py_dict: Symbol
    py_dot: Symbol
    py_eq: Symbol
    py_format: Symbol
    py_in: Symbol
    py_iter: Symbol
    py_len: Symbol
    py_list: Symbol
    py_range: Symbol
    py_repr: Symbol
    py_round: Symbol
    py_slice: Symbol
    py_str: Symbol
    py_str_join: Symbol
    py_truthy: Symbol
    py_tuple: Symbol
    quote: Symbol
    random_float: Symbol
    random_int: Symbol
    read_form: Symbol
    readln: Symbol
    reduce: Symbol
    register_token: Symbol
    remove_atom: Symbol
    remove_translator_rule: Symbol
    remove_typing_rule: Symbol
    repr: Symbol
    repra: Symbol
    residual_goals: Symbol
    return_on_error: Symbol
    reverse: Symbol
    round_math: Symbol
    sealed: Symbol
    second_from_pair: Symbol
    sin_math: Symbol
    size_atom: Symbol
    sleep: Symbol
    sort: Symbol
    sort_atom: Symbol
    sort_strings: Symbol
    space_admission_verdict: Symbol
    space_atom_count: Symbol
    space_contains: Symbol
    sqrt_math: Symbol
    sread: Symbol
    sread_command: Symbol
    subtraction: Symbol
    subtraction_atom: Symbol
    super: Symbol
    superpose: Symbol
    switch: Symbol
    take: Symbol
    tan_math: Symbol
    test: Symbol
    test_no_answer: Symbol
    throw: Symbol
    timeout: Symbol
    top: Symbol
    trace: Symbol
    transaction: Symbol
    trunc_math: Symbol
    type_cast: Symbol
    type_cast_holds: Symbol
    undeclare_post_add: Symbol
    undeclare_pre_add: Symbol
    undocumented: Symbol
    undocumented_space: Symbol
    unify: Symbol
    union: Symbol
    union_atom: Symbol
    unique: Symbol
    unique_atom: Symbol
    unquote: Symbol
    unregister_token: Symbol
    with_pragma: Symbol
    with_seed: Symbol
    xor: Symbol
    def __getitem__(self, name: str, /) -> Symbol: ...

fn: Final[_FunctionNamespace]
