"""Purpose: the catalog's value vocabularies as Python constants and
Literal aliases, one per (vocabulary ...) row in &petta.

GENERATED by bindings/python/tools/vocabgen.py from the running engine's catalog
presets; edit the presets in engine/spaces.pl and rerun with --write, never
this file. The vocab-sync gate lane fails when the two drift.

Guarantees:
  - every tuple and Literal here exactly matches its catalog vocabulary row
    [tested: test_the_vocabulary_module_is_generated; commit=dcfc20be4933c19140ccb5759291401d13058301]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""  # noqa: D205  -- the API contract is one continuous invariant, not summary-and-body prose

from typing import Literal

__all__ = [
    "ANSWER_POLICY",
    "ATOMICITY",
    "CACHE_MODE",
    "CLAUSEFAILEDENUM",
    "DETERMINISM",
    "EFFECT_CLASS",
    "EVALUATIONORDERENUM",
    "FIDELITY",
    "FUNCTIONRESULTENUM",
    "MEMO_AGGREGATE",
    "MEMO_STRATEGY",
    "MISMATCHENUM",
    "NOMATCHENUM",
    "NUMERIC_TYPE",
    "ON_ERROR_MODE",
    "OP_KIND",
    "OUTOFCLAUSESENUM",
    "ROUTE_KEY",
    "SAVE_FORMAT",
    "SEMIRING",
    "SOURCE_KIND",
    "SPACE_CAPABILITY",
    "SUBSCRIPTION_EDGE",
    "VOLATILITY",
    "WORLD",
    "AnswerPolicy",
    "Atomicity",
    "CacheMode",
    "ClauseFailedEnum",
    "Determinism",
    "EffectClass",
    "EvaluationOrderEnum",
    "Fidelity",
    "FunctionResultEnum",
    "MemoAggregate",
    "MemoStrategy",
    "MismatchEnum",
    "NoMatchEnum",
    "NumericType",
    "OnErrorMode",
    "OpKind",
    "OutOfClausesEnum",
    "RouteKey",
    "SaveFormat",
    "Semiring",
    "SourceKind",
    "SpaceCapability",
    "SubscriptionEdge",
    "Volatility",
    "World",
]

#: (vocabulary ClauseFailedEnum ClauseFailNonDet ClauseFailDet)
CLAUSEFAILEDENUM = ("ClauseFailNonDet", "ClauseFailDet")
ClauseFailedEnum = Literal["ClauseFailNonDet", "ClauseFailDet"]

#: (vocabulary EvaluationOrderEnum OrderClause OrderFittest)
EVALUATIONORDERENUM = ("OrderClause", "OrderFittest")
EvaluationOrderEnum = Literal["OrderClause", "OrderFittest"]

#: (vocabulary FunctionResultEnum Nondeterministic Deterministic)
FUNCTIONRESULTENUM = ("Nondeterministic", "Deterministic")
FunctionResultEnum = Literal["Nondeterministic", "Deterministic"]

#: (vocabulary MismatchEnum MismatchOriginal MismatchError MismatchFail)
MISMATCHENUM = ("MismatchOriginal", "MismatchError", "MismatchFail")
MismatchEnum = Literal["MismatchOriginal", "MismatchError", "MismatchFail"]

#: (vocabulary NoMatchEnum NoMatchOriginal NoMatchFail NoMatchError)
NOMATCHENUM = ("NoMatchOriginal", "NoMatchFail", "NoMatchError")
NoMatchEnum = Literal["NoMatchOriginal", "NoMatchFail", "NoMatchError"]

#: (vocabulary OutOfClausesEnum FailureOriginal FailureEmpty FailureError)
OUTOFCLAUSESENUM = ("FailureOriginal", "FailureEmpty", "FailureError")
OutOfClausesEnum = Literal["FailureOriginal", "FailureEmpty", "FailureError"]

#: (vocabulary answer-policy depth fair best-first)
ANSWER_POLICY = ("depth", "fair", "best-first")
AnswerPolicy = Literal["depth", "fair", "best-first"]

#: (vocabulary atomicity transactional atomic-single best-effort)
ATOMICITY = ("transactional", "atomic-single", "best-effort")
Atomicity = Literal["transactional", "atomic-single", "best-effort"]

#: (vocabulary cache-mode unchecked)
CACHE_MODE = ("unchecked",)
CacheMode = Literal["unchecked"]

#: (vocabulary determinism det semidet nondet)
DETERMINISM = ("det", "semidet", "nondet")
Determinism = Literal["det", "semidet", "nondet"]

#: (vocabulary effect-class immutable)
EFFECT_CLASS = ("immutable",)
EffectClass = Literal["immutable"]

#: (vocabulary fidelity Exact Partial Sound Refuse)
FIDELITY = ("Exact", "Partial", "Sound", "Refuse")
Fidelity = Literal["Exact", "Partial", "Sound", "Refuse"]

#: (vocabulary memo-aggregate none min max sum count)
MEMO_AGGREGATE = ("none", "min", "max", "sum", "count")
MemoAggregate = Literal["none", "min", "max", "sum", "count"]

#: (vocabulary memo-strategy wtinylfu lru)
MEMO_STRATEGY = ("wtinylfu", "lru")
MemoStrategy = Literal["wtinylfu", "lru"]

#: (vocabulary numeric-type Number BigInt)
NUMERIC_TYPE = ("Number", "BigInt")
NumericType = Literal["Number", "BigInt"]

#: (vocabulary on-error-mode keep empty abort)
ON_ERROR_MODE = ("keep", "empty", "abort")
OnErrorMode = Literal["keep", "empty", "abort"]

#: (vocabulary op-kind det many raw_det raw_many)
OP_KIND = ("det", "many", "raw_det", "raw_many")
OpKind = Literal["det", "many", "raw_det", "raw_many"]

#: (vocabulary route-key context global)
ROUTE_KEY = ("context", "global")
RouteKey = Literal["context", "global"]

#: (vocabulary save-format metta fast)
SAVE_FORMAT = ("metta", "fast")
SaveFormat = Literal["metta", "fast"]

#: (vocabulary semiring bool bag set ranked prob prov)
SEMIRING = ("bool", "bag", "set", "ranked", "prob", "prov")
Semiring = Literal["bool", "bag", "set", "ranked", "prob", "prov"]

#: (vocabulary source-kind linear repeated peek)
SOURCE_KIND = ("linear", "repeated", "peek")
SourceKind = Literal["linear", "repeated", "peek"]

#: (vocabulary space-capability file process network)
SPACE_CAPABILITY = ("file", "process", "network")
SpaceCapability = Literal["file", "process", "network"]

#: (vocabulary subscription-edge add remove both)
SUBSCRIPTION_EDGE = ("add", "remove", "both")
SubscriptionEdge = Literal["add", "remove", "both"]

#: (vocabulary volatility volatile stable immutable)
VOLATILITY = ("volatile", "stable", "immutable")
Volatility = Literal["volatile", "stable", "immutable"]

#: (vocabulary world closed-world open-world)
WORLD = ("closed-world", "open-world")
World = Literal["closed-world", "open-world"]
