"""Purpose: make the callable ``metta.algebra`` contract executable in mypy.

GENERATED by extensions/python/tools/initstubgen.py from the catalog's
``semiring`` vocabulary.  Edit that authority and rerun with ``--write``; do
not add carrier names here by hand.

Guarantees:
  - direct and decorator calls retain their precise result types
  - every catalog carrier resolves through ``metta.algebra`` as
    ``DeclaredAlgebra``, and through the package root as well for each carrier
    the root names in a TYPE_CHECKING import
  - representative function, namespace, and satellite-module exports retain
    the types the source package exposed before the stub existed.  These few
    types are written out rather than derived, so a source type that gains a
    parameter turns this lane red; the remedy is ``probe_text`` in the
    generator, never an edit here
  - an ``Any`` result makes the guarded assignment's ignore unused and fails
    under the repository's ``warn_unused_ignores`` policy
    [tested: mypy-algebra-surface; commit=WORKTREE]
"""

from collections.abc import Callable
from types import ModuleType
from typing import assert_type

import metta
from metta._atom_namespace import _Namespace
from metta._fn import _FunctionNamespace
from metta.algebra import DeclaredAlgebra
from metta.atoms import Atom, Symbol

assert_type(metta.S, _Namespace[Symbol])
assert_type(metta.fn, _FunctionNamespace)
assert_type(metta.convert, ModuleType)
assert_type(metta.forms("(x)"), list[Atom])
assert_type(metta.run("!(x)"), list[list[Atom]])
assert_type(metta.algebra(int), DeclaredAlgebra)
assert_type(metta.algebra(), Callable[[type], DeclaredAlgebra])
assert_type(metta.algebra.bool, DeclaredAlgebra)
assert_type(metta.algebra.bag, DeclaredAlgebra)
assert_type(metta.bag, DeclaredAlgebra)
assert_type(metta.algebra.counting, DeclaredAlgebra)
assert_type(metta.counting, DeclaredAlgebra)
assert_type(metta.algebra.set, DeclaredAlgebra)
assert_type(metta.algebra.ranked, DeclaredAlgebra)
assert_type(metta.ranked, DeclaredAlgebra)
assert_type(metta.algebra.tropical, DeclaredAlgebra)
assert_type(metta.tropical, DeclaredAlgebra)
assert_type(metta.algebra.prob, DeclaredAlgebra)
assert_type(metta.prob, DeclaredAlgebra)
assert_type(metta.algebra.prov, DeclaredAlgebra)
assert_type(metta.prov, DeclaredAlgebra)
assert_type(metta.algebra.budget, DeclaredAlgebra)
assert_type(metta.budget, DeclaredAlgebra)
assert_type(metta.algebra.amplitude, DeclaredAlgebra)
assert_type(metta.amplitude, DeclaredAlgebra)

_not_an_integer: int = metta.algebra(int)  # type: ignore[assignment]
