"""Purpose: type-check root exports and callable algebra carriers.

GENERATED by extensions/python/tools/rootgen.py --write from
extensions/python/metta/__init__.pyi, extensions/python/metta/vocabularies.py,
extensions/python/metta/_faces/*.py: the init-stub artifact in
extensions/python/tools/artifacts.py, whose init-stub lane refuses drift.
Check with `sh check.sh init-stub mypy`.
"""

from collections.abc import Callable
from types import ModuleType
from typing import assert_type

import metta
from metta._atoms.factories import Atom, Symbol
from metta._atoms.namespace import _Namespace
from metta.algebra import DeclaredAlgebra

assert_type(metta.S, _Namespace[Symbol])
assert_type(metta.fn.car_atom, Symbol)
assert_type(metta.convert, ModuleType)
assert_type(metta.forms("(x)"), list[Atom])
assert_type(metta.run("!(x)"), list[list[Atom]])
assert_type(metta.algebra(int), DeclaredAlgebra)
assert_type(metta.algebra(), Callable[[type], DeclaredAlgebra])
assert_type(
    metta.algebra(
        "typed-int-product", plus=max, times=lambda a, b: a * b,
        zero=0, one=1, type=int,
    ),
    DeclaredAlgebra,
)
assert_type(metta.algebra(type=int), Callable[[type], DeclaredAlgebra])
assert_type(metta.algebra.bool, DeclaredAlgebra)
assert_type(metta.bool, DeclaredAlgebra)
assert_type(metta.algebra.visibility, DeclaredAlgebra)
assert_type(metta.visibility, DeclaredAlgebra)
assert_type(metta.algebra.bag, DeclaredAlgebra)
assert_type(metta.bag, DeclaredAlgebra)
assert_type(metta.algebra.counting, DeclaredAlgebra)
assert_type(metta.counting, DeclaredAlgebra)
assert_type(metta.algebra.set, DeclaredAlgebra)
assert_type(metta.set, DeclaredAlgebra)
assert_type(metta.algebra.ranked, DeclaredAlgebra)
assert_type(metta.ranked, DeclaredAlgebra)
assert_type(metta.algebra.tropical, DeclaredAlgebra)
assert_type(metta.tropical, DeclaredAlgebra)
assert_type(metta.algebra.prob, DeclaredAlgebra)
assert_type(metta.prob, DeclaredAlgebra)
assert_type(metta.algebra.prov, DeclaredAlgebra)
assert_type(metta.prov, DeclaredAlgebra)
assert_type(metta.algebra.budget, DeclaredAlgebra)
assert_type(metta.budget, DeclaredAlgebra)
assert_type(metta.algebra.amplitude, DeclaredAlgebra)
assert_type(metta.amplitude, DeclaredAlgebra)

_not_an_integer: int = metta.algebra(int)  # type: ignore[assignment]
