"""Purpose: expose engine callbacks lazily under the ``metta_ops`` alias.

Guarantees:
  - exact-token mutation callbacks delegate to metta.foreign [tested:
    test_token_mutation_receives_and_withdraws_a_reference; commit=90ba93eb8f6e98ebfefc55416859bf13de6a8427].
  - the facade owns no registry state; each callback is the owning module's
    exact object behind one frame that marks the engine's entry, and
    `__wrapped__` names that object [tested:
    test_callback_facade_owns_no_state_and_delegates; commit=f80cc416ddcadaf710caafd08f3f1f9ae7791e36]
  - `entered()` answers True exactly while a callback frame is open on the
    running thread, which is how a scope lookup knows the engine may hold a
    scope the host does not, and an ordinary door access makes no engine
    call to find out [tested: test_the_engine_scope_is_read_inside_a_callback,
    test_a_space_accessor_costs_no_engine_call_outside_a_callback;
    commit=f80cc416ddcadaf710caafd08f3f1f9ae7791e36]
  - importing the callback facade does not import event, provider, or path
    satellites [tested: test_m7_satellites_are_lazy_and_identity_stable;
    commit=f88aa8be03cb64cb59d3307515ded8701f418321]
  - scheduler context and async-operation callbacks resolve lazily to their
    owning satellites [tested:
    test_context_snapshot_crosses_every_spawn_door_including_thread_workers,
    test_an_async_operation_answers_a_future_space; commit=39092863ae34184a9f955f185ff57c1ff177ec40]
  - the engine-message callback resolves lazily to the runtime module that
    owns the metta.engine logger [tested:
    test_an_engine_warning_becomes_a_warning_record; commit=6375a7c8f3c035b04bc9d41c8f7f22e56b42fb41]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import functools as _functools
import importlib as _importlib
import sys as _sys
import threading as _threading
from collections.abc import Callable as _Callable
from typing import Any as _Any

# begin generated binding callbacks
# Generated by tools/bindinggen.py from interface.CALLBACK_GROUPS.
# closed-set: generated; by=extensions/python/tools/bindinggen.py; lane=binding
_CALLBACKS = {
    'async_cancel': ('metta.aio._ops', 'cancel'),
    'async_discard': ('metta.aio._ops', 'discard'),
    'async_prepare': ('metta.aio._ops', 'prepare'),
    'async_start': ('metta.aio._ops', 'start'),
    'atom_added': ('metta.events', 'atom_added'),
    'atom_removed': ('metta.events', 'atom_removed'),
    'capture_context': ('metta._binding.task_context', 'snapshot'),
    'capture_contexts': ('metta._binding.task_context', 'snapshot_many'),
    'construct_token': ('metta._binding.tokens', 'construct_token'),
    'dispatch': ('metta._binding.dispatch', 'dispatch'),
    'drop_completed': ('metta._spaces.handle', 'drop_completed'),
    'engine_message': ('metta._binding.runtime', 'engine_message'),
    'foreign_add': ('metta.foreign', 'foreign_add'),
    'foreign_add_many': ('metta.foreign', 'foreign_add_many'),
    'foreign_add_token': ('metta.foreign', 'foreign_add_token'),
    'foreign_atoms': ('metta.foreign', 'foreign_atoms'),
    'foreign_clear': ('metta.foreign', 'foreign_clear'),
    'foreign_match': ('metta.foreign', 'foreign_match'),
    'foreign_participant': ('metta.foreign', 'foreign_participant'),
    'foreign_plan': ('metta.foreign', 'foreign_plan'),
    'foreign_pushdown': ('metta.foreign', 'foreign_pushdown'),
    'foreign_refuse': ('metta.foreign', 'foreign_refuse'),
    'foreign_remove': ('metta.foreign', 'foreign_remove'),
    'foreign_remove_token': ('metta.foreign', 'foreign_remove_token'),
    'foreign_tokens': ('metta.foreign', 'foreign_tokens'),
    'fork_context': ('metta._binding.task_context', 'fork'),
    'fork_contexts': ('metta._binding.task_context', 'fork_many'),
    'heartbeat_tick': ('metta._binding.runtime', 'heartbeat_tick'),
    'is_matchable': ('metta.foreign', 'is_matchable'),
    'lease_aborted': ('metta._spaces.lease', 'aborted'),
    'match_object': ('metta.foreign', 'match_object'),
    'path_begin': ('metta.paths', '_path_begin'),
    'path_step': ('metta.paths', '_path_step'),
    'path_value': ('metta.paths', '_path_value'),
    'release_context': ('metta._binding.task_context', 'release'),
    'release_contexts': ('metta._binding.task_context', 'release_many'),
    'segment_committed': ('metta.events', 'segment_committed'),
    'space_released': ('metta._spaces.lease', 'released'),
    'stream_reraise': ('metta._errors.errors', 'stream_reraise'),
    'transaction_body': ('metta._spaces.scope', 'transaction_body'),
    'type_names': ('metta._binding.dispatch', 'type_names'),
}

async_cancel: _Any
async_discard: _Any
async_prepare: _Any
async_start: _Any
atom_added: _Any
atom_removed: _Any
capture_context: _Any
capture_contexts: _Any
construct_token: _Any
dispatch: _Any
drop_completed: _Any
engine_message: _Any
foreign_add: _Any
foreign_add_many: _Any
foreign_add_token: _Any
foreign_atoms: _Any
foreign_clear: _Any
foreign_match: _Any
foreign_participant: _Any
foreign_plan: _Any
foreign_pushdown: _Any
foreign_refuse: _Any
foreign_remove: _Any
foreign_remove_token: _Any
foreign_tokens: _Any
fork_context: _Any
fork_contexts: _Any
heartbeat_tick: _Any
is_matchable: _Any
lease_aborted: _Any
match_object: _Any
path_begin: _Any
path_step: _Any
path_value: _Any
release_context: _Any
release_contexts: _Any
segment_committed: _Any
space_released: _Any
stream_reraise: _Any
transaction_body: _Any
type_names: _Any

__all__ = [
    'async_cancel',
    'async_discard',
    'async_prepare',
    'async_start',
    'atom_added',
    'atom_removed',
    'capture_context',
    'capture_contexts',
    'construct_token',
    'dispatch',
    'drop_completed',
    'engine_message',
    'foreign_add',
    'foreign_add_many',
    'foreign_add_token',
    'foreign_atoms',
    'foreign_clear',
    'foreign_match',
    'foreign_participant',
    'foreign_plan',
    'foreign_pushdown',
    'foreign_refuse',
    'foreign_remove',
    'foreign_remove_token',
    'foreign_tokens',
    'fork_context',
    'fork_contexts',
    'heartbeat_tick',
    'is_matchable',
    'lease_aborted',
    'match_object',
    'path_begin',
    'path_step',
    'path_value',
    'release_context',
    'release_contexts',
    'segment_committed',
    'space_released',
    'stream_reraise',
    'transaction_body',
    'type_names',
]
# end generated binding callbacks


# The one boundary the engine crosses into Python. A frame is counted per
# thread while a callback runs, so code that may run on the engine's behalf
# (an operation's body, a provider, a subscription handler) can ask whether it
# does, and the scope it runs under is the engine's own then rather than the
# host's ambient one.
_ENTERED = _threading.local()


def entered() -> bool:
    """Whether the running thread is inside a callback the engine made."""
    return getattr(_ENTERED, "depth", 0) > 0


def _entry(target: _Callable[..., _Any]) -> _Callable[..., _Any]:
    @_functools.wraps(target)
    def callback(*args: _Any, **kwargs: _Any) -> _Any:
        _ENTERED.depth = getattr(_ENTERED, "depth", 0) + 1
        try:
            return target(*args, **kwargs)
        finally:
            _ENTERED.depth -= 1

    return callback


def __getattr__(name: str) -> _Any:
    """Resolve a callback only when Janus first requests it."""
    try:
        module_name, attribute = _CALLBACKS[name]
    except KeyError:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg, name=name, obj=_sys.modules[__name__]) from None
    module = _importlib.import_module(module_name)
    value = _entry(getattr(module, attribute))
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return the exact callback protocol without resolving callbacks."""
    return list(__all__)
