"""Generated by tools/doorgen.py from Door.Binding.evaluation."""

from typing import Any, NamedTuple


class EvaluationRecord(NamedTuple):
    """The fixed Janus record; its field order comes from EvaluationOptions."""

    form: str
    using: list[Any]
    answers: str
    fuel: str
    inferences: int | str
    seconds: float | str
    under: list[Any] | str
    policy: list[Any] | str
    repeatable: str
    columns: list[Any]
    accounting: str
    batch: str
    unmatched: str

    def with_options(self, **options: Any) -> "EvaluationRecord":
        """Project Python flags and unbounded quotas to native Prolog atoms."""
        native: dict[str, Any] = {
            name: ("none" if value is None else
                   "true" if value is True else "false" if value is False else
                   "none" if name in ('inferences', 'seconds') and isinstance(value, (int, float)) and value < 0 else value)
            for name, value in options.items()
        }
        return self._replace(**native)


# closed-set: generated; by=extensions/python/tools/doorgen.py; lane=door-sync
EVALUATIONS = {
    'space:eval': ('metta_py_evaluate', EvaluationRecord(form='wire', using=[], answers='all', fuel='true', inferences='none', seconds='none', under='none', policy='none', repeatable='false', columns=[], accounting='false', batch='false', unmatched='true'), 0),
    'space:answers': ('metta_py_evaluate', EvaluationRecord(form='wire', using=[], answers='cursor', fuel='true', inferences='none', seconds='none', under='none', policy='none', repeatable='false', columns=[], accounting='false', batch='false', unmatched='true'), 1),
    'space:eval-status': ('metta_py_evaluate', EvaluationRecord(form='wire', using=[], answers='status', fuel='true', inferences='none', seconds='none', under='none', policy='none', repeatable='false', columns=[], accounting='false', batch='false', unmatched='true'), 2),
}
