% Generated by tools/bindinggen.py from the binding interface.
:- multifile seam:extension_builtin/2.

:- multifile seam:grounded_algebra_equal/3.

:- multifile seam:grounded_applicable/1.

:- multifile seam:grounded_apply/3.

:- multifile seam:grounded_class_type/2.

:- multifile seam:grounded_extra_type/2.

:- multifile seam:grounded_length/2.

:- multifile seam:grounded_numeric/1.

:- multifile seam:grounded_numeric_operation/3.

:- multifile seam:grounded_structure/2.

:- multifile seam:grounded_text/2.

:- multifile seam:host_error_reason/2.

:- multifile seam:host_import/1.

:- multifile seam:host_object/1.

:- multifile seam:host_transport_failure/1.

seam:grounded_extra_type(Obj, Type) :-
    python_object_blob(Obj),
    py_is_object(Obj),
    metta_py_bridge,
    py_call('metta._binding.host':declared_type_texts(Obj), Texts, [py_string_as(string)]),
    member(Text, Texts),
    term_string(Type, Text).

seam:extension_builtin('py-call',  oracleIO).

seam:extension_builtin('py-atom',  oracleIO).

seam:extension_builtin('py-dot',   oracleIO).

seam:extension_builtin('py-list',  oracleIO).

seam:extension_builtin('py-tuple', oracleIO).

seam:extension_builtin('py-dict',  oracleIO).

seam:extension_builtin('py-iter',  oracleIO).

seam:extension_builtin('py-iter-once', oracleIO).

seam:grounded_length(Tuple, Length) :-
    compound(Tuple),
    compound_name_arity(Tuple, -, Length).

seam:grounded_length(Obj, Length) :-
    python_object_blob(Obj),
    py_is_object(Obj),
    metta_py_bridge,
    py_call('metta._binding.host':sized_length(Obj), Length),
    Length >= 0.

seam:grounded_structure(Tuple, Elements) :-
    metta_py_tuple_arguments(Tuple, Raw),
    maplist(metta_py_result, Raw, Elements).

seam:grounded_structure(Obj, Elements) :-
    python_object_blob(Obj),
    py_is_object(Obj),
    metta_py_bridge,
    py_call('metta._binding.host':sequence_length(Obj), Length),
    Length >= 0,
    (   is_list(Elements)
    ->  length(Elements, Length)
    ;   true
    ),
    findall(E, 'py-iter'(Obj, E), Elements).

seam:grounded_text(Tuple, Text) :-
    metta_py_tuple_arguments(Tuple, Raw),
    !,
    maplist(metta_py_result, Raw, Elements),
    sdisplay(Elements, Text).

seam:grounded_text(Obj, Text) :-
    python_object_blob(Obj),
    py_is_object(Obj),
    metta_py_bridge,
    py_call('metta._binding.host':render(Obj), Text).

seam:grounded_class_type(X, T) :-
    metta_py_bridge,
    py_call('metta._binding.host':class_names(X), Names, [py_string_as(string)]),
    member(Name, Names),
    ( atom(Name) -> T = Name ; atom_string(T, Name) ).

seam:grounded_algebra_equal(Left, Right, Equal) :-
    ( python_object_blob(Left) -> true ; python_object_blob(Right) ),
    metta_py_bridge,
    py_call('metta._binding.host':algebra_equal(Left, Right), Truth),
    ( Truth == @true -> Equal = true ; Equal = false ).

seam:grounded_numeric(X) :-
    python_object_blob(X),
    metta_py_bridge,
    py_call('metta._binding.host':is_numeric(X), @true).

seam:grounded_numeric_operation(Operation, Arguments, Result) :-
    member(Operand, Arguments),
    python_object_blob(Operand), !,
    metta_py_call([Operation|Arguments],
             numeric_operation(Operation, Arguments), Result).

seam:grounded_apply(Obj, Args, Result) :-
    python_object_blob(Obj),
    py_is_object(Obj),
    metta_py_bridge,
    py_call('metta._binding.host':is_callable(Obj), @true),
    metta_py_split_kwargs(Args, Positional0, Kwargs),
    maplist(py_frame_arg_norm, Positional0, Positional),
    metta_py_opts(Opts),
    metta_py_guard([Obj|Args],
                   py_call('metta._binding.host':apply(Obj, Positional, Kwargs), Raw, Opts)),
    metta_py_result(Raw, Result).

seam:grounded_applicable(Obj) :-
    python_object_blob(Obj),
    py_is_object(Obj),
    metta_py_bridge,
    py_call('metta._binding.host':is_callable(Obj), @true).

seam:host_import(File) :-
    python_import_file(File),
    resolve_python_import_path(File, CanonPath),
    import_when(not_loaded, '$python', CanonPath,
                load_python_source(CanonPath)).

seam:host_object(X) :- python_object_blob(X), py_is_object(X).

seam:host_transport_failure(error(python_error('TransportFailure', _), _)).

seam:host_error_reason(error(python_error(Class, Message0), _), Reason) :-
    (   string(Message0) -> Message = Message0
    ;   metta_py_exception_message(Message0, Message)
    ),
    format(string(Reason), "~w: ~w", [Class, Message]).
