% Generated by tools/bindinggen.py from the binding interface.
:- multifile seam:catalog_row_changed/2.

seam:catalog_row_changed(_Event, [limit, Name|_]) :-
    ( current_transaction(_) -> metta_py_bound_transaction ; true ),
    py_call('metta._catalog.bounds':bound_row_changed(Name), _).
