% Generated by tools/bindinggen.py from the binding interface.
:- module(metta_python_services, [binding_forward_expansion/2]).
:- use_module(library(error), [domain_error/2]).

binding_forward_expansion(Indicator, Clause) :-
    ( binding_forward_clause(Indicator, Clause) -> true
    ; domain_error(binding_forward, Indicator) ).

:- multifile system:term_expansion/2.
system:term_expansion(binding_forward(Indicator), Clause) :-
    prolog_load_context(module, Module),
    Module \== metta_python_services,
    predicate_property(Module:binding_forward_expansion(_, _), imported_from(metta_python_services)),
    binding_forward_expansion(Indicator, Clause).

binding_forward_clause(metta_control_signal_line/2, (metta_control_signal_line(A0, A1) :- metta_host_control_signal_line(A0, A1))).
binding_forward_clause(metta_py_clear/1, (metta_py_clear(A0) :- metta_host_clear_space(A0))).
binding_forward_clause(metta_py_cursor_chunk/3, (metta_py_cursor_chunk(A0, A1, A2) :- metta_host_hold_chunk(A0, A1, A2))).
binding_forward_clause(metta_py_cursor_close/1, (metta_py_cursor_close(A0) :- metta_host_hold_close(A0))).
binding_forward_clause(metta_py_fast_load/2, (metta_py_fast_load(A0, A1) :- metta_host_load_fast(A0, A1))).
binding_forward_clause(metta_py_function_generation/1, (metta_py_function_generation(A0) :- metta_host_function_generation(A0))).
binding_forward_clause(metta_py_in_module/2, (metta_py_in_module(A0, A1) :- with_metta_module(A0, A1))).
binding_forward_clause(metta_py_module/2, (metta_py_module(A0, A1) :- space_module(A0, A1))).
binding_forward_clause(metta_py_space_capability_error/4, (metta_py_space_capability_error(A0, A1, A2, A3) :- metta_host_space_capability_error(A0, A1, A2, A3))).
binding_forward_clause(metta_py_unregister_token/1, (metta_py_unregister_token(A0) :- metta_host_unregister_reader_token(A0))).
