% Generated by tools/bindinggen.py from the binding interface.
:- module(metta_python_source_macros, [binding_source_expansion/2]).
:- use_module(library(error), [domain_error/2]).

binding_source_expansion(metta_py_wide_projection(Names), Names = [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _|_]).

binding_source_expansion(metta_py_provided_clause(Name, Clause), Clause = Template) :-
    ( atom(Name), provided_template(Name, Template) -> true
    ; domain_error(binding_provided_clause, Name) ).

:- multifile system:goal_expansion/2.

system:goal_expansion(metta_py_wide_projection(Names), Expanded) :-
    prolog_load_context(module, Module),
    Module \== metta_python_source_macros,
    predicate_property(Module:binding_source_expansion(_, _), imported_from(metta_python_source_macros)),
    binding_source_expansion(metta_py_wide_projection(Names), Expanded).

system:goal_expansion(metta_py_provided_clause(Name, Clause), Expanded) :-
    prolog_load_context(module, Module),
    Module \== metta_python_source_macros,
    predicate_property(Module:binding_source_expansion(_, _), imported_from(metta_python_source_macros)),
    binding_source_expansion(metta_py_provided_clause(Name, Clause), Expanded).

provided_template(atom_added, (seam:atom_added(Space, Term) :- metta_py_notify_atom_added(Space, Term))).

provided_template(atom_removed, (seam:atom_removed(Space, Term) :- metta_py_notify_atom_removed(Space, Term))).

provided_template(segment_committed, (seam:segment_committed(Spaces) :- metta_py_notify_segment_committed(Spaces))).
