"""Purpose: expose the generated static function-mention namespace.

GENERATED by extensions/python/tools/fngen.py from a fresh running engine's
function and special-form catalog. Edit the catalog and rerun with --write,
never edit this file directly.

The generator holds the contract and its evidence. Check with
`python extensions/python/tools/fngen.py`.
"""

from typing import TYPE_CHECKING, cast

from metta._atoms.factories import Symbol
from metta._atoms.namespace import _Namespace
from metta._errors.errors import Remedy

if TYPE_CHECKING:
    from collections.abc import Callable
    from typing import Protocol

    from metta._atoms.factories import Expression

    class _FunctionNamespace(Protocol):
        """The public aliases of the frozen function catalog."""

        Predicate: Symbol
        abs_math: Symbol
        "abs-math: (-> Number Number)\n\nPython's builtin `abs`."
        acos_math: Symbol
        "acos-math: (-> Number Number)\n\n`math.acos`."
        add: Symbol
        "+: (-> Number Number Number)\n\nPython's own operator. On atoms the same operator builds `(+ ...)` instead of computing, which is how a compiled body reaches the MeTTa function."
        add_atom: Symbol
        "add-atom: (-> SpaceType Atom (->))\n\n`space += atom`, the container protocol. A plain Python tuple encodes to an expression on the way in, so a fact needs no builder ceremony. This spelling takes upstream PeTTa's domain, an atom with a HEAD, and has no answer for a bare symbol, a grounded value or the empty expression; `add-atoms` is the door onto the wider space and `space += atom` uses it."
        add_atoms: Symbol
        "add-atoms: (-> SpaceType Expression (->))\n\nThe same `+=` form, once per fact: anything that yields tuples is a fact stream. Lists, outer tuples of rows, generators, SQL cursors, and dataframe row iterators each write one atom per yielded item; a built Expression is always one atom."
        add_reduct: Symbol
        "add-reduct: (-> SpaceType %Undefined% (->))\n\nThere is no second form: `+=` adds what you give it, so adding a REDUCT is explicit composition, `space += m.eval(term)[0]`. Bare grounded answers use `+=` directly; this row wraps the evaluated sum only to retain its `total` relation head."
        add_reducts: Symbol
        "add-reducts: (-> SpaceType %Undefined% (->))\n\nThe plural of the same composition: evaluate, then write the answers."
        add_translator_rule: Symbol
        add_typing_rule: Symbol
        alpha_unique: Symbol
        alpha_unique_atom: Symbol
        and_: Symbol
        "and: (-> Bool Bool Bool)\n\nPython's own keyword. On atoms `&` builds the MeTTa `and` instead, because the keyword cannot be overloaded."
        and_then: Symbol
        annotation: Symbol
        append: Symbol
        argv: Symbol
        asin_math: Symbol
        "asin-math: (-> Number Number)\n\n`math.asin`."
        assertAlphaEqual: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertAlphaEqual: (-> Atom Atom (->))\n\n`assert a.alpha_eq(b)`: the assertion is Python's, the relation is MeTTa's."
        assertAlphaEqualMsg: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertAlphaEqualMsg: (-> Atom Atom Atom (->))\n\nThe same with Python's assertion message."
        assertAlphaEqualToResult: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertAlphaEqualToResult: (-> Atom Atom (->))\n\nThe answer-list form compared modulo renaming."
        assertAlphaEqualToResultMsg: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertAlphaEqualToResultMsg: (-> Atom Atom Atom (->))\n\nThe same with Python's assertion message."
        assertEqual: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertEqual: (-> Atom Atom (->))\n\n`assert a == b`, and pytest's own assertion rewriting prints the halves."
        assertEqualMsg: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertEqualMsg: (-> Atom Atom Atom (->))\n\n`assert a == b, message`, which is Python's own second argument."
        assertEqualToResult: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertEqualToResult: (-> Atom Atom (->))\n\nThe right-hand side is a LIST of expected answers rather than one, which is `assert list(answers) == [...]`."
        assertEqualToResultMsg: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertEqualToResultMsg: (-> Atom Atom Atom (->))\n\nThe same with Python's assertion message."
        assertIncludes: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        "assertIncludes: (-> Atom Expression (->))\n\nPython's own `in`."
        assert_: Symbol
        "assert: (-> Atom (->))\n\nPython's own `assert`. A twin or a test states its claims this way and the run proves them, because a false assertion raises."
        assert_answers: Symbol
        assert_includes_answers: Symbol
        assertaPredicate: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        assertzPredicate: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        atan_math: Symbol
        "atan-math: (-> Number Number)\n\n`math.atan`."
        atom_subst: Symbol
        "atom-subst: (-> Atom (:Atom Variable) Atom Atom)\n\nApplying a substitution to a template, which `Atom.map` does over the whole term. Section 9e wants the bindings object to carry it, `b.apply(template)`; `metta.Bindings` has no such method yet, so the walker is the spelling."
        atomically: Symbol
        bind: Symbol
        "bind!: (-> Symbol %Undefined% (->))\n\nA Python name binding. `space = metta.space(...)` is exactly what a token binding was for, and Python's own scoping rules then apply."
        bit_and: Symbol
        bit_not: Symbol
        bit_or: Symbol
        bit_shift_left: Symbol
        bit_shift_right: Symbol
        bit_xor: Symbol
        call: Symbol
        callPredicate: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        car_atom: Symbol
        "car-atom: (-> Expression %Undefined%)\n\nIndexing. An expression is a sequence in Python, so its head is `e[0]`."
        case: Symbol
        "case: (-> Atom Expression %Undefined%)\n\nPython's `match` statement. A bare variable arm is `case _`."
        catch: Symbol
        cdr_atom: Symbol
        "cdr-atom: (-> Expression Expression)\n\nSlicing. `e[1:]` answers a Python tuple today rather than an Expression, which prints the same and is the T6 friction section 9e names as this bucket's one prerequisite."
        ceil_math: Symbol
        "ceil-math: (-> Number Number)\n\n`math.ceil`, which answers an integer in Python 3 where a float-preserving float."
        chain: Symbol
        "chain: (-> Atom Variable Atom %Undefined%)\n\nPython assignment, and `let`'s own instruction under a second name: it runs the operand, binds the VALUE it produced once, and continues into the template, which is exactly `x = m.eval(t)[0]` followed by use of `x`."
        change_state: Symbol
        "change-state!: (-> (StateMonad $tcso) $tcso Bool)\n\nAssigning `state.value` writes the same typed engine cell and reading it back returns the replacement. The WRITE answers True rather than the cell, which is upstream's own answer -- `'change-state!'(Var, Value, true)` [source: PeTTa@ae66fa8 src/metta.pl:265] -- so the read is a separate step here as it is in Python."
        collapse: Symbol
        "collapse: (-> Atom Atom)\n\n`list()` is the everyday spelling, materialising the answers; `tuple()` is the same act when you want MeTTa's own `( )` atom back, which is what collapse answers."
        collapse_bind: Symbol
        "collapse-bind: (-> Atom Expression)\ncollapse-bind: (TU Expression)\n\nThe deep-tier collapse that keeps each alternative's BINDINGS, `((a (bindings ...)) ...)`. It belongs to the bindings-carrying tier, never to the surface; MeTTa's engine has the bindings carrier (`answer_bindings`) but not this instruction."
        cons: Symbol
        cons_atom: Symbol
        "cons-atom: (-> Atom Expression Atom)\n\nConstruction: call the head, or rebuild from head and tail with `*`."
        context_space: Symbol
        "context-space: (-> SpaceType)\n\nThe space a program is currently in, which in Python is the handle it holds; `metta.current_space()` is the function for code that did not receive one, and it follows Python's own `current_thread` and `current_task` convention, so the Python word wins over the instruction's name. The row asks both sides for the current space's atoms."
        cos_math: Symbol
        "cos-math: (-> Number Number)\n\n`math.cos`."
        current_time: Symbol
        cut: Symbol
        declare_post_add: Symbol
        declare_pre_add: Symbol
        decons: Symbol
        decons_atom: Symbol
        "decons-atom: (-> Expression Atom)\n\nStarred unpacking, which is the same act in one line: `head, *tail = e`."
        defined_name: Symbol
        dif: Symbol
        documented: Symbol
        documented_space: Symbol
        elapsed: Symbol
        empty: Symbol
        eq: Symbol
        "==: (-> $t $t Bool)\n\nPython's own operator, and atoms compare structurally under it."
        error_payload: Symbol
        eval: Symbol
        "eval: (-> Atom Atom)\n\nONE step. `m.eval(term)` is the same one step and answers every result, and `space.eval(term)` is `evalc`, the same step in a named space."
        eval_one: Symbol
        "eval-one: (-> Atom Atom)\n\nEvaluate held source, count at most two answers and return the sole answer as data. Failed alternatives do not count. Zero or multiple answers raise a cardinality error before the caller can filter them."
        evalc: Symbol
        "evalc: (-> Atom SpaceType Atom)\n\nOne step WITH an explicit context space, which is `space.eval(term)`: the signature IS term plus space."
        except_: Symbol
        exclude_item: Symbol
        exp: Symbol
        exp_math: Symbol
        explain: Symbol
        filter_atom: Symbol
        "filter-atom: (-> Expression Variable Atom Expression)\nfilter-atom: (-> Expression Expression Expression)\n\nA comprehension with an `if`, or `filter`."
        first: Symbol
        first_from_pair: Symbol
        floor_div: Symbol
        floor_math: Symbol
        "floor-math: (-> Number Number)\n\n`math.floor`, the same integer-against-float difference as `ceil-math`."
        foldall: Symbol
        foldl: Symbol
        foldl_atom: Symbol
        "foldl-atom: (-> Expression Atom Variable Variable Atom %Undefined%)\nfoldl-atom: (-> Expression Atom Expression %Undefined%)\n\n`functools.reduce` with an initial value is the same finite left fold. For a change stream, `m.events().fold(..., under=algebra)` makes the algebra itself the step; `into=State(...)` is the running-gauge form."
        for_each_in_atom: Symbol
        "for-each-in-atom: (-> Expression Atom (->))\n\nA `for` statement. It is called for its effect, so the row prints and answers the unit. Python's `for` has no value at all, and the concept map says `None` IS the unit, but `metta.ground(None)` renders `<NoneType>` rather than `()` today, so a row that wants the unit writes it [measured 2026-08-22]."
        forall: Symbol
        format_args: Symbol
        "format-args: (-> String Expression String)\n\nAn f-string. MeTTa's `{}` holes are Python's own interpolation."
        format_time: Symbol
        function: Symbol
        "function: (-> Atom Atom)\n\nThe core's function frame, which `return` closes. MeTTa's compiled definitions do not go through this instruction and it is not implemented."
        ge: Symbol
        ">=: (-> Number Number Bool)\n\nPython's own operator."
        get_atoms: Symbol
        "get-atoms: (-> SpaceType Atom)\n\n`space.atoms()`, or `for atom in space` when you want to walk them."
        get_doc: Symbol
        "get-doc: (-> SpaceType Atom %Undefined%)\n\nPython's builtin `help`, over the docstring a decorated function already carries. This engine answers nothing here because no documentation atoms are written yet, which is the doc-vocabulary gap."
        get_doc_space: Symbol
        get_metatype: Symbol
        "get-metatype: (-> Atom Atom)\n\nPython's own builtin `type`: the four atom classes ARE the four metatypes, so `type(a).__name__` is the metatype by construction."
        get_property: Symbol
        get_state: Symbol
        "get-state: (-> (StateMonad $tgso) $tgso)\n\nReading the cell is the typed handle's `state.value` property."
        get_type: Symbol
        "get-type: (-> Atom %Undefined%)\n\nDeclared types are space-relative, so `space.type(atom)` asks the space. Class declarations use the consolidated `@space.define` decorator."
        get_type_space: Symbol
        "get-type-space: (-> SpaceType Atom Atom)\n\nThe same question asked of a named space through that handle's `space.type(atom)` method."
        git_import: Symbol
        "git-import!: (-> String String Atom)\n\npip and `importlib`. Fetching a dependency is packaging's job, the module catalog IS Python packaging, and a boot manifest names the distribution."
        gt: Symbol
        ">: (-> Number Number Bool)\n\nPython's own operator."
        has_declared_type: Symbol
        help: Symbol
        "help!: (-> Atom (->))\nhelp!: (-> (->))\n\nPython's builtin `help`, which is the same act on the same docstring."
        hyperpose: Symbol
        id: Symbol
        "id: (-> $t $t)\n\nThe identity function, which Python writes as the value itself."
        if_: Symbol
        "if: (-> Bool Atom Atom $t)\n\nPython's own `if`, and its conditional expression where a value is wanted. Both arms stay unevaluated in MeTTa because the parameters are Atom-typed, which is exactly what Python's own short-circuit does."
        if_decons_expr: Symbol
        "if-decons-expr: (-> (:Atom Expression) (:Atom Variable) (:Atom Variable) Atom Atom %Undefined%)\n\nStarred unpacking inside an `if`: the empty case is the `else` branch."
        if_equal: Symbol
        "if-equal: (-> Atom Atom Atom Atom %Undefined%)\n\nA conditional expression over `==`."
        if_equal2: Symbol
        if_error: Symbol
        "if-error: (-> Atom Atom Atom %Undefined%)\n\n`try`/`except`, or a conditional over the value. It is the railway combinator over Error atoms."
        implies: Symbol
        import_: Symbol
        "import!: (-> Atom Atom (->))\n\nPython's own `import`, and for a MeTTa library the boot manifest or `m.load(path)`. The module catalog IS Python packaging."
        include: Symbol
        "include: (-> Atom %Undefined%)\n\n`space.load(path)` reads a file into that space, which is what include does; Python's own `import` is the spelling for a Python module."
        index_atom: Symbol
        "index-atom: (-> Expression Number Atom)\n\nIndexing again, with the index you want."
        inferences: Symbol
        intersection: Symbol
        "intersection: (-> Atom Atom %Undefined%)\n\n`collections.Counter` IS the multiset algebra, and `&` is its intersection."
        intersection_atom: Symbol
        "intersection-atom: (-> Expression Expression Atom)\n\n`Counter` over children, answering an expression."
        is_alpha_member: Symbol
        is_expr: Symbol
        is_function: Symbol
        "is-function: (-> Type Bool)\n\nAsking whether a type is an arrow. In Python the same question is asked of the annotation, and `m.is_function(name)` asks it of a defined name."
        is_ground: Symbol
        is_member: Symbol
        is_space: Symbol
        is_var: Symbol
        isinf_math: Symbol
        "isinf-math: (-> Number Bool)\n\n`math.isinf`."
        isnan_math: Symbol
        "isnan-math: (-> Number Bool)\n\n`math.isnan`."
        last: Symbol
        le: Symbol
        "<=: (-> Number Number Bool)\n\nPython's own operator."
        length: Symbol
        let: Symbol
        "let: (-> Atom %Undefined% Atom %Undefined%)\n\nAssignment. It reads in MeTTa's own order, bind then use, which is why plain assignment and not the walrus is the taught spelling."
        library: Symbol
        log_math: Symbol
        "log-math: (-> Number Number Number)\n\n`math.log(x, base)`, with the arguments the other way round: MeTTa takes the base first."
        lt: Symbol
        "<: (-> Number Number Bool)\n\nPython's own operator."
        map_atom: Symbol
        "map-atom: (-> Expression Variable Atom Expression)\nmap-atom: (-> Expression Expression Expression)\n\nA comprehension, or `map`. The variable and the template are the comprehension's own binder and body."
        maplist: Symbol
        match: Symbol
        "match: (-> SpaceType Atom Atom %Undefined%)\n\n`space[pattern]` is the subscript form and `space.match(pattern)` the named method; the TEMPLATE is built in Python from the answer's bindings. `under=counting|tropical|prov|ranked` changes the annotation algebra; `answers(call, under=...)` is its call twin, `with metta.under(...)` scopes the default, and an annotated answer exposes `.annotation`, `.why()` and `.under(other)` without a re-query. `metta.algebra(...)` constructs arbitrary carriers while remaining their namespace."
        match_types: Symbol
        max: Symbol
        max_atom: Symbol
        "max-atom: (-> %Undefined% Number)\n\nPython's builtin `max` over the children."
        member: Symbol
        metta: Symbol
        "metta: (-> Atom Type SpaceType Atom)\n\nThe full interpreter, which is what CALLING does: a defined object called from Python evaluates, and `m.eval` on a built term is the same act."
        metta_thread: Symbol
        min: Symbol
        min_atom: Symbol
        "min-atom: (-> %Undefined% Number)\n\nPython's builtin `min` over the children."
        mm2_exec: Symbol
        mod: Symbol
        "%: (-> Number Number Number)\n\nPython's own operator. Both take the sign of the divisor for a positive divisor; a Euclidean `%` differs on a NEGATIVE divisor, which parts them and `mod-floor` is the name for Python's convention."
        mork_add_atoms: Symbol
        mork_flush: Symbol
        msort: Symbol
        mul: Symbol
        "*: (-> Number Number Number)\n\nPython's own operator."
        ne: Symbol
        neg: Callable[[object], Expression]
        new_space: Symbol
        "new-space: (-> SpaceType)\n\n`metta.space()`. A constructor call is Python's own spelling for `make me a fresh one`, and the row asks the fresh space for its atoms because the NAME a space gets differs per engine."
        new_state: Symbol
        "new-state: (-> $t (StateMonad $t))\n\n`metta.State[T](value, space=space)` creates the typed Python handle. The row reads `.value` because the engine cell itself is deliberately hidden behind that handle. An event `fold(..., into=state)` passes this same process-shared cell to its step; individual reads and writes are thread-safe, but a compound read-modify-write needs coordination."
        noeval: Symbol
        "noeval: (-> Atom Atom)\n\nThe same point as `quote`: a built term is already unevaluated."
        nop: Symbol
        "nop: (-> (:seg %Undefined%) (->))\n\nPython's `pass`, or simply not writing the call. It answers the unit."
        noreduce_eq: Symbol
        "noreduce-eq: (-> Atom Atom Bool)\n\nComparing two atoms WITHOUT reducing them is what Python's `==` on atoms already does: building a term never evaluates it."
        not_: Symbol
        "not: (-> Bool Bool)\n\nPython's own keyword; `~` is the operator form on atoms."
        not_provable: Symbol
        on_unwind: Symbol
        "on-unwind: (-> Atom Atom Atom)\n\nEvaluate a held source and apply a held native handler once on failure, cut or exception. The handler receives the native catcher as a product, such as `(fail)` or `(exception Ball)`. Deterministic completion leaves the handler untouched; cleanup exceptions follow SWI's urgency rules."
        once: Symbol
        only: Symbol
        or_: Symbol
        "or: (-> Bool Bool Bool)\n\nPython's own keyword; `|` is the operator form on atoms."
        or_else: Symbol
        owned_record_read: Symbol
        "owned-record-read: (-> Atom Atom)\n\nRead a native owned record as data: the held `@owned-record` key names the home, the owner, the storage and the row prefix; the answer is the record's zero or one complete rows, with a stored expression left unevaluated. A retired owner or a second value refuses."
        parse: Symbol
        parse_command: Symbol
        pow: Symbol
        "pow-math: (-> Number Number Number)\n\nPython's `**` operator. MeTTa answers a float where Python's integer power answers an integer, so the row raises a float."
        pow_math: Symbol
        "pow-math: (-> Number Number Number)\n\nPython's `**` operator. MeTTa answers a float where Python's integer power answers an integer, so the row raises a float."
        pragma: Symbol
        prefix: Symbol
        pretty_atom: Symbol
        println: Symbol
        "println!: (-> %Undefined% Bool)\n\nPython's `print`. It answers True rather than unit, which is upstream's own answer: `'println!'(Arg, true)` [source: PeTTa@ae66fa8 src/metta.pl:212]."
        prog1: Symbol
        progn: Symbol
        py_at: Symbol
        py_atom: Symbol
        py_call: Symbol
        py_container_kind: Symbol
        py_dict: Symbol
        py_dict_pairs: Symbol
        py_dot: Symbol
        py_eq: Symbol
        py_except: Symbol
        py_format: Symbol
        py_global_read: Symbol
        py_global_write: Symbol
        py_in: Symbol
        py_iter: Symbol
        py_iter_once: Symbol
        py_len: Symbol
        py_list: Symbol
        py_operator: Symbol
        py_range: Symbol
        py_repr: Symbol
        py_round: Symbol
        py_sequence_image: Symbol
        py_set: Symbol
        py_set_pairs: Symbol
        py_slice: Symbol
        py_str: Symbol
        py_str_join: Symbol
        py_truthy: Symbol
        py_tuple: Symbol
        qualified: Symbol
        quote: Symbol
        "quote: (-> Atom Atom)\n\nThere is nothing to quote: building a term with `S[...]` never evaluates it, so the quoting question does not arise. `S.quote(x)` builds the term itself where a program needs the constructor."
        random_float: Symbol
        random_int: Symbol
        read_form: Symbol
        readln: Symbol
        reduce: Symbol
        register_token: Symbol
        remove_atom: Symbol
        "remove-atom: (-> SpaceType Atom Bool)\n\nDrains every atom that unifies and answers True either way. `del space[pattern]` is this operation, and raises when the pattern matches nothing as Python's `del` does; `subtract-atom` is the one-occurrence grain beside it, which `space -= atom` and `space.remove(atom)` both spell."
        remove_translator_rule: Symbol
        remove_typing_rule: Symbol
        rename: Symbol
        repr: Symbol
        repra: Symbol
        require_extension: Symbol
        residual_goals: Symbol
        retractPredicate: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        return_: Symbol
        "return: (-> $t $t)\n\nThe core's return, paired with `function`: it is what closes the frame, so it only ever appears inside one."
        return_on_error: Symbol
        "return-on-error: (-> Atom Atom %Undefined%)\n\nEarly return, which is Python's own `return` inside an `if`. Indexing needs the guard because a leaf atom is not indexable here."
        reverse: Symbol
        round_math: Symbol
        "round-math: (-> Number Number)\n\nNOT Python's `round`: `round` breaks a tie to the EVEN neighbour, so `round(2.5)` is 2 where MeTTa answers 3. Half away from zero is `math.floor(x + 0.5)` for a positive number."
        sealed: Symbol
        "sealed: (-> Expression Atom Atom)\n\nFreshening every variable except a named few, the hygiene primitive under rule emission. The Python surface makes most uses unnecessary by construction, because a parameter-scoped rule is fresh per rule, so the row shows the law spelling."
        second_from_pair: Symbol
        sin_math: Symbol
        "sin-math: (-> Number Number)\n\n`math.sin`."
        size_atom: Symbol
        "size-atom: (-> Expression Number)\n\n`len`. Both count CHILDREN, so `(f a b)` is 3 either way."
        sleep: Symbol
        sort: Symbol
        sort_atom: Symbol
        sort_strings: Symbol
        "sort-strings: (-> Expression Expression)\n\nPython's builtin `sorted`. A tuple goes back in as one expression."
        space_admission_verdict: Symbol
        space_atom_count: Symbol
        space_contains: Symbol
        sqrt_math: Symbol
        "sqrt-math: (-> Number Number)\n\n`math.sqrt`."
        sread: Symbol
        sub: Symbol
        "-: (-> Number Number Number)\n\nPython's own operator."
        subtract_atom: Symbol
        "subtract-atom: (-> SpaceType Atom Bool)\n\nTakes ONE unifying occurrence and answers whether one was there, the multiset subtraction `remove-atom` gave up when it took upstream's draining law. `space -= atom` is this operation, because Python's in-place difference over a multiset is `collections.Counter`'s, which subtracts the multiplicity given rather than clearing the key, and `space.remove(atom)` is the same grain reporting what it found. An unbound atom is refused by name rather than read as every atom at once."
        subtraction: Symbol
        "subtraction: (-> Atom Atom %Undefined%)\n\n`Counter` again, with `-`."
        subtraction_atom: Symbol
        "subtraction-atom: (-> Expression Expression Atom)\n\n`Counter` over children, answering an expression."
        super: Symbol
        superpose: Symbol
        "superpose: (-> Expression %Undefined%)\n\nNondeterminism has no primitive of its own because Python's iteration IS it: a list of values is a multiset of answers, and `yield` is the same act inside a compiled body. `space.sample(q, k=10, seed=7)` is the weighted choice method, with replacement and implicit `(rate n)` weights."
        superpose_bind: Symbol
        "superpose-bind: (-> Expression Atom)\n\nThe inverse of `collapse-bind`: it restores each alternative WITH its recorded bindings, which is a different operation from `superpose`."
        switch: Symbol
        "switch: (-> %Undefined% Expression %Undefined%)\n\nPython's `match` statement again. `switch` differs from `case` only in evaluating its subject first, which a Python expression does anyway."
        take: Symbol
        tan_math: Symbol
        "tan-math: (-> Number Number)\n\n`math.tan`."
        test: Symbol
        test_no_answer: Symbol
        throw: Symbol
        timeout: Symbol
        top: Symbol
        trace: Symbol
        "trace!: (-> %Undefined% Atom %Undefined%)\n\n`print` or `logging` beside the value; `m.trace()` is the engine's own reduction trace, a different and deeper thing."
        transaction: Symbol
        translatePredicate: Symbol  # noqa: N815 -- the catalog owns this Python-compatible spelling
        truediv: Symbol
        "/: (-> Number Number Number)\n\nPython's `/` is true division, and so is this engine's. An integer `/` is EUCLIDEAN by its own ruling, so `(/ 7 2)` is 3 there and 3.5 here; on floats all three agree."
        trunc_math: Symbol
        "trunc-math: (-> Number Number)\n\n`math.trunc`, or `int` on a float."
        type_cast: Symbol
        type_cast_holds: Symbol
        undeclare_post_add: Symbol
        undeclare_pre_add: Symbol
        undocumented: Symbol
        undocumented_space: Symbol
        unify: Symbol
        "unify: (-> Atom Atom Atom Atom %Undefined%)\n\nStructural unification. `metta.unify(a, b)` symmetrically answers one substitution keyed by the VARIABLES, which is what `atom.subs` takes, or `None`; `metta.unify(a, b, then, els)` evaluates the engine conditional, running `then` once per binding set and `els` only when none exists. A compiled body lowers the same four-argument call directly to the engine form."
        union: Symbol
        "union: (-> Atom Atom %Undefined%)\n\nMultiset union over nondeterministic answers, which is concatenation: answers are iterables and `+` joins them."
        union_atom: Symbol
        "union-atom: (-> Expression Expression Atom)\n\nThe same act over an expression's children; a tuple goes back in as one expression."
        unique: Symbol
        "unique: (-> Atom %Undefined%)\n\n`dict.fromkeys` is Python's order-preserving dedupe."
        unique_atom: Symbol
        "unique-atom: (-> Expression Atom)\n\n`dict.fromkeys` over children."
        unquote: Symbol
        "unquote: (-> %Undefined% %Undefined%)\n\nReducing a quoted term is `m.eval`, primitive 4."
        unregister_token: Symbol
        with_pragma: Symbol
        with_seed: Symbol
        xor: Symbol
        "xor: (-> Bool Bool Bool)\n\nPython's `^` on booleans."
        def __getitem__(self, name: str, /) -> Symbol: ...


_NAMES = frozenset(
    {
        "!=",
        "#*",
        "#+",
        "#-",
        "#//",
        "#<",
        "#=",
        "#=<",
        "#>",
        "#>=",
        "#\\=",
        "#div",
        "#max",
        "#min",
        "#mod",
        "%",
        "*",
        "+",
        "-",
        "/",
        "<",
        "<=",
        "=",
        "==",
        "=?",
        "=alpha",
        ">",
        ">=",
        "Predicate",
        "__metta_type_syntax__",
        "abs-math",
        "acos-math",
        "add-atom",
        "add-atoms",
        "add-reduct",
        "add-reducts",
        "add-translator-rule!",
        "add-typing-rule!",
        "alpha-unique",
        "alpha-unique-atom",
        "and",
        "and-then",
        "annotation",
        "append",
        "argv",
        "asin-math",
        "assert",
        "assert-answers",
        "assert-includes-answers",
        "assertAlphaEqual",
        "assertAlphaEqualMsg",
        "assertAlphaEqualToResult",
        "assertAlphaEqualToResultMsg",
        "assertEqual",
        "assertEqualMsg",
        "assertEqualToResult",
        "assertEqualToResultMsg",
        "assertIncludes",
        "assertaPredicate",
        "assertzPredicate",
        "atan-math",
        "atom-subst",
        "atom_chars",
        "atom_concat",
        "atomically",
        "bind!",
        "bit-and",
        "bit-not",
        "bit-or",
        "bit-shift-left",
        "bit-shift-right",
        "bit-xor",
        "call",
        "callPredicate",
        "car-atom",
        "case",
        "catch",
        "cdr-atom",
        "ceil-math",
        "chain",
        "change-state!",
        "check_prolog_function_names",
        "collapse",
        "collapse-bind",
        "cons",
        "cons-atom",
        "context-space",
        "copy_term",
        "cos-math",
        "current-time",
        "cut",
        "declare-post-add!",
        "declare-pre-add!",
        "decons",
        "decons-atom",
        "defined-name",
        "dif",
        "documented",
        "documented-space",
        "elapsed",
        "empty",
        "error-payload",
        "eval",
        "eval-one",
        "evalc",
        "except",
        "exclude-item",
        "exists_file",
        "exp",
        "exp-math",
        "explain",
        "filter-atom",
        "first",
        "first-from-pair",
        "floor-div",
        "floor-math",
        "foldall",
        "foldl",
        "foldl-atom",
        "for-each-in-atom",
        "forall",
        "format-args",
        "format-time",
        "function",
        "get-atoms",
        "get-doc",
        "get-doc-atom",
        "get-doc-function",
        "get-doc-params",
        "get-doc-single-atom",
        "get-doc-space",
        "get-metatype",
        "get-property",
        "get-state",
        "get-type",
        "get-type-space",
        "git-import!",
        "has-declared-type",
        "help!",
        "hyperpose",
        "id",
        "if",
        "if-decons-expr",
        "if-equal",
        "if-equal2",
        "if-error",
        "implies",
        "import!",
        "import_prolog_function",
        "import_prolog_functions",
        "include",
        "index-atom",
        "inferences",
        "interpret",
        "intersection",
        "intersection-atom",
        "is-alpha-member",
        "is-expr",
        "is-function",
        "is-ground",
        "is-member",
        "is-space",
        "is-var",
        "isinf-math",
        "isnan-math",
        "last",
        "length",
        "let",
        "let*",
        "library",
        "list_to_set",
        "log-math",
        "map-atom",
        "maplist",
        "match",
        "match-type-or",
        "match-types",
        "max",
        "max-atom",
        "member",
        "metta",
        "metta-thread",
        "min",
        "min-atom",
        "mm2-exec",
        "mork-add-atoms",
        "mork-flush",
        "msort",
        "new-space",
        "new-state",
        "noeval",
        "nop",
        "noreduce-eq",
        "not",
        "not-provable",
        "on-unwind",
        "once",
        "only",
        "or",
        "or-else",
        "owned-record-read",
        "parse",
        "parse-command",
        "pow-math",
        "pragma!",
        "prefix",
        "pretty-atom",
        "println!",
        "prog1",
        "progn",
        "py-at",
        "py-atom",
        "py-call",
        "py-container-kind",
        "py-dict",
        "py-dict-pairs",
        "py-dot",
        "py-eq",
        "py-except",
        "py-format",
        "py-global-read",
        "py-global-write",
        "py-in",
        "py-iter",
        "py-iter-once",
        "py-len",
        "py-list",
        "py-operator",
        "py-range",
        "py-repr",
        "py-round",
        "py-sequence-image",
        "py-set",
        "py-set-pairs",
        "py-slice",
        "py-str",
        "py-str-join",
        "py-truthy",
        "py-tuple",
        "qualified",
        "quote",
        "random-float",
        "random-int",
        "read-form!",
        "readln!",
        "reduce",
        "register-token!",
        "register_metta_library_path",
        "remove-atom",
        "remove-translator-rule!",
        "remove-typing-rule!",
        "rename",
        "repr",
        "repra",
        "require-extension!",
        "residual-goals",
        "retractPredicate",
        "return",
        "return-on-error",
        "reverse",
        "round-math",
        "sealed",
        "second-from-pair",
        "sin-math",
        "size-atom",
        "sleep",
        "sort",
        "sort-atom",
        "sort-strings",
        "space-admission-verdict",
        "space-atom-count",
        "space-contains",
        "sqrt-math",
        "sread",
        "subtract-atom",
        "subtraction",
        "subtraction-atom",
        "super",
        "superpose",
        "superpose-bind",
        "switch",
        "take",
        "tan-math",
        "term_hash",
        "test",
        "test-no-answer",
        "throw",
        "timeout",
        "top",
        "trace!",
        "transaction",
        "translatePredicate",
        "trunc-math",
        "type-cast",
        "type-cast-holds",
        "undeclare-post-add!",
        "undeclare-pre-add!",
        "undocumented",
        "undocumented-space",
        "unify",
        "union",
        "union-atom",
        "unique",
        "unique-atom",
        "unquote",
        "unregister-token!",
        "with-pragma!",
        "with-seed",
        "with_mutex",
        "xor",
        "|->",
    }
)

_ALIASES: dict[str, str] = {}
_ALIASES.update(
    (
        ("Predicate", "Predicate"),
        ("abs_math", "abs-math"),
        ("acos_math", "acos-math"),
        ("add", "+"),
        ("add_atom", "add-atom"),
        ("add_atoms", "add-atoms"),
        ("add_reduct", "add-reduct"),
        ("add_reducts", "add-reducts"),
        ("add_translator_rule", "add-translator-rule!"),
        ("add_typing_rule", "add-typing-rule!"),
        ("alpha_unique", "alpha-unique"),
        ("alpha_unique_atom", "alpha-unique-atom"),
        ("and_", "and"),
        ("and_then", "and-then"),
        ("annotation", "annotation"),
        ("append", "append"),
        ("argv", "argv"),
        ("asin_math", "asin-math"),
        ("assertAlphaEqual", "assertAlphaEqual"),
        ("assertAlphaEqualMsg", "assertAlphaEqualMsg"),
        ("assertAlphaEqualToResult", "assertAlphaEqualToResult"),
        ("assertAlphaEqualToResultMsg", "assertAlphaEqualToResultMsg"),
        ("assertEqual", "assertEqual"),
        ("assertEqualMsg", "assertEqualMsg"),
        ("assertEqualToResult", "assertEqualToResult"),
        ("assertEqualToResultMsg", "assertEqualToResultMsg"),
        ("assertIncludes", "assertIncludes"),
        ("assert_", "assert"),
        ("assert_answers", "assert-answers"),
        ("assert_includes_answers", "assert-includes-answers"),
        ("assertaPredicate", "assertaPredicate"),
        ("assertzPredicate", "assertzPredicate"),
        ("atan_math", "atan-math"),
        ("atom_subst", "atom-subst"),
        ("atomically", "atomically"),
        ("bind", "bind!"),
        ("bit_and", "bit-and"),
        ("bit_not", "bit-not"),
        ("bit_or", "bit-or"),
        ("bit_shift_left", "bit-shift-left"),
        ("bit_shift_right", "bit-shift-right"),
        ("bit_xor", "bit-xor"),
        ("call", "call"),
        ("callPredicate", "callPredicate"),
        ("car_atom", "car-atom"),
        ("case", "case"),
        ("catch", "catch"),
        ("cdr_atom", "cdr-atom"),
        ("ceil_math", "ceil-math"),
        ("chain", "chain"),
        ("change_state", "change-state!"),
        ("collapse", "collapse"),
        ("collapse_bind", "collapse-bind"),
        ("cons", "cons"),
        ("cons_atom", "cons-atom"),
        ("context_space", "context-space"),
        ("cos_math", "cos-math"),
        ("current_time", "current-time"),
        ("cut", "cut"),
        ("declare_post_add", "declare-post-add!"),
        ("declare_pre_add", "declare-pre-add!"),
        ("decons", "decons"),
        ("decons_atom", "decons-atom"),
        ("defined_name", "defined-name"),
        ("dif", "dif"),
        ("documented", "documented"),
        ("documented_space", "documented-space"),
        ("elapsed", "elapsed"),
        ("empty", "empty"),
        ("eq", "=="),
        ("error_payload", "error-payload"),
        ("eval", "eval"),
        ("eval_one", "eval-one"),
        ("evalc", "evalc"),
        ("except_", "except"),
        ("exclude_item", "exclude-item"),
        ("exp", "exp"),
        ("exp_math", "exp-math"),
        ("explain", "explain"),
        ("filter_atom", "filter-atom"),
        ("first", "first"),
        ("first_from_pair", "first-from-pair"),
        ("floor_div", "floor-div"),
        ("floor_math", "floor-math"),
        ("foldall", "foldall"),
        ("foldl", "foldl"),
        ("foldl_atom", "foldl-atom"),
        ("for_each_in_atom", "for-each-in-atom"),
        ("forall", "forall"),
        ("format_args", "format-args"),
        ("format_time", "format-time"),
        ("function", "function"),
        ("ge", ">="),
        ("get_atoms", "get-atoms"),
        ("get_doc", "get-doc"),
        ("get_doc_atom", "get-doc-atom"),
        ("get_doc_function", "get-doc-function"),
        ("get_doc_params", "get-doc-params"),
        ("get_doc_single_atom", "get-doc-single-atom"),
        ("get_doc_space", "get-doc-space"),
        ("get_metatype", "get-metatype"),
        ("get_property", "get-property"),
        ("get_state", "get-state"),
        ("get_type", "get-type"),
        ("get_type_space", "get-type-space"),
        ("git_import", "git-import!"),
        ("gt", ">"),
        ("has_declared_type", "has-declared-type"),
        ("help", "help!"),
        ("hyperpose", "hyperpose"),
        ("id", "id"),
        ("if_", "if"),
        ("if_decons_expr", "if-decons-expr"),
        ("if_equal", "if-equal"),
        ("if_equal2", "if-equal2"),
        ("if_error", "if-error"),
        ("implies", "implies"),
        ("import_", "import!"),
        ("include", "include"),
        ("index_atom", "index-atom"),
        ("inferences", "inferences"),
        ("interpret", "interpret"),
        ("intersection", "intersection"),
        ("intersection_atom", "intersection-atom"),
        ("is_alpha_member", "is-alpha-member"),
        ("is_expr", "is-expr"),
        ("is_function", "is-function"),
        ("is_ground", "is-ground"),
        ("is_member", "is-member"),
        ("is_space", "is-space"),
        ("is_var", "is-var"),
        ("isinf_math", "isinf-math"),
        ("isnan_math", "isnan-math"),
        ("last", "last"),
        ("le", "<="),
        ("length", "length"),
        ("let", "let"),
        ("library", "library"),
        ("log_math", "log-math"),
        ("lt", "<"),
        ("map_atom", "map-atom"),
        ("maplist", "maplist"),
        ("match", "match"),
        ("match_type_or", "match-type-or"),
        ("match_types", "match-types"),
        ("max", "max"),
        ("max_atom", "max-atom"),
        ("member", "member"),
        ("metta", "metta"),
        ("metta_thread", "metta-thread"),
        ("min", "min"),
        ("min_atom", "min-atom"),
        ("mm2_exec", "mm2-exec"),
        ("mod", "%"),
        ("mork_add_atoms", "mork-add-atoms"),
        ("mork_flush", "mork-flush"),
        ("msort", "msort"),
        ("mul", "*"),
        ("ne", "!="),
        ("neg", "neg"),
        ("new_space", "new-space"),
        ("new_state", "new-state"),
        ("noeval", "noeval"),
        ("nop", "nop"),
        ("noreduce_eq", "noreduce-eq"),
        ("not_", "not"),
        ("not_provable", "not-provable"),
        ("on_unwind", "on-unwind"),
        ("once", "once"),
        ("only", "only"),
        ("or_", "or"),
        ("or_else", "or-else"),
        ("owned_record_read", "owned-record-read"),
        ("parse", "parse"),
        ("parse_command", "parse-command"),
        ("pow", "pow-math"),
        ("pow_math", "pow-math"),
        ("pragma", "pragma!"),
        ("prefix", "prefix"),
        ("pretty_atom", "pretty-atom"),
        ("println", "println!"),
        ("prog1", "prog1"),
        ("progn", "progn"),
        ("py_at", "py-at"),
        ("py_atom", "py-atom"),
        ("py_call", "py-call"),
        ("py_container_kind", "py-container-kind"),
        ("py_dict", "py-dict"),
        ("py_dict_pairs", "py-dict-pairs"),
        ("py_dot", "py-dot"),
        ("py_eq", "py-eq"),
        ("py_except", "py-except"),
        ("py_format", "py-format"),
        ("py_global_read", "py-global-read"),
        ("py_global_write", "py-global-write"),
        ("py_in", "py-in"),
        ("py_iter", "py-iter"),
        ("py_iter_once", "py-iter-once"),
        ("py_len", "py-len"),
        ("py_list", "py-list"),
        ("py_operator", "py-operator"),
        ("py_range", "py-range"),
        ("py_repr", "py-repr"),
        ("py_round", "py-round"),
        ("py_sequence_image", "py-sequence-image"),
        ("py_set", "py-set"),
        ("py_set_pairs", "py-set-pairs"),
        ("py_slice", "py-slice"),
        ("py_str", "py-str"),
        ("py_str_join", "py-str-join"),
        ("py_truthy", "py-truthy"),
        ("py_tuple", "py-tuple"),
        ("qualified", "qualified"),
        ("quote", "quote"),
        ("random_float", "random-float"),
        ("random_int", "random-int"),
        ("read_form", "read-form!"),
        ("readln", "readln!"),
        ("reduce", "reduce"),
        ("register_token", "register-token!"),
        ("remove_atom", "remove-atom"),
        ("remove_translator_rule", "remove-translator-rule!"),
        ("remove_typing_rule", "remove-typing-rule!"),
        ("rename", "rename"),
        ("repr", "repr"),
        ("repra", "repra"),
        ("require_extension", "require-extension!"),
        ("residual_goals", "residual-goals"),
        ("retractPredicate", "retractPredicate"),
        ("return_", "return"),
        ("return_on_error", "return-on-error"),
        ("reverse", "reverse"),
        ("round_math", "round-math"),
        ("sealed", "sealed"),
        ("second_from_pair", "second-from-pair"),
        ("sin_math", "sin-math"),
        ("size_atom", "size-atom"),
        ("sleep", "sleep"),
        ("sort", "sort"),
        ("sort_atom", "sort-atom"),
        ("sort_strings", "sort-strings"),
        ("space_admission_verdict", "space-admission-verdict"),
        ("space_atom_count", "space-atom-count"),
        ("space_contains", "space-contains"),
        ("sqrt_math", "sqrt-math"),
        ("sread", "sread"),
        ("sub", "-"),
        ("subtract_atom", "subtract-atom"),
        ("subtraction", "subtraction"),
        ("subtraction_atom", "subtraction-atom"),
        ("super", "super"),
        ("superpose", "superpose"),
        ("superpose_bind", "superpose-bind"),
        ("switch", "switch"),
        ("take", "take"),
        ("tan_math", "tan-math"),
        ("test", "test"),
        ("test_no_answer", "test-no-answer"),
        ("throw", "throw"),
        ("timeout", "timeout"),
        ("top", "top"),
        ("trace", "trace!"),
        ("transaction", "transaction"),
        ("translatePredicate", "translatePredicate"),
        ("truediv", "/"),
        ("trunc_math", "trunc-math"),
        ("type_cast", "type-cast"),
        ("type_cast_holds", "type-cast-holds"),
        ("undeclare_post_add", "undeclare-post-add!"),
        ("undeclare_pre_add", "undeclare-pre-add!"),
        ("undocumented", "undocumented"),
        ("undocumented_space", "undocumented-space"),
        ("unify", "unify"),
        ("union", "union"),
        ("union_atom", "union-atom"),
        ("unique", "unique"),
        ("unique_atom", "unique-atom"),
        ("unquote", "unquote"),
        ("unregister_token", "unregister-token!"),
        ("with_pragma", "with-pragma!"),
        ("with_seed", "with-seed"),
        ("xor", "xor"),
    )
)

_DOCUMENTATION = {
    "%": "%: (-> Number Number Number)\n\nPython's own operator. Both take the sign of the divisor for a positive divisor; a Euclidean `%` differs on a NEGATIVE divisor, which parts them and `mod-floor` is the name for Python's convention.",
    "*": "*: (-> Number Number Number)\n\nPython's own operator.",
    "+": "+: (-> Number Number Number)\n\nPython's own operator. On atoms the same operator builds `(+ ...)` instead of computing, which is how a compiled body reaches the MeTTa function.",
    "-": "-: (-> Number Number Number)\n\nPython's own operator.",
    "/": "/: (-> Number Number Number)\n\nPython's `/` is true division, and so is this engine's. An integer `/` is EUCLIDEAN by its own ruling, so `(/ 7 2)` is 3 there and 3.5 here; on floats all three agree.",
    "<": "<: (-> Number Number Bool)\n\nPython's own operator.",
    "<=": "<=: (-> Number Number Bool)\n\nPython's own operator.",
    "=": "=: (-> $t $t %Undefined%)\n\nThe definitional decorator. `@m.define` compiles a function into equations, `metta.equation(lhs).to(rhs)` builds one by hand, and both land as ordinary `(= ...)` atoms a program can match.",
    "==": "==: (-> $t $t Bool)\n\nPython's own operator, and atoms compare structurally under it.",
    "=alpha": "=alpha: (-> Atom Atom Bool)\n\nEquality modulo variable renaming is not a Python concept, so it keeps MeTTa's noun. `a.alpha_eq(b)` is the method form of the same act.",
    ">": ">: (-> Number Number Bool)\n\nPython's own operator.",
    ">=": ">=: (-> Number Number Bool)\n\nPython's own operator.",
    "abs-math": "abs-math: (-> Number Number)\n\nPython's builtin `abs`.",
    "acos-math": "acos-math: (-> Number Number)\n\n`math.acos`.",
    "add-atom": "add-atom: (-> SpaceType Atom (->))\n\n`space += atom`, the container protocol. A plain Python tuple encodes to an expression on the way in, so a fact needs no builder ceremony. This spelling takes upstream PeTTa's domain, an atom with a HEAD, and has no answer for a bare symbol, a grounded value or the empty expression; `add-atoms` is the door onto the wider space and `space += atom` uses it.",
    "add-atoms": "add-atoms: (-> SpaceType Expression (->))\n\nThe same `+=` form, once per fact: anything that yields tuples is a fact stream. Lists, outer tuples of rows, generators, SQL cursors, and dataframe row iterators each write one atom per yielded item; a built Expression is always one atom.",
    "add-reduct": "add-reduct: (-> SpaceType %Undefined% (->))\n\nThere is no second form: `+=` adds what you give it, so adding a REDUCT is explicit composition, `space += m.eval(term)[0]`. Bare grounded answers use `+=` directly; this row wraps the evaluated sum only to retain its `total` relation head.",
    "add-reducts": "add-reducts: (-> SpaceType %Undefined% (->))\n\nThe plural of the same composition: evaluate, then write the answers.",
    "and": "and: (-> Bool Bool Bool)\n\nPython's own keyword. On atoms `&` builds the MeTTa `and` instead, because the keyword cannot be overloaded.",
    "asin-math": "asin-math: (-> Number Number)\n\n`math.asin`.",
    "assert": "assert: (-> Atom (->))\n\nPython's own `assert`. A twin or a test states its claims this way and the run proves them, because a false assertion raises.",
    "assertAlphaEqual": "assertAlphaEqual: (-> Atom Atom (->))\n\n`assert a.alpha_eq(b)`: the assertion is Python's, the relation is MeTTa's.",
    "assertAlphaEqualMsg": "assertAlphaEqualMsg: (-> Atom Atom Atom (->))\n\nThe same with Python's assertion message.",
    "assertAlphaEqualToResult": "assertAlphaEqualToResult: (-> Atom Atom (->))\n\nThe answer-list form compared modulo renaming.",
    "assertAlphaEqualToResultMsg": "assertAlphaEqualToResultMsg: (-> Atom Atom Atom (->))\n\nThe same with Python's assertion message.",
    "assertEqual": "assertEqual: (-> Atom Atom (->))\n\n`assert a == b`, and pytest's own assertion rewriting prints the halves.",
    "assertEqualMsg": "assertEqualMsg: (-> Atom Atom Atom (->))\n\n`assert a == b, message`, which is Python's own second argument.",
    "assertEqualToResult": "assertEqualToResult: (-> Atom Atom (->))\n\nThe right-hand side is a LIST of expected answers rather than one, which is `assert list(answers) == [...]`.",
    "assertEqualToResultMsg": "assertEqualToResultMsg: (-> Atom Atom Atom (->))\n\nThe same with Python's assertion message.",
    "assertIncludes": "assertIncludes: (-> Atom Expression (->))\n\nPython's own `in`.",
    "atan-math": "atan-math: (-> Number Number)\n\n`math.atan`.",
    "atom-subst": "atom-subst: (-> Atom (:Atom Variable) Atom Atom)\n\nApplying a substitution to a template, which `Atom.map` does over the whole term. Section 9e wants the bindings object to carry it, `b.apply(template)`; `metta.Bindings` has no such method yet, so the walker is the spelling.",
    "bind!": "bind!: (-> Symbol %Undefined% (->))\n\nA Python name binding. `space = metta.space(...)` is exactly what a token binding was for, and Python's own scoping rules then apply.",
    "car-atom": "car-atom: (-> Expression %Undefined%)\n\nIndexing. An expression is a sequence in Python, so its head is `e[0]`.",
    "case": "case: (-> Atom Expression %Undefined%)\n\nPython's `match` statement. A bare variable arm is `case _`.",
    "cdr-atom": "cdr-atom: (-> Expression Expression)\n\nSlicing. `e[1:]` answers a Python tuple today rather than an Expression, which prints the same and is the T6 friction section 9e names as this bucket's one prerequisite.",
    "ceil-math": "ceil-math: (-> Number Number)\n\n`math.ceil`, which answers an integer in Python 3 where a float-preserving float.",
    "chain": "chain: (-> Atom Variable Atom %Undefined%)\n\nPython assignment, and `let`'s own instruction under a second name: it runs the operand, binds the VALUE it produced once, and continues into the template, which is exactly `x = m.eval(t)[0]` followed by use of `x`.",
    "change-state!": "change-state!: (-> (StateMonad $tcso) $tcso Bool)\n\nAssigning `state.value` writes the same typed engine cell and reading it back returns the replacement. The WRITE answers True rather than the cell, which is upstream's own answer -- `'change-state!'(Var, Value, true)` [source: PeTTa@ae66fa8 src/metta.pl:265] -- so the read is a separate step here as it is in Python.",
    "collapse": "collapse: (-> Atom Atom)\n\n`list()` is the everyday spelling, materialising the answers; `tuple()` is the same act when you want MeTTa's own `( )` atom back, which is what collapse answers.",
    "collapse-bind": "collapse-bind: (-> Atom Expression)\ncollapse-bind: (TU Expression)\n\nThe deep-tier collapse that keeps each alternative's BINDINGS, `((a (bindings ...)) ...)`. It belongs to the bindings-carrying tier, never to the surface; MeTTa's engine has the bindings carrier (`answer_bindings`) but not this instruction.",
    "cons-atom": "cons-atom: (-> Atom Expression Atom)\n\nConstruction: call the head, or rebuild from head and tail with `*`.",
    "context-space": "context-space: (-> SpaceType)\n\nThe space a program is currently in, which in Python is the handle it holds; `metta.current_space()` is the function for code that did not receive one, and it follows Python's own `current_thread` and `current_task` convention, so the Python word wins over the instruction's name. The row asks both sides for the current space's atoms.",
    "cos-math": "cos-math: (-> Number Number)\n\n`math.cos`.",
    "decons-atom": "decons-atom: (-> Expression Atom)\n\nStarred unpacking, which is the same act in one line: `head, *tail = e`.",
    "eval": "eval: (-> Atom Atom)\n\nONE step. `m.eval(term)` is the same one step and answers every result, and `space.eval(term)` is `evalc`, the same step in a named space.",
    "eval-one": "eval-one: (-> Atom Atom)\n\nEvaluate held source, count at most two answers and return the sole answer as data. Failed alternatives do not count. Zero or multiple answers raise a cardinality error before the caller can filter them.",
    "evalc": "evalc: (-> Atom SpaceType Atom)\n\nOne step WITH an explicit context space, which is `space.eval(term)`: the signature IS term plus space.",
    "filter-atom": "filter-atom: (-> Expression Variable Atom Expression)\nfilter-atom: (-> Expression Expression Expression)\n\nA comprehension with an `if`, or `filter`.",
    "floor-math": "floor-math: (-> Number Number)\n\n`math.floor`, the same integer-against-float difference as `ceil-math`.",
    "foldl-atom": "foldl-atom: (-> Expression Atom Variable Variable Atom %Undefined%)\nfoldl-atom: (-> Expression Atom Expression %Undefined%)\n\n`functools.reduce` with an initial value is the same finite left fold. For a change stream, `m.events().fold(..., under=algebra)` makes the algebra itself the step; `into=State(...)` is the running-gauge form.",
    "for-each-in-atom": "for-each-in-atom: (-> Expression Atom (->))\n\nA `for` statement. It is called for its effect, so the row prints and answers the unit. Python's `for` has no value at all, and the concept map says `None` IS the unit, but `metta.ground(None)` renders `<NoneType>` rather than `()` today, so a row that wants the unit writes it [measured 2026-08-22].",
    "format-args": "format-args: (-> String Expression String)\n\nAn f-string. MeTTa's `{}` holes are Python's own interpolation.",
    "function": "function: (-> Atom Atom)\n\nThe core's function frame, which `return` closes. MeTTa's compiled definitions do not go through this instruction and it is not implemented.",
    "get-atoms": "get-atoms: (-> SpaceType Atom)\n\n`space.atoms()`, or `for atom in space` when you want to walk them.",
    "get-doc": "get-doc: (-> SpaceType Atom %Undefined%)\n\nPython's builtin `help`, over the docstring a decorated function already carries. This engine answers nothing here because no documentation atoms are written yet, which is the doc-vocabulary gap.",
    "get-metatype": "get-metatype: (-> Atom Atom)\n\nPython's own builtin `type`: the four atom classes ARE the four metatypes, so `type(a).__name__` is the metatype by construction.",
    "get-state": "get-state: (-> (StateMonad $tgso) $tgso)\n\nReading the cell is the typed handle's `state.value` property.",
    "get-type": "get-type: (-> Atom %Undefined%)\n\nDeclared types are space-relative, so `space.type(atom)` asks the space. Class declarations use the consolidated `@space.define` decorator.",
    "get-type-space": "get-type-space: (-> SpaceType Atom Atom)\n\nThe same question asked of a named space through that handle's `space.type(atom)` method.",
    "git-import!": "git-import!: (-> String String Atom)\n\npip and `importlib`. Fetching a dependency is packaging's job, the module catalog IS Python packaging, and a boot manifest names the distribution.",
    "help!": "help!: (-> Atom (->))\nhelp!: (-> (->))\n\nPython's builtin `help`, which is the same act on the same docstring.",
    "id": "id: (-> $t $t)\n\nThe identity function, which Python writes as the value itself.",
    "if": "if: (-> Bool Atom Atom $t)\n\nPython's own `if`, and its conditional expression where a value is wanted. Both arms stay unevaluated in MeTTa because the parameters are Atom-typed, which is exactly what Python's own short-circuit does.",
    "if-decons-expr": "if-decons-expr: (-> (:Atom Expression) (:Atom Variable) (:Atom Variable) Atom Atom %Undefined%)\n\nStarred unpacking inside an `if`: the empty case is the `else` branch.",
    "if-equal": "if-equal: (-> Atom Atom Atom Atom %Undefined%)\n\nA conditional expression over `==`.",
    "if-error": "if-error: (-> Atom Atom Atom %Undefined%)\n\n`try`/`except`, or a conditional over the value. It is the railway combinator over Error atoms.",
    "import!": "import!: (-> Atom Atom (->))\n\nPython's own `import`, and for a MeTTa library the boot manifest or `m.load(path)`. The module catalog IS Python packaging.",
    "include": "include: (-> Atom %Undefined%)\n\n`space.load(path)` reads a file into that space, which is what include does; Python's own `import` is the spelling for a Python module.",
    "index-atom": "index-atom: (-> Expression Number Atom)\n\nIndexing again, with the index you want.",
    "intersection": "intersection: (-> Atom Atom %Undefined%)\n\n`collections.Counter` IS the multiset algebra, and `&` is its intersection.",
    "intersection-atom": "intersection-atom: (-> Expression Expression Atom)\n\n`Counter` over children, answering an expression.",
    "is-function": "is-function: (-> Type Bool)\n\nAsking whether a type is an arrow. In Python the same question is asked of the annotation, and `m.is_function(name)` asks it of a defined name.",
    "isinf-math": "isinf-math: (-> Number Bool)\n\n`math.isinf`.",
    "isnan-math": "isnan-math: (-> Number Bool)\n\n`math.isnan`.",
    "let": "let: (-> Atom %Undefined% Atom %Undefined%)\n\nAssignment. It reads in MeTTa's own order, bind then use, which is why plain assignment and not the walrus is the taught spelling.",
    "let*": "let*: (-> Expression Atom %Undefined%)\n\nA sequence of assignments; a statement sequence in a compiled body already chains into `let*`.",
    "log-math": "log-math: (-> Number Number Number)\n\n`math.log(x, base)`, with the arguments the other way round: MeTTa takes the base first.",
    "map-atom": "map-atom: (-> Expression Variable Atom Expression)\nmap-atom: (-> Expression Expression Expression)\n\nA comprehension, or `map`. The variable and the template are the comprehension's own binder and body.",
    "match": "match: (-> SpaceType Atom Atom %Undefined%)\n\n`space[pattern]` is the subscript form and `space.match(pattern)` the named method; the TEMPLATE is built in Python from the answer's bindings. `under=counting|tropical|prov|ranked` changes the annotation algebra; `answers(call, under=...)` is its call twin, `with metta.under(...)` scopes the default, and an annotated answer exposes `.annotation`, `.why()` and `.under(other)` without a re-query. `metta.algebra(...)` constructs arbitrary carriers while remaining their namespace.",
    "max-atom": "max-atom: (-> %Undefined% Number)\n\nPython's builtin `max` over the children.",
    "metta": "metta: (-> Atom Type SpaceType Atom)\n\nThe full interpreter, which is what CALLING does: a defined object called from Python evaluates, and `m.eval` on a built term is the same act.",
    "min-atom": "min-atom: (-> %Undefined% Number)\n\nPython's builtin `min` over the children.",
    "new-space": "new-space: (-> SpaceType)\n\n`metta.space()`. A constructor call is Python's own spelling for `make me a fresh one`, and the row asks the fresh space for its atoms because the NAME a space gets differs per engine.",
    "new-state": "new-state: (-> $t (StateMonad $t))\n\n`metta.State[T](value, space=space)` creates the typed Python handle. The row reads `.value` because the engine cell itself is deliberately hidden behind that handle. An event `fold(..., into=state)` passes this same process-shared cell to its step; individual reads and writes are thread-safe, but a compound read-modify-write needs coordination.",
    "noeval": "noeval: (-> Atom Atom)\n\nThe same point as `quote`: a built term is already unevaluated.",
    "nop": "nop: (-> (:seg %Undefined%) (->))\n\nPython's `pass`, or simply not writing the call. It answers the unit.",
    "noreduce-eq": "noreduce-eq: (-> Atom Atom Bool)\n\nComparing two atoms WITHOUT reducing them is what Python's `==` on atoms already does: building a term never evaluates it.",
    "not": "not: (-> Bool Bool)\n\nPython's own keyword; `~` is the operator form on atoms.",
    "on-unwind": "on-unwind: (-> Atom Atom Atom)\n\nEvaluate a held source and apply a held native handler once on failure, cut or exception. The handler receives the native catcher as a product, such as `(fail)` or `(exception Ball)`. Deterministic completion leaves the handler untouched; cleanup exceptions follow SWI's urgency rules.",
    "or": "or: (-> Bool Bool Bool)\n\nPython's own keyword; `|` is the operator form on atoms.",
    "owned-record-read": "owned-record-read: (-> Atom Atom)\n\nRead a native owned record as data: the held `@owned-record` key names the home, the owner, the storage and the row prefix; the answer is the record's zero or one complete rows, with a stored expression left unevaluated. A retired owner or a second value refuses.",
    "pow-math": "pow-math: (-> Number Number Number)\n\nPython's `**` operator. MeTTa answers a float where Python's integer power answers an integer, so the row raises a float.",
    "println!": "println!: (-> %Undefined% Bool)\n\nPython's `print`. It answers True rather than unit, which is upstream's own answer: `'println!'(Arg, true)` [source: PeTTa@ae66fa8 src/metta.pl:212].",
    "quote": "quote: (-> Atom Atom)\n\nThere is nothing to quote: building a term with `S[...]` never evaluates it, so the quoting question does not arise. `S.quote(x)` builds the term itself where a program needs the constructor.",
    "remove-atom": "remove-atom: (-> SpaceType Atom Bool)\n\nDrains every atom that unifies and answers True either way. `del space[pattern]` is this operation, and raises when the pattern matches nothing as Python's `del` does; `subtract-atom` is the one-occurrence grain beside it, which `space -= atom` and `space.remove(atom)` both spell.",
    "return": "return: (-> $t $t)\n\nThe core's return, paired with `function`: it is what closes the frame, so it only ever appears inside one.",
    "return-on-error": "return-on-error: (-> Atom Atom %Undefined%)\n\nEarly return, which is Python's own `return` inside an `if`. Indexing needs the guard because a leaf atom is not indexable here.",
    "round-math": "round-math: (-> Number Number)\n\nNOT Python's `round`: `round` breaks a tie to the EVEN neighbour, so `round(2.5)` is 2 where MeTTa answers 3. Half away from zero is `math.floor(x + 0.5)` for a positive number.",
    "sealed": "sealed: (-> Expression Atom Atom)\n\nFreshening every variable except a named few, the hygiene primitive under rule emission. The Python surface makes most uses unnecessary by construction, because a parameter-scoped rule is fresh per rule, so the row shows the law spelling.",
    "sin-math": "sin-math: (-> Number Number)\n\n`math.sin`.",
    "size-atom": "size-atom: (-> Expression Number)\n\n`len`. Both count CHILDREN, so `(f a b)` is 3 either way.",
    "sort-strings": "sort-strings: (-> Expression Expression)\n\nPython's builtin `sorted`. A tuple goes back in as one expression.",
    "sqrt-math": "sqrt-math: (-> Number Number)\n\n`math.sqrt`.",
    "subtract-atom": "subtract-atom: (-> SpaceType Atom Bool)\n\nTakes ONE unifying occurrence and answers whether one was there, the multiset subtraction `remove-atom` gave up when it took upstream's draining law. `space -= atom` is this operation, because Python's in-place difference over a multiset is `collections.Counter`'s, which subtracts the multiplicity given rather than clearing the key, and `space.remove(atom)` is the same grain reporting what it found. An unbound atom is refused by name rather than read as every atom at once.",
    "subtraction": "subtraction: (-> Atom Atom %Undefined%)\n\n`Counter` again, with `-`.",
    "subtraction-atom": "subtraction-atom: (-> Expression Expression Atom)\n\n`Counter` over children, answering an expression.",
    "superpose": "superpose: (-> Expression %Undefined%)\n\nNondeterminism has no primitive of its own because Python's iteration IS it: a list of values is a multiset of answers, and `yield` is the same act inside a compiled body. `space.sample(q, k=10, seed=7)` is the weighted choice method, with replacement and implicit `(rate n)` weights.",
    "superpose-bind": "superpose-bind: (-> Expression Atom)\n\nThe inverse of `collapse-bind`: it restores each alternative WITH its recorded bindings, which is a different operation from `superpose`.",
    "switch": "switch: (-> %Undefined% Expression %Undefined%)\n\nPython's `match` statement again. `switch` differs from `case` only in evaluating its subject first, which a Python expression does anyway.",
    "tan-math": "tan-math: (-> Number Number)\n\n`math.tan`.",
    "trace!": "trace!: (-> %Undefined% Atom %Undefined%)\n\n`print` or `logging` beside the value; `m.trace()` is the engine's own reduction trace, a different and deeper thing.",
    "trunc-math": "trunc-math: (-> Number Number)\n\n`math.trunc`, or `int` on a float.",
    "unify": "unify: (-> Atom Atom Atom Atom %Undefined%)\n\nStructural unification. `metta.unify(a, b)` symmetrically answers one substitution keyed by the VARIABLES, which is what `atom.subs` takes, or `None`; `metta.unify(a, b, then, els)` evaluates the engine conditional, running `then` once per binding set and `els` only when none exists. A compiled body lowers the same four-argument call directly to the engine form.",
    "union": "union: (-> Atom Atom %Undefined%)\n\nMultiset union over nondeterministic answers, which is concatenation: answers are iterables and `+` joins them.",
    "union-atom": "union-atom: (-> Expression Expression Atom)\n\nThe same act over an expression's children; a tuple goes back in as one expression.",
    "unique": "unique: (-> Atom %Undefined%)\n\n`dict.fromkeys` is Python's order-preserving dedupe.",
    "unique-atom": "unique-atom: (-> Expression Atom)\n\n`dict.fromkeys` over children.",
    "unquote": "unquote: (-> %Undefined% %Undefined%)\n\nReducing a quoted term is `m.eval`, primitive 4.",
    "xor": "xor: (-> Bool Bool Bool)\n\nPython's `^` on booleans.",
}

fn = cast("_FunctionNamespace", _Namespace(
    Symbol,
    allowed=_NAMES,
    aliases=_ALIASES,
    documentation=_DOCUMENTATION,
    label="target function",
    # This namespace is GENERATED, so it holds what the catalog held when
    # fngen last ran and cannot see a name registered since. `space.fn` is the
    # LIVE one and does, which is the whole difference between them and is
    # what a caller who has just registered something needs to be told
    # [measured 2026-08-31: an @m.pure registered at run time is absent here
    # and present on space.fn].
    remedy=(
        "; that namespace is generated, so a name registered at run time is "
        "on the live one instead: space.fn.<name>, or build the term directly "
        "with S['<name>'](...)"
    ),
    fix=Remedy(
        "reach the name on the live namespace, space.fn",
        "quickfix",
        "prose",
        python="space.fn.<name>",
    ),
))
