"""Purpose: generate AsyncMeTTa's mechanical mirror from Space, so the two
surfaces cannot drift. Sixty-six async doors were nothing but
`await self.call(lambda m: m.<name>(...))`, written by hand, and they HAD
drifted: measured 2026-08-31, fifteen carried a signature different from the
sync door's, sixteen weakened its return type, and sixty-four of sixty-six
paraphrased its docstring under a section comment claiming the synchronous
docstrings applied verbatim. Two of the fifteen were runtime refusals, not
annotations. Generation makes all three unrepresentable.

The approach is SQLAlchemy's, which solves this same problem for
AsyncConnection, AsyncEngine, AsyncSession and async_scoped_session: its
tools/generate_proxy_methods.py rewrites a marked region INSIDE the real file
rather than emitting a base class, so the doors stay where a reader and an IDE
find them [source:
https://github.com/sqlalchemy/sqlalchemy/blob/main/tools/generate_proxy_methods.py].

Assumes:
  - `Space` is the source of truth. The generator reads _space.py's AST, not a
    live class, so it needs no engine and can gate cheaply
  - a mirrored door is one AsyncMeTTa does not define itself. Hand-write a
    door and the generator stops emitting it, with no list to maintain
Guarantees:
  - every generated door carries Space's signature, return annotation and
    docstring VERBATIM, except the four in DIVERGENT which carry their stated
    reason beside them [tested:
    test_the_async_mirror_is_generated_from_the_sync_surface]
  - a new public Space method appears here or in EXCLUDED, so it cannot be
    silently absent from the async surface [tested: test_aio_mirrors_the_surface]
Fails when: a Space door's body must differ across the worker. Hand-write it in
  AsyncMeTTa and the generator yields to it.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None.
"""  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parents[2]
sys.path.insert(0, str(TOOLS))

from aio_divergences import DIVERGENT, EXCLUDED, PRIVATE_TARGET  # noqa: E402

SPACE = REPO / "extensions" / "python" / "metta" / "_space.py"
AIO = REPO / "extensions" / "python" / "metta" / "aio.py"
START = "    # ---------------------------------------------- generated mirror"
END = "    # ------------------------------------------ end of generated mirror"
WIDTH = 100

HEADER = """
    # Every door below is GENERATED by tools/aiogen.py from the synchronous
    # Space method of the same name, whose signature, return annotation and
    # docstring it carries verbatim. Each is one worker round trip. Do not
    # edit them here: change Space, or hand-write the door above this block
    # and the generator will yield to it. tools/aio_divergences.py holds the
    # exclusions and the one signature that cannot be Space's.
"""


def _class(path: Path, name: str) -> tuple[ast.ClassDef, list[str]]:
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text)
    found = next(n for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name == name)
    return found, text.splitlines()


def _handwritten(asy: ast.ClassDef, lines: list[str]) -> set[str]:
    """Doors defined OUTSIDE the generated block. Reading the whole class here
    would count the generator's own output as hand-written, and the second run
    would emit nothing.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose
    if START not in lines:
        return set(methods(asy))
    first, last = lines.index(START), lines.index(END)
    return {
        name
        for name, nodes in methods(asy).items()
        if any(not (first < node.lineno <= last) for node in nodes)
    }


def _decorators(fn: ast.AST) -> list[str]:
    return [ast.unparse(d) for d in getattr(fn, "decorator_list", [])]


def methods(cls: ast.ClassDef) -> dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]]:
    """Every def in the class, by name, overload stubs kept before the door."""
    out: dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]] = {}
    for node in cls.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out.setdefault(node.name, []).append(node)
    return out


def forwarded(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """The call that reaches the sync door, one term per parameter kind."""
    parts = [a.arg for a in (*fn.args.posonlyargs, *fn.args.args) if a.arg != "self"]
    if fn.args.vararg:
        parts.append(f"*{fn.args.vararg.arg}")
    parts.extend(f"{a.arg}={a.arg}" for a in fn.args.kwonlyargs)
    if fn.args.kwarg:
        parts.append(f"**{fn.args.kwarg.arg}")
    return ", ".join(parts)


def _signature(fn: ast.FunctionDef, lines: list[str], name: str) -> list[str]:
    """Space's own signature source, or the divergent one with its reason."""
    if name in DIVERGENT:
        replacement, reason = DIVERGENT[name]
        returns = f" -> {ast.unparse(fn.returns)}" if fn.returns else ""
        wrapped = []
        words, row = reason.split(), "    #"
        for word in words:
            if len(row) + len(word) + 1 > WIDTH - 2:
                wrapped.append(row)
                row = "    #"
            row += f" {word}"
        wrapped.append(row)
        return [
            f"    # {name} DIVERGES from Space.{name}, because",
            *wrapped,
            f"    async def {name}({replacement}){returns}:",
        ]
    first = fn.body[0]
    source = lines[fn.lineno - 1 : first.lineno - 1]
    # The public async name can differ from the sync method's: one() and
    # first() reach Space._one and Space._first, so the def line is renamed
    # while the parameters stay Space's.
    head = source[0].lstrip().replace(f"def {fn.name}(", f"def {name}(", 1)
    return ["    async " + head, *source[1:]]


def door(fn: ast.FunctionDef, lines: list[str], name: str) -> list[str]:
    """One generated async door: Space's face, the worker's body."""
    out = _signature(fn, lines, name)
    first = fn.body[0]
    if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant):
        out.extend(lines[first.lineno - 1 : first.end_lineno])
    target = PRIVATE_TARGET.get(name, name)
    call = f"        return await self.call(lambda m: m.{target}({forwarded(fn)}))"
    if len(call) <= WIDTH:
        out.append(call)
    else:
        out.extend([
            "        return await self.call(",
            f"            lambda m: m.{target}({forwarded(fn)})",
            "        )",
        ])
        if len(out[-2]) > WIDTH:
            out[-3:] = [
                "        return await self.call(",
                f"            lambda m: m.{target}(",
                *[f"                {part}," for part in forwarded(fn).split(", ")],
                "            )",
                "        )",
            ]
    return out


def overloads(nodes: list[ast.FunctionDef], lines: list[str]) -> list[str]:
    """Space's @overload stubs, awaited. cast's ambient one-argument form is
    only reachable through them, so dropping them narrows the door.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose
    out: list[str] = []
    for node in nodes:
        if "overload" not in _decorators(node):
            continue
        source = lines[node.lineno - 1 : node.end_lineno]
        out.extend(["    @overload", "    async " + source[0].lstrip(), *source[1:]])
    return out


def block(
    space: ast.ClassDef, space_lines: list[str], asy: ast.ClassDef, lines: list[str]
) -> list[str]:
    """Every mirrored door, generated, in the sync surface's own order."""
    space_methods = methods(space)
    handwritten = _handwritten(asy, lines)
    out = [START, *HEADER.rstrip("\n").split("\n")[1:], ""]
    for name, nodes in space_methods.items():
        implementation = next(
            (n for n in nodes if "overload" not in _decorators(n)), None
        )
        public = PRIVATE_TARGET_INVERSE.get(name, name)
        if implementation is None or public.startswith("_"):
            continue
        if any(d in _decorators(implementation) for d in ("property", "staticmethod")):
            continue
        if public in EXCLUDED or public in handwritten:
            continue
        out.extend(overloads(nodes, space_lines))
        out.extend(door(implementation, space_lines, public))
        out.append("")
    out.append(END)
    return out


PRIVATE_TARGET_INVERSE = {target: name for name, target in PRIVATE_TARGET.items()}


def rendered(text: str, generated: list[str]) -> str:
    """aio.py with the marked region replaced."""
    lines = text.splitlines()
    try:
        start = lines.index(START)
        end = lines.index(END)
    except ValueError:
        msg = f"aio.py has no generated-mirror markers; add\n{START}\n{END}"
        raise SystemExit(msg) from None
    return "\n".join([*lines[:start], *generated, *lines[end + 1 :]]) + "\n"


def main(argv: list[str]) -> int:
    """Check the generated mirror, or rewrite it."""
    parser = argparse.ArgumentParser(description="generate AsyncMeTTa's mirror of Space")
    parser.add_argument("--write", action="store_true", help="rewrite the block")
    arguments = parser.parse_args(argv)

    space, space_lines = _class(SPACE, "Space")
    asy, aio_lines = _class(AIO, "AsyncMeTTa")
    text = AIO.read_text(encoding="utf-8")
    wanted = rendered(text, block(space, space_lines, asy, aio_lines))
    if wanted == text:
        print(f"the async mirror matches Space ({wanted.count('await self.call(lambda m:')} doors)")
        return 0
    if arguments.write:
        AIO.write_text(wanted, encoding="utf-8")
        print("rewrote aio.py's generated mirror")
        return 0
    print(
        "AsyncMeTTa's mirror no longer matches Space: run "
        "`python extensions/python/tools/aiogen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
