"""Purpose: generate the three mechanical mirrors of Space — AsyncMeTTa's,
the module tier's and the MeTTa context tier's — so no surface can drift from
the methods it delegates to. Sixty-six async methods were nothing but
`await self.call(lambda m: m.<name>(...))`, written by hand, and they HAD
drifted: measured 2026-08-31, fifteen carried a signature different from the
sync method's, sixteen weakened its return type, and sixty-four of sixty-six
paraphrased its docstring under a section comment claiming the synchronous
docstrings applied verbatim. Two of the fifteen were runtime refusals, not
annotations. Generation makes all three unrepresentable.

The approach is SQLAlchemy's, which solves this same problem for
AsyncConnection, AsyncEngine, AsyncSession and async_scoped_session: its
tools/generate_proxy_methods.py rewrites a marked region INSIDE the real file
rather than emitting a base class, so the methods stay where a reader and an IDE
find them [source:
https://github.com/sqlalchemy/sqlalchemy/blob/main/tools/generate_proxy_methods.py].

Assumes:
  - `Space` is the source of truth. The generator reads _space.py's AST, not a
    live class, so it needs no engine and can gate cheaply
  - a mirrored method is one AsyncMeTTa does not define itself. Hand-write a
    method and the generator stops emitting it, with no list to maintain
Guarantees:
  - every generated method carries Space's signature, return annotation and
    docstring VERBATIM, except the four in DIVERGENT which carry their stated
    reason beside them [tested:
    test_the_async_mirror_is_generated_from_the_sync_surface]
  - a new public Space method appears here or in EXCLUDED, so it cannot be
    silently absent from the async surface [tested: test_aio_mirrors_the_surface]
Fails when: a Space method's body must differ across the worker. Hand-write it in
  AsyncMeTTa and the generator yields to it.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None.
"""  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
REPO = TOOLS.parents[2]
sys.path.insert(0, str(TOOLS))

from aio_divergences import (  # noqa: E402
    CONTEXT_DUNDERS,
    DIVERGENT,
    EXCLUDED,
    INPLACE_DUNDERS,
    MODULE_DOORS,
    PRIVATE_TARGET,
)
from reference import spaced_default, split_top_level  # noqa: E402

SPACE = REPO / "extensions" / "python" / "metta" / "_space.py"
AIO = REPO / "extensions" / "python" / "metta" / "aio.py"
INIT = REPO / "extensions" / "python" / "metta" / "__init__.py"
START = "    # ---------------------------------------------- generated mirror"
END = "    # ------------------------------------------ end of generated mirror"
MODULE_START = "# ------------------------------------------------- generated module tier"
MODULE_END = "# ------------------------------------------ end of generated module tier"
WIDTH = 100

HEADER = """
    # Every method below is GENERATED by tools/aiogen.py from the synchronous
    # Space method of the same name, whose signature, return annotation and
    # docstring it carries verbatim. Each is one worker round trip. Do not
    # edit them here: change Space, or hand-write the method above this block
    # and the generator will yield to it. tools/aio_divergences.py holds the
    # exclusions and the one signature that cannot be Space's.
"""


def _class(path: Path, name: str) -> tuple[ast.ClassDef, list[str]]:
    text = path.read_text(encoding="utf-8")
    tree = ast.parse(text)
    found = next(n for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name == name)
    return found, text.splitlines()


def _handwritten(asy: ast.ClassDef, lines: list[str]) -> set[str]:
    """Methods defined OUTSIDE the generated block. Reading the whole class here
    would count the generator's own output as hand-written, and the second run
    would emit nothing.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose
    if START not in lines:
        return set(methods(asy))
    first, last = lines.index(START), lines.index(END)
    return {
        name
        for name, nodes in methods(asy).items()
        if any(not (first < node.lineno <= last) for node in nodes)
    }


def _decorators(fn: ast.AST) -> list[str]:
    return [ast.unparse(d) for d in getattr(fn, "decorator_list", [])]


def methods(cls: ast.ClassDef) -> dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]]:
    """Every def in the class, by name, overload stubs kept before the method."""
    out: dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]] = {}
    for node in cls.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out.setdefault(node.name, []).append(node)
    return out


def forwarded(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """The call that reaches the sync method, one term per parameter kind."""
    parts = [a.arg for a in (*fn.args.posonlyargs, *fn.args.args) if a.arg != "self"]
    if fn.args.vararg:
        parts.append(f"*{fn.args.vararg.arg}")
    parts.extend(f"{a.arg}={a.arg}" for a in fn.args.kwonlyargs)
    if fn.args.kwarg:
        parts.append(f"**{fn.args.kwarg.arg}")
    return ", ".join(parts)


def _signature(fn: ast.FunctionDef, lines: list[str], name: str) -> list[str]:
    """Space's own signature source, or the divergent one with its reason."""
    if name in DIVERGENT:
        replacement, reason = DIVERGENT[name]
        returns = f" -> {ast.unparse(fn.returns)}" if fn.returns else ""
        wrapped = []
        words, row = reason.split(), "    #"
        for word in words:
            if len(row) + len(word) + 1 > WIDTH - 2:
                wrapped.append(row)
                row = "    #"
            row += f" {word}"
        wrapped.append(row)
        return [
            f"    # {name} DIVERGES from Space.{name}, because",
            *wrapped,
            f"    async def {name}({replacement}){returns}:",
        ]
    first = fn.body[0]
    source = lines[fn.lineno - 1 : first.lineno - 1]
    # The public async name can differ from the sync method's: one() and
    # first() reach Space._one and Space._first, so the def line is renamed
    # while the parameters stay Space's.
    head = source[0].lstrip().replace(f"def {fn.name}(", f"def {name}(", 1)
    return ["    async " + head, *source[1:]]


def door(fn: ast.FunctionDef, lines: list[str], name: str) -> list[str]:
    """One generated async method: Space's interface, the worker's body."""
    out = _signature(fn, lines, name)
    first = fn.body[0]
    if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant):
        out.extend(lines[first.lineno - 1 : first.end_lineno])
    target = PRIVATE_TARGET.get(name, name)
    call = f"        return await self.call(lambda m: m.{target}({forwarded(fn)}))"
    if len(call) <= WIDTH:
        out.append(call)
    else:
        out.extend([
            "        return await self.call(",
            f"            lambda m: m.{target}({forwarded(fn)})",
            "        )",
        ])
        if len(out[-2]) > WIDTH:
            out[-3:] = [
                "        return await self.call(",
                f"            lambda m: m.{target}(",
                *[f"                {part}," for part in forwarded(fn).split(", ")],
                "            )",
                "        )",
            ]
    return out


def overloads(nodes: list[ast.FunctionDef], lines: list[str]) -> list[str]:
    """Space's @overload stubs, awaited. cast's ambient one-argument form is
    only reachable through them, so dropping them narrows the method.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose
    out: list[str] = []
    for node in nodes:
        if "overload" not in _decorators(node):
            continue
        source = lines[node.lineno - 1 : node.end_lineno]
        out.extend(["    @overload", "    async " + source[0].lstrip(), *source[1:]])
    return out


def block(
    space: ast.ClassDef, space_lines: list[str], asy: ast.ClassDef, lines: list[str]
) -> list[str]:
    """Every mirrored method, generated, in the sync surface's own order."""
    space_methods = methods(space)
    handwritten = _handwritten(asy, lines)
    out = [START, *HEADER.rstrip("\n").split("\n")[1:], ""]
    for name, nodes in space_methods.items():
        implementation = next(
            (n for n in nodes if "overload" not in _decorators(n)), None
        )
        public = PRIVATE_TARGET_INVERSE.get(name, name)
        if implementation is None or public.startswith("_"):
            continue
        if any(d in _decorators(implementation) for d in ("property", "staticmethod")):
            continue
        if public in EXCLUDED or public in handwritten:
            continue
        out.extend(overloads(nodes, space_lines))
        out.extend(door(implementation, space_lines, public))
        out.append("")
    out.append(END)
    return out


PRIVATE_TARGET_INVERSE = {target: name for name, target in PRIVATE_TARGET.items()}


MODULE_HEADER = """
# Every method below is GENERATED by tools/aiogen.py from the synchronous Space
# method it delegates to, whose signature, return annotation and docstring it
# carries, each with the tier note appended. Do not edit them here: change
# Space, or remove the method's row from MODULE_DOORS in tools/aio_divergences.py.
"""

#: The module keeps typing names out of `metta.<TAB>` by underscore-aliasing
#: its imports, so a copied annotation renames to the aliases the module
#: declares. Word-boundary replacement, and no parameter shares these names.
#: The heavy aliases live under TYPE_CHECKING on purpose: `import metta` stays
#: lazy, which the module buys by making `typing.get_type_hints` on a
#: generated method a NameError. Every reader in this repository walks the AST
#: instead, and a caller who needs live hints has Space's own methods, whose
#: annotations resolve.
MODULE_ALIASES = (
    ("Any", "_Any"),
    ("Callable", "_Callable"),
    ("Iterable", "_Iterable"),
    ("Literal", "_Literal"),
    ("ScopedExecution", "_ScopedExecution"),
    ("ScopedLimits", "_ScopedLimits"),
    ("EffectClass", "_EffectClass"),
    ("Defined", "_Defined"),
    ("PrologBacked", "_PrologBacked"),
    ("os", "_os"),
)

TIER_NOTE = "Runs against the default context's self space."


def _aliased(text: str) -> str:
    for name, alias in MODULE_ALIASES:
        text = re.sub(rf"\b{name}\b", alias, text)
    return text


def _module_signature(fn: ast.FunctionDef, name: str) -> list[str]:
    """The def line, Space's parameters and return, at module indentation."""
    returns = f" -> {_aliased(ast.unparse(fn.returns))}" if fn.returns else ""
    parts = [
        spaced_default(_aliased(part))
        for part in split_top_level(ast.unparse(fn.args))
        if part != "self"
    ]
    noqa = "  # noqa: A001 -- eval is the ruled public verb" if name == "eval" else ""
    exempt = (
        "    # policy-inventory-exempt: mechanism-internal; reason=mirrored "
        "from the Space method of the same name, whose adjacent exemption "
        "carries the reason; evidence=extensions/python/metta/ops.py:_operation_kind"
    )
    flat = f"def {name}({', '.join(parts)}){returns}:{noqa}"
    if len(flat) <= WIDTH and not any("Literal[" in part for part in parts):
        return [flat]
    body: list[str] = []
    for part in parts:
        if "Literal[" in part:
            body.append(exempt)
        body.append(f"    {part},")
    # A suppression binds to the line it ends, so a wrapped def carries it on
    # the first line, where the shadowing name is.
    return [f"def {name}({noqa.replace('  #', '  #', 1)}" if noqa else f"def {name}(",
            *body, f"){returns}:"]


def _module_docstring(fn: ast.FunctionDef, lines: list[str]) -> list[str]:
    """Space's docstring dedented a level, the tier note appended inside."""
    first = fn.body[0]
    if not (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)):
        return [f'    """{TIER_NOTE}"""']
    copied = [
        line.removeprefix("    ")
        for line in lines[first.lineno - 1 : first.end_lineno]
    ]
    if len(copied) == 1:
        head = copied[0].rstrip()
        closing = head[head.rindex('"""'):]
        return [head[: head.rindex('"""')].rstrip(), "", f"    {TIER_NOTE}", f'    {closing}']
    return [*copied[:-1], f"    {TIER_NOTE}", copied[-1]]


def _module_call(fn: ast.FunctionDef, target: str) -> list[str]:
    arguments = forwarded(fn)
    call = f"    return engine().self.{target}({arguments})"
    if len(call) <= WIDTH:
        return [call]
    return [
        f"    return engine().self.{target}(",
        f"        {arguments}",
        "    )",
    ]


def _module_overloads(nodes: list[ast.FunctionDef], name: str) -> list[str]:
    """Space's @overload stubs, self stripped, at module indentation. Without
    them the decorator forms of op and define lose the return types the
    overload family exists to give a checker.

    define's class row overlaps its callable row on purpose, because a class
    IS a callable and must still match the row that answers a class; module
    scope makes mypy say so where method scope does not, and the ignore
    acknowledges the choice rather than reordering it away.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose
    out: list[str] = []
    first = True
    for node in nodes:
        if "overload" not in _decorators(node):
            continue
        signature = _module_signature(node, name)
        signature[-1] = signature[-1] + " ..."
        if first and name == "define":
            signature[-1] += "  # type: ignore[overload-overlap]"
        first = False
        out.extend(("@_overload", *signature))
    return out


def module_block(space: ast.ClassDef, space_lines: list[str]) -> list[str]:
    """The module tier, generated in MODULE_DOORS order."""
    space_methods = methods(space)
    out = [MODULE_START, *MODULE_HEADER.rstrip("\n").split("\n")[1:], ""]
    for name, target in MODULE_DOORS:
        nodes = space_methods.get(target)
        if not nodes:
            msg = f"MODULE_DOORS names {target}, which Space no longer defines"
            raise SystemExit(msg)
        fn = next(n for n in nodes if "overload" not in _decorators(n))
        out.extend(_module_overloads(nodes, name))
        out.extend(_module_signature(fn, name))
        out.extend(_module_docstring(fn, space_lines))
        out.extend(_module_call(fn, target))
        out.extend(("", ""))
    while out and not out[-1]:
        out.pop()
    out.extend(("", "", MODULE_END))
    return out


METTA_START = "    # ---------------------------------------------- generated context tier"
METTA_END = "    # ------------------------------------------ end of generated context tier"

METTA_HEADER = """
    # Every method below is GENERATED by tools/aiogen.py from the synchronous
    # Space method it delegates to, whose signature, return annotation and
    # docstring it carries, each with the tier note appended. MeTTa held a
    # hand-written subset of these once, typed (*args: Any) -> Any, which
    # erased every overload a checker could use and silently missed methods
    # (a context that could define but not eval). Do not edit them here:
    # change Space, or remove the method's row from MODULE_DOORS in
    # tools/aio_divergences.py.
"""

METTA_TIER_NOTE = "Runs against this context's self space."


def _metta_docstring(fn: ast.FunctionDef, lines: list[str]) -> list[str]:
    """Space's docstring at method indentation, the tier note appended."""
    first = fn.body[0]
    if not (isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant)):
        return [f'        """{METTA_TIER_NOTE}"""']
    copied = lines[first.lineno - 1 : first.end_lineno]
    if len(copied) == 1:
        head = copied[0].rstrip()
        closing = head[head.rindex('"""') :]
        return [
            head[: head.rindex('"""')].rstrip(),
            "",
            f"        {METTA_TIER_NOTE}",
            f"        {closing}",
        ]
    return [*copied[:-1], f"        {METTA_TIER_NOTE}", copied[-1]]


def _metta_overloads(nodes: list[ast.FunctionDef], lines: list[str], name: str) -> list[str]:
    """Space's @overload stubs verbatim, renamed with the public method."""
    out: list[str] = []
    for node in nodes:
        if "overload" not in _decorators(node):
            continue
        source = lines[node.lineno - 1 : node.end_lineno]
        head = source[0].replace(f"def {node.name}(", f"def {name}(", 1)
        out.extend(["    @overload", head, *source[1:]])
    return out


def _metta_door(
    fn: ast.FunctionDef, lines: list[str], name: str, target: str, *, overloaded: bool
) -> list[str]:
    first = fn.body[0]
    source = lines[fn.lineno - 1 : first.lineno - 1]
    head = source[0].replace(f"def {fn.name}(", f"def {name}(", 1)
    out = [head, *source[1:]]
    out.extend(_metta_docstring(fn, lines))
    # An overloaded target cannot type-accept its own implementation
    # signature; the cast keeps the method's PUBLIC interface (the overload
    # stubs above) as the only typing surface, with no per-method ignore lists.
    receiver = 'cast("Any", self._self)' if overloaded else "self._self"
    call = f"        return {receiver}.{target}({forwarded(fn)})"
    if len(call) <= WIDTH or overloaded:
        out.append(call)
    else:
        out.extend(
            [
                "        return self._self." + target + "(",
                f"            {forwarded(fn)}",
                "        )",
            ]
        )
    return out


def _metta_dunder(fn: ast.FunctionDef, lines: list[str], name: str) -> list[str]:
    """One protocol face, delegated: Space's own signature, the context's return.

    The in-place operators rebind their left operand to the return value, so
    their bodies delegate and then `return self`; the read faces return the
    delegation directly. The signature and docstring come verbatim from
    Space, the same rule the named methods follow.
    """
    # The signature alone: a dunder without a docstring opens with comment
    # lines, and slicing to the first statement would copy that Space-side
    # narration into the context. Space's `type: ignore[override]` answers
    # ITS base-class variance and the context subclasses nothing, so copied
    # ignores are stripped rather than inherited as unused-ignore errors.
    signature: list[str] = []
    for line in lines[fn.lineno - 1 :]:
        signature.append(re.sub(r"\s*# type: ignore\[[^]]*\]", "", line))
        if line.split("#", 1)[0].rstrip().endswith(":"):
            break
    out = signature
    out.extend(_metta_docstring(fn, lines))
    arguments = forwarded(fn)
    if name in INPLACE_DUNDERS:
        out.append(f"        self._self.{name}({arguments})")
        out.append("        return self")
    else:
        out.append(f"        return self._self.{name}({arguments})")
    return out


def metta_block(
    space: ast.ClassDef,
    space_lines: list[str],
    context: ast.ClassDef,
    context_lines: list[str],
) -> list[str]:
    """The context tier, generated in MODULE_DOORS order, yielding to any
    method MeTTa hand-writes outside the marked region.
    """  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose
    space_methods = methods(space)
    if METTA_START in context_lines:
        first, last = (
            context_lines.index(METTA_START),
            context_lines.index(METTA_END),
        )
        handwritten = {
            name
            for name, nodes in methods(context).items()
            if any(not (first < node.lineno <= last) for node in nodes)
        }
    else:
        handwritten = set(methods(context))
    out = [METTA_START, *METTA_HEADER.rstrip("\n").split("\n")[1:], ""]
    for name, target in MODULE_DOORS:
        if name in handwritten:
            continue
        nodes = space_methods.get(target)
        if not nodes:
            msg = f"MODULE_DOORS names {target}, which Space no longer defines"
            raise SystemExit(msg)
        fn = next(n for n in nodes if "overload" not in _decorators(n))
        stubs = _metta_overloads(nodes, space_lines, name)
        out.extend(stubs)
        out.extend(
            _metta_door(fn, space_lines, name, target, overloaded=bool(stubs))
        )
        out.append("")
    for name in CONTEXT_DUNDERS:
        if name in handwritten:
            continue
        nodes = space_methods.get(name)
        if not nodes:
            msg = f"CONTEXT_DUNDERS names {name}, which Space no longer defines"
            raise SystemExit(msg)
        fn = next(n for n in nodes if "overload" not in _decorators(n))
        out.extend(_metta_dunder(fn, space_lines, name))
        out.append("")
    out.append(METTA_END)
    return out


def metta_rendered(text: str, generated: list[str]) -> str:
    """_space.py with MeTTa's marked region replaced."""
    lines = text.splitlines()
    try:
        start = lines.index(METTA_START)
        end = lines.index(METTA_END)
    except ValueError:
        msg = f"_space.py has no context-tier markers; add\n{METTA_START}\n{METTA_END}"
        raise SystemExit(msg) from None
    return "\n".join([*lines[:start], *generated, *lines[end + 1 :]]) + "\n"


def module_rendered(text: str, generated: list[str]) -> str:
    """__init__.py with its marked region replaced."""
    lines = text.splitlines()
    try:
        start = lines.index(MODULE_START)
        end = lines.index(MODULE_END)
    except ValueError:
        msg = f"__init__.py has no module-tier markers; add\n{MODULE_START}\n{MODULE_END}"
        raise SystemExit(msg) from None
    return "\n".join([*lines[:start], *generated, *lines[end + 1 :]]) + "\n"


def rendered(text: str, generated: list[str]) -> str:
    """aio.py with the marked region replaced."""
    lines = text.splitlines()
    try:
        start = lines.index(START)
        end = lines.index(END)
    except ValueError:
        msg = f"aio.py has no generated-mirror markers; add\n{START}\n{END}"
        raise SystemExit(msg) from None
    return "\n".join([*lines[:start], *generated, *lines[end + 1 :]]) + "\n"


def main(argv: list[str]) -> int:
    """Check the generated mirror, or rewrite it."""
    parser = argparse.ArgumentParser(description="generate AsyncMeTTa's mirror of Space")
    parser.add_argument("--write", action="store_true", help="rewrite the block")
    arguments = parser.parse_args(argv)

    space, space_lines = _class(SPACE, "Space")
    asy, aio_lines = _class(AIO, "AsyncMeTTa")
    context, context_lines = _class(SPACE, "MeTTa")
    stale = []
    for path, wanted in (
        (AIO, lambda text: rendered(text, block(space, space_lines, asy, aio_lines))),
        (INIT, lambda text: module_rendered(text, module_block(space, space_lines))),
        (
            SPACE,
            lambda text: metta_rendered(
                text, metta_block(space, space_lines, context, context_lines)
            ),
        ),
    ):
        text = path.read_text(encoding="utf-8")
        rewritten = wanted(text)
        if rewritten == text:
            continue
        if arguments.write:
            path.write_text(rewritten, encoding="utf-8")
            print(f"rewrote {path.name}'s generated mirror")
        else:
            stale.append(path.name)
    if not stale:
        if not arguments.write:
            print(f"all three mirrors match Space ({len(MODULE_DOORS)} module doors)")
        return 0
    print(
        f"{' and '.join(stale)} no longer match Space: run "
        "`python extensions/python/tools/aiogen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
