"""Purpose: compile and check the Python binding's service and seam interface.

Guarantees: declared Python signatures, native service kinds, supplied seam
kinds, loading audiences and generated projections are checked together
[tested: test_binding_crossing_mutations_refuse,
test_binding_provisions_keep_audience_and_kind; commit=8358dfc233bf299bb23eceddd94593a62372fe4b].
Controlled entry maps follow admitted native return signatures
[tested: test_binding_controlled_entries_derive_from_native_shapes,
test_binding_controlled_signature_mutations_refuse; commit=8358dfc233bf299bb23eceddd94593a62372fe4b].
Owns resources: the source reader subprocess completes before its output is read.
"""

from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import json
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from prologmacros import scoped_goal_expansions

ROOT = Path(__file__).resolve().parents[3]
SEAT = ROOT / "extensions/python"
sys.path.insert(0, str(SEAT))

from metta._binding import interface  # noqa: E402 -- inspect the checkout interface

BEGIN = "# begin generated binding callbacks"
END = "# end generated binding callbacks"
EXECUTION_BEGIN = "# begin generated controlled entries"
EXECUTION_END = "# end generated controlled entries"
CLOSED_SET = "# closed-set: generated; by=extensions/python/tools/bindinggen.py; lane=binding"
BINDING = Path("extensions/python/metta/_binding")
GENERATED = "% Generated by tools/bindinggen.py from the binding interface.\n"


def walk(term: Any):
    """Visit source nodes, retaining variables and zero-arity compounds."""
    yield term
    if isinstance(term, list):
        for argument in term[1:]:
            yield from walk(argument)


def compound(term: Any, name: str, arity: int | None = None) -> bool:
    """Whether a source node has the named functor and optional arity."""
    return (isinstance(term, list) and bool(term) and term[0] == name
            and (arity is None or len(term) == arity + 1))


def head_body(term: Any) -> tuple[Any, Any]:
    """Separate a clause from its executable body; declarations have no body."""
    if compound(term, ":-", 1):
        return None, None
    if compound(term, ":-", 2) or compound(term, "-->", 2):
        return term[1], term[2]
    return term, None


def indicator(head: Any) -> str:
    """Read an explicit predicate indicator or a clause head."""
    if compound(head, ":", 2):
        return f"{head[1]}:{indicator(head[2])}"
    if compound(head, "/", 2):
        return f"{head[1]}/{head[2]}"
    if isinstance(head, list) and head:
        return f"{head[0]}/{len(head) - 1}"
    return f"{head}/0"


def source_model(root: Path, paths: list[Path] | None = None) -> dict[Path, list[dict]]:
    """Read native terms with SWI's operator-aware source reader."""
    if paths is None:
        paths = [*sorted((root / BINDING).rglob("*.pl")), root / "engine/ext_points.pl"]
    process = subprocess.run(  # noqa: S603 -- a fixed reader receives source paths as literal argv
        ["swipl", "-q", "-s", str(ROOT / "extensions/python/tools/binding_source.pl"),  # noqa: S607 -- use the configured SWI executable on PATH
         "--", *(str(path.resolve()) for path in paths)],
        text=True, capture_output=True, check=False,
    )
    if process.returncode:
        message = f"binding source reader exited {process.returncode}: {process.stderr.strip()}"
        raise ValueError(message)
    return {Path(row["file"]): row["records"] for row in json.loads(process.stdout)}


def kinds(model: dict[Path, list[dict]], root: Path) -> dict[str, str]:
    """Read the engine's kind rows, rejecting conflicting declarations."""
    result = {}
    for record in model[root / "engine/ext_points.pl"]:
        term = record["term"]
        if compound(term, "kind", 2):
            name, kind = indicator(term[1]), term[2]
            if name in result and result[name] != kind:
                message = f"engine seam {name} has conflicting kinds"
                raise ValueError(message)
            result[name] = kind
    return result


def python_targets() -> dict[str, tuple[str, str]]:
    """Name every permitted static crossing and its defining implementation."""
    result = {f"metta_ops:{name}": target for name, target in interface.callbacks().items()}
    result.update({f"{module}:{name}": (module, name)
                   for module, names in interface.PYTHON_SERVICES.items() for name in names})
    return result


def module_source(root: Path, module: str) -> Path:
    """Locate a core module or its package initializer without importing it."""
    path = root / "extensions/python" / Path(*module.split("."))
    return path.with_suffix(".py") if path.with_suffix(".py").is_file() else path / "__init__.py"


def source_function(root: Path, module: str, name: str, seen: frozenset = frozenset()):
    """Follow a function's explicit source re-exports without loading satellites."""
    key = (module, name)
    if key in seen:
        message = f"service implementation import cycle at {module}:{name}"
        raise ValueError(message)
    path = module_source(root, module)
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == name:
            return node
        if isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if (alias.asname or alias.name) == name:
                    if node.level:
                        package = module if path.name == "__init__.py" else module.rpartition(".")[0]
                        target = importlib.util.resolve_name("." * node.level + (node.module or ""), package)
                    else:
                        target = node.module
                    return source_function(root, target, alias.name, seen | {key})
    message = f"service implementation {module}:{name} has no declared function"
    raise ValueError(message)


def accepts(root: Path, target: tuple[str, str], count: int) -> bool:
    """Check positional arity against Python source or a bound stdlib callable."""
    module, name = target
    if module.startswith("metta."):
        function = source_function(root, module, name)
        args = function.args
        minimum = len(args.posonlyargs) + len(args.args) - len(args.defaults)
        maximum = None if args.vararg else len(args.posonlyargs) + len(args.args)
        return minimum <= count and (maximum is None or count <= maximum) and all(
            default is not None for default in args.kw_defaults)
    qualified = f"{module}:{name}"
    if qualified in interface.C_SIGNATURES:
        return count in interface.C_SIGNATURES[qualified]
    value = importlib.import_module(module)
    for part in name.split("."):
        value = getattr(value, part)
    try:
        inspect.signature(value).bind(*([None] * count))
    except TypeError:
        return False
    return True


def substitutions(body: Any) -> dict[int, Any]:
    """Resolve single source assignments, leaving conditional choices dynamic."""
    candidates = defaultdict(list)
    for term in walk(body):
        if compound(term, "=", 2):
            for left, right in ((term[1], term[2]), (term[2], term[1])):
                if isinstance(left, dict) and "var" in left and right not in candidates[left["var"]]:
                    candidates[left["var"]].append(right)
    return {key: values[0] for key, values in candidates.items() if len(values) == 1}


def resolve(term: Any, bindings: dict[int, Any], seen: frozenset = frozenset()) -> Any:
    """Follow a source variable once per assignment edge."""
    if isinstance(term, dict) and "var" in term:
        variable = term["var"]
        if variable in bindings and variable not in seen:
            return resolve(bindings[variable], bindings, seen | {variable})
    return term


def call_shape(spec: Any, bindings: dict[int, Any]) -> tuple[str | None, str | None, int | None]:
    """Separate a Janus receiver, dotted member path and positional arity."""
    spec = resolve(spec, bindings)
    if not compound(spec, ":", 2):
        return None, None, None
    receiver, member = resolve(spec[1], bindings), resolve(spec[2], bindings)
    module = receiver if isinstance(receiver, str) else None
    parts = []
    while compound(member, ":", 2):
        if not isinstance(member[1], str):
            return module, None, None
        parts.append(member[1])
        member = resolve(member[2], bindings)
    if isinstance(member, list) and member:
        parts.append(member[0])
        count = len(member) - 1
    elif isinstance(member, str):
        parts.append(member)
        count = 0
    else:
        return module, None, None
    # Janus accepts importlib:util:f(...) as well as 'importlib.util':f(...).
    while module and parts and f"{module}.{parts[0]}" in interface.PYTHON_SERVICES:
        module += "." + parts.pop(0)
    return module, ".".join(parts), count


def crossing_findings(root: Path, model: dict[Path, list[dict]]) -> list[str]:
    """Check each direct crossing, callback term and host-wrapper invocation."""
    targets, problems = python_targets(), []
    for path, records in model.items():
        if path == root / "engine/ext_points.pl":
            continue
        for record in records:
            term = record["term"]
            if compound(term, "provides", 3) or compound(term, "provides_template", 4):
                term = term[-1]
            head, body = head_body(term)
            if head is None or body is None:
                continue
            owner = indicator(head)
            bindings = substitutions(body)
            checked = set()
            for node in walk(body):
                specs = []
                if compound(node, "py_call") or compound(node, "py_iter"):
                    permitted = (1, 2, 3) if node[0] == "py_call" else (2, 3)
                    if len(node) - 1 not in permitted:
                        problems.append(f"{path.relative_to(root)}:{owner}: invalid {node[0]} arity")
                        continue
                    specs.append((node[1], True))
                elif compound(node, "metta_py_call", 3):
                    specs.append(([":", "metta._binding.host", node[2]], True))
                elif compound(node, ":", 2) and node[1] == "metta_ops":
                    specs.append((node, False))
                for spec, capability in specs:
                    module, member, count = call_shape(spec, bindings)
                    key = (module, member, count, capability)
                    if key in checked:
                        continue
                    checked.add(key)
                    site = f"{path.relative_to(root)}:{owner}"
                    if module is not None and member is not None:
                        target = targets.get(f"{module}:{member}")
                        if target is None:
                            problems.append(f"{site}: undeclared Python service {module}:{member}/{count}")
                        elif not accepts(root, target, count):
                            problems.append(f"{site}: Python service {module}:{member} refuses arity {count}")
                    elif not capability or not any(
                        row.owner == owner and row.module == module
                        and (row.member is None or row.member == member)
                        and (row.arity is None or row.arity == count)
                        for row in interface.CAPABILITIES
                    ):
                        problems.append(f"{site}: undeclared dynamic Python crossing {key[:3]!r}")
    return sorted(set(problems))


def callback_projection() -> str:
    """Emit the facade's runtime table, static names and export list together."""
    rows = sorted(interface.callbacks().items())
    lines = [
        BEGIN,
        "# Generated by tools/bindinggen.py from interface.CALLBACK_GROUPS.",
        CLOSED_SET,
        "_CALLBACKS = {",
    ]
    lines += [f"    {name!r}: {target!r}," for name, target in rows]
    lines += ["}", "", *(f"{name}: _Any" for name, _ in rows), "", "__all__ = ["]
    lines += [f"    {name!r}," for name, _ in rows]
    return "\n".join([*lines, "]", END])


def controlled_projection(model: dict[Path, list[dict]]) -> str:
    """Derive held openers and resumptions from the admitted native signatures."""
    heads = [head_body(record["term"])[0] for records in model.values() for record in records]
    declared = {head[1] for head in heads if compound(head, "metta_py_wrappable", 1)
                and isinstance(head[1], str) and head[1].endswith("_controlled")}
    transports: dict[str, set[str]] = {name: set() for name in declared}
    for head in heads:
        if not isinstance(head, list) or not head or head[0] not in declared:
            continue
        output = head[-1]
        if compound(output, "prolog", 1):
            if len(head) < 3:
                message = f"controlled entry {indicator(head)}: missing opener policy input"
                raise ValueError(message)
            transport = "OPENERS"
        elif (compound(output, "[|]", 2) and compound(output[2], "[|]", 2)
              and output[2][2] == []):
            transport = "RESUMES"
        else:
            message = f"controlled entry {indicator(head)}: expected prolog/1 or [payload,text] output"
            raise ValueError(message)
        transports[head[0]].add(transport)
    for name, shapes in transports.items():
        if len(shapes) != 1:
            message = f"controlled entry {name}: missing or conflicting return signatures"
            raise ValueError(message)
    lines = [EXECUTION_BEGIN, "# Generated from metta_py_wrappable/1 and native controlled return signatures."]
    for transport in ("OPENERS", "RESUMES"):
        lines += [CLOSED_SET, f"_DEFERRED_EXECUTION_{transport} = {{"]
        lines += [f"    {json.dumps(name.removesuffix('_controlled'))}: {json.dumps(name)},"
                  for name, shapes in sorted(transports.items()) if transport in shapes]
        lines += ["}", ""]
    return "\n".join([*lines, EXECUTION_END])


def projections(root: Path, model: dict[Path, list[dict]]) -> dict[Path, str]:
    """Compile native imports and audience-specific seam clause projections."""
    engine_kinds = kinds(model, root)
    native = []
    for alias, target in sorted(interface.NATIVE_FORWARDS.items()):
        if engine_kinds.get(target) not in ("service", "host_service"):
            message = f"native forward {alias}: {target} is not an engine service"
            raise ValueError(message)
        name, arity = target.rsplit("/", 1)
        args = ", ".join(f"A{i}" for i in range(int(arity)))
        native.append(f"binding_forward_clause({alias}/{arity}, ({alias}({args}) :- {name}({args}))).")
    # SWI's sentinel-import expansion keeps each clause at its declaration site.
    # https://www.swi-prolog.org/pldoc/doc_for?object=term_expansion/2
    services = GENERATED + '''\
:- module(metta_python_services, [binding_forward_expansion/2]).
:- use_module(library(error), [domain_error/2]).

binding_forward_expansion(Indicator, Clause) :-
    ( binding_forward_clause(Indicator, Clause) -> true
    ; domain_error(binding_forward, Indicator) ).

:- multifile system:term_expansion/2.
system:term_expansion(binding_forward(Indicator), Clause) :-
    prolog_load_context(module, Module),
    Module \\== metta_python_services,
    predicate_property(Module:binding_forward_expansion(_, _), imported_from(metta_python_services)),
    binding_forward_expansion(Indicator, Clause).

''' + "\n".join(native) + "\n"
    outputs = {root / BINDING / "services.pl": services}
    for path, begin, end, projection in (
        (root / BINDING / "callbacks.py", BEGIN, END, callback_projection()),
        (root / "extensions/python/metta/_spaces/execution.py",
         EXECUTION_BEGIN, EXECUTION_END, controlled_projection(model)),
    ):
        original = path.read_text(encoding="utf-8")
        if (original.count(begin) != 1 or original.count(end) != 1
                or original.index(begin) >= original.index(end)):
            message = f"{path.name} needs one ordered {begin.removeprefix('# begin ')} region"
            raise ValueError(message)
        before, rest = original.split(begin)
        _, after = rest.split(end)
        outputs[path] = before + projection + after
    supplied = defaultdict(list)
    templates = []
    declarations = defaultdict(set)
    for path in sorted((root / BINDING / "provides").glob("*.pl")):
        text = path.read_text(encoding="utf-8")
        for record in model[path]:
            term = record["term"]
            if not any(compound(term, name, width) for name, width in
                       (("provides", 3), ("provides_template", 4), ("provides_declaration", 3))):
                message = f"{path.relative_to(root)}: unrecognised provision"
                raise ValueError(message)
            audience, module = term[1:3]
            if audience not in ("engine", "host") or not isinstance(module, str) or not module.isidentifier():
                message = f"{path.relative_to(root)}: invalid load audience or defining module"
                raise ValueError(message)
            clause = term[-1]
            head, _ = head_body(clause)
            if term[0] == "provides_declaration":
                head = [":", "seam", clause]
            if not compound(head, ":", 2) or head[1] != "seam":
                message = f"{path.relative_to(root)}: a provision must name a seam predicate"
                raise ValueError(message)
            name = indicator(head[2])
            if engine_kinds.get(name) != path.stem:
                message = f"{path.relative_to(root)}: {name} has engine kind {engine_kinds.get(name)!r}"
                raise ValueError(message)
            declarations[audience, module].add(name)
            start, end = record["arguments"][-1]
            raw = text[start:end]
            if raw.startswith("(") and raw.endswith(")"):
                raw = raw[1:-1].strip()
            if term[0] == "provides":
                supplied[audience, module].append(raw + ".")
            elif term[0] == "provides_template":
                if (audience, module) != ("host", "user"):
                    message = "dynamic hook templates currently require the host user namespace"
                    raise ValueError(message)
                templates.append(f"provided_template({term[3]}, ({raw})).")
    for audience, module in declarations.keys() | supplied.keys():
        clauses = [f":- multifile seam:{name}." for name in sorted(declarations[audience, module])]
        clauses += supplied[audience, module]
        outputs[root / BINDING / f"provides_{audience}_{module}.pl"] = GENERATED + "\n\n".join(clauses) + "\n"
    macros = scoped_goal_expansions('metta_python_source_macros', 'binding_source_expansion', (
        ('metta_py_wide_projection(Names)',
         'Names = [' + ', '.join('_' for _ in range(interface.QUERY_INDEX_CROSSOVER)) + '|_]', ''),
        ('metta_py_provided_clause(Name, Clause)', 'Clause = Template',
         '    ( atom(Name), provided_template(Name, Template) -> true\n'
         '    ; domain_error(binding_provided_clause, Name) )'),
    ))
    outputs[root / BINDING / "source_macros.pl"] = GENERATED + '''\
:- module(metta_python_source_macros, [binding_source_expansion/2]).
:- use_module(library(error), [domain_error/2]).

''' + macros + "\n" + "\n\n".join(templates) + "\n"
    return outputs


def findings(root: Path = ROOT) -> list[str]:
    """Check source contracts and refuse stale generated binding artifacts."""
    model = source_model(root)
    problems = crossing_findings(root, model)
    expected = projections(root, model)
    for path, content in expected.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            problems.append(f"binding projection drift: {path.relative_to(root)}")
    generated = set(expected)
    problems.extend(load_findings(root, model, generated))
    problems.extend(native_forward_findings(root, model, generated))
    for path in (root / BINDING).glob("*.pl"):
        if path.read_text(encoding="utf-8").startswith(GENERATED) and path not in generated:
            problems.append(f"obsolete binding projection: {path.relative_to(root)}")
    for path, records in model.items():
        if path in generated or path.parent.name == "provides" or path == root / "engine/ext_points.pl":
            continue
        for record in records:
            head, _ = head_body(record["term"])
            if compound(head, ":", 2) and head[1] == "seam":
                problems.append(f"{path.relative_to(root)}: supplied {indicator(head)} belongs in provides/<kind>.pl")
    return problems


def native_forward_findings(root: Path, model: dict[Path, list[dict]], generated: set[Path]) -> list[str]:
    """Require one declaration per import, retaining overloads and policy clauses."""
    declared = {f"{alias}/{target.rsplit('/', 1)[1]}": target.split('/')[0]
                for alias, target in interface.NATIVE_FORWARDS.items()}
    counts: Counter[str] = Counter()
    problems = []
    for path, records in model.items():
        if path in generated or path.parent.name == "provides" or path == root / "engine/ext_points.pl":
            continue
        for record in records:
            term = record["term"]
            if compound(term, "binding_forward", 1):
                name = indicator(term[1])
                counts[name] += 1
                if name not in declared:
                    problems.append(f"{path.relative_to(root)}: undeclared native forward {name}")
            head, body = head_body(term)
            name = indicator(head)
            if (name in declared and isinstance(head, list)
                    and all(isinstance(arg, dict) and "var" in arg for arg in head[1:])
                    and len({arg["var"] for arg in head[1:]}) == len(head) - 1
                    and body == [declared[name], *head[1:]]):
                problems.append(f"{path.relative_to(root)}: hand-written native forward {name}")
    problems.extend(f"native forward {name}: expected one declaration, found {counts[name]}"
                    for name in sorted(declared) if counts[name] != 1)
    return problems


def load_findings(root: Path, model: dict[Path, list[dict]], generated: set[Path]) -> list[str]:
    """Follow actual includes and modules from each declared load audience."""
    reached = defaultdict(set)

    def visit(path: Path, audience: str, module: str, seen: frozenset):
        if path not in model or (path, module) in seen:
            return
        records = model[path]
        for record in records:
            term = record["term"]
            if compound(term, ":-", 1) and compound(term[1], "module", 2):
                module = term[1][1]
        reached[path].add((audience, module))
        for record in records:
            term = record["term"]
            if not compound(term, ":-", 1):
                continue
            directive = term[1]
            if (isinstance(directive, list) and len(directive) >= 2
                    and directive[0] in ("include", "use_module", "ensure_loaded")
                    and isinstance(directive[1], str)):
                visit((path.parent / directive[1]).resolve(), audience, module, seen | {(path, module)})

    for audience, name in interface.LOAD_ENTRIES.items():
        visit(root / BINDING / name, audience, "user", frozenset())
    problems = []
    for path in sorted(generated):
        if path.name.startswith("provides_"):
            audience, module = path.stem.removeprefix("provides_").split("_", 1)
            actual = reached[path]
            if actual != {(audience, module)}:
                problems.append(f"binding load audience: {path.relative_to(root)}: "
                                f"expected {(audience, module)!r}, reached {sorted(actual)!r}")
    return problems


def main(argv: list[str] | None = None) -> int:
    """Check the binding, or regenerate its declared projections first."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args(argv)
    try:
        if arguments.write:
            for path, text in projections(ROOT, source_model(ROOT)).items():
                path.write_text(text, encoding="utf-8")
        problems = findings()
    except (OSError, ValueError, SyntaxError) as error:
        print(error)
        return 1
    for problem in problems:
        print(problem)
    if not problems:
        print("binding: service signatures, crossing capabilities, seam kinds and projections agree")
    return int(bool(problems))


if __name__ == "__main__":
    raise SystemExit(main())
