"""Purpose: derive configure parameters, setting documentation and the C seat's startup settings from descriptors.

Guarantees: every effective Setting appears in the exact configure signature
and its documented policy [tested:
test_setting_declaration_reaches_every_projection; commit=cd62330ceacc8f1254eed9791c3f6203b48a1c9e],
and every Setting naming the SWI flag it sets appears in
extensions/cmetta/settings.h with its default and environment input, where no
other Setting does [tested: test_setting_declaration_reaches_every_projection;
commit=WORKTREE].
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

ROOT = next(parent for parent in Path(__file__).resolve().parents if (parent / 'engine').is_dir() and (parent / 'lib').is_dir())
sys.path.insert(0, str(ROOT / "extensions/python"))

from metta._catalog.bounds import Config, settings  # noqa: E402  -- the tool runs from its checkout

BEGIN = "    # begin generated configure (tools/boundsgen.py; source=Setting declarations)"
END = "    # end generated configure"
DOC_BEGIN = "<!-- begin generated settings (extensions/python/tools/boundsgen.py; source=_catalog/bounds.py:Setting) -->"
DOC_END = "<!-- end generated settings -->"
C_MODULE = ROOT / "extensions/cmetta/settings.h"

#: The C header's fixed text: its contract and include guard. The blocks
#: between it and C_TAIL are one per Setting that names an SWI flag.
C_HEADER = """/* Purpose: the settings a program embedding the engine applies before the
 *   engine loads, as C constants, so the C seat boots under the bounds the
 *   Python seat declares rather than numbers of its own.
 * Assumes: each block below is one Setting in
 *   extensions/python/metta/_catalog/bounds.py that names the SWI flag it
 *   sets.
 * Guarantees:
 *   - this file is GENERATED by extensions/python/tools/boundsgen.py from
 *     those declarations, beside Config.configure's signature and the
 *     settings table in DEVELOPING.md; edit the declaration and rerun the
 *     tool with --write, never this file, and the tool's check fails on any
 *     drift [tested: test_each_declaration_projection_refuses_an_independent_edit;
 *     commit=WORKTREE]
 *   - for a setting <name>, MT_<NAME>_FLAG is the SWI flag it sets,
 *     MT_<NAME>_ENVIRONMENT the environment variable whose value replaces its
 *     default, present when the declaration names one, and MT_<NAME>_DEFAULT
 *     the default in the flag's own unit [tested:
 *     test_setting_declaration_reaches_every_projection; commit=WORKTREE]
 * Open Obligations: None.
 */
#ifndef CMETTA_SETTINGS_H
#define CMETTA_SETTINGS_H
"""

C_TAIL = "#endif\n"


def configure_source(owner: type = Config) -> str:
    """Emit real parameters so Python, help and type checkers read one shape."""
    names = settings(owner)
    lines = ["    def configure(", "        self,"]
    if names:
        lines.append("        *,")
    lines.extend(f"        {name}: int | _Unset = _UNSET," for name in names)
    lines.extend([
        "    ) -> None:",
        '        """Validate every supplied setting and replace its local or catalog value.',
        "",
        "        Live values use one engine transaction. An enclosing transaction",
        "        owns its commit; private configurations only change their own bag.",
        '        """',
        "        self._configure({",
        *(f'            "{name}": {name},' for name in names),
        "        })",
    ])
    return "\n".join(lines)


def documentation(owner: type = Config) -> str:
    """Render names, defaults and policy from the effective descriptors."""
    lines = [
        "| Setting | Default | Environment | Lifetime | Purpose |",
        "|---|---:|---|---|---|",
    ]
    for name, field in settings(owner).items():
        help_text = (field.__doc__ or "").replace("|", "&#124;").replace("\n", " ")
        lines.append(
            f"| `{name}` | {field.default} | {field.environment or ''} | "
            f"{'startup' if field.startup else 'catalog row'} | {help_text} |"
        )
    return "\n".join(lines)


def c_header(owner: type = Config) -> str:
    """Render each Setting that names an SWI flag as the C seat's constants."""
    blocks = []
    for name, field in settings(owner).items():
        if field.flag is None:
            continue
        prefix = "MT_" + name.upper()
        comment = textwrap.wrap(f"{name}: {field.__doc__}", width=74)
        lines = ["/* " + "\n   ".join(comment) + " */", f'#define {prefix}_FLAG "{field.flag}"']
        if field.environment:
            lines.append(f'#define {prefix}_ENVIRONMENT "{field.environment}"')
        lines.append(f"#define {prefix}_DEFAULT {field.default}ULL")
        blocks.append("\n".join(lines) + "\n")
    return C_HEADER + "".join("\n" + block for block in blocks) + "\n" + C_TAIL


def region(source: str, begin: str, end: str, value: str) -> str:
    """Replace one named generated region, refusing ambiguous ownership."""
    if source.count(begin) != 1 or source.count(end) != 1:
        msg = f"expected exactly one generated region: {begin}"
        raise ValueError(msg)
    head, remaining = source.split(begin)
    _, tail = remaining.split(end)
    return head + begin + "\n" + value + "\n" + end + tail


def projections(root: Path = ROOT) -> dict[Path, str]:
    """Read declarations once and derive each file's owned region."""
    bounds = root / "extensions/python/metta/_catalog/bounds.py"
    guide = root / "DEVELOPING.md"
    return {
        bounds: region(bounds.read_text(), BEGIN, END, configure_source()),
        guide: region(guide.read_text(), DOC_BEGIN, DOC_END, documentation()),
        root / C_MODULE.relative_to(ROOT): c_header(),
    }


def main(argv: list[str] | None = None) -> int:
    """Check every projection or write the forms declared by the descriptors."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, wanted in projections().items():
        if not path.exists() or path.read_text() != wanted:
            if args.write:
                path.write_text(wanted)
            else:
                stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("bounds-sync: stale projections: " + ", ".join(stale))
        return 1
    print(f"bounds-sync: {len(settings(Config))} setting declarations agree with every projection")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
