"""Purpose: gate defects while reporting every unordered Python door boundary.

Guarantees: the report and catalog call the same source analysis. Mixed,
recursive and undeclared open boundaries fail. Supplied parameter contracts
and their dependent doors stay unordered and remain visible
[tested: test_door_order_gate_refuses_each_boundary_defect,
test_declared_supplied_callable_is_unordered_by_contract,
test_composition_of_contract_open_door_is_unordered_by_dependency; commit=07976cf8b415390449863d803277b73102673b51].
The shipped verdict table metta/doors/_orders.py is a projection of this
analysis: --write regenerates it and a check refuses drift, so a boot reads
the table instead of analysing the tree [tested:
test_door_order_gate_refuses_a_stale_verdict_table,
test_verdict_table_round_trips_every_verdict; commit=38aa006aa9ecb1ce5366439fee69474623e37091].
The shipped invocation table metta/doors/_invocations.py names, from mypy's
typeshed, the standard-library parameters declared Callable, so the analysis
invokes a supplied callback exactly where the library declares it will and
never where a predicate merely inspects it [tested:
test_a_callable_passed_to_the_standard_library_is_invoked_where_typeshed_declares_it,
test_invocation_table_reads_versioned_stub_blocks; commit=2ef13993eeb63385a1aece70f37e72bef1cfd5ac].
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import sys
from collections import Counter
from collections.abc import Iterable, Mapping
from dataclasses import asdict
from graphlib import TopologicalSorter
from pathlib import Path

SEAT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SEAT))

import doorgen  # noqa: E402 -- the checkout source precedes an installed seat

from metta.doors._order import Order, Verdict, analyse, source_text  # noqa: E402
from metta.doors._scan import core_paths  # noqa: E402

TABLE = SEAT / "metta/doors/_orders.py"
INVOCATIONS = SEAT / "metta/doors/_invocations.py"
NOTICE = (
    "GENERATED by extensions/python/tools/doororder.py --write from\n"
    "extensions/python/metta/**/*.py and extensions/python/ext/metta-*/*.py: the\n"
    "door-order lane refuses drift. Edit the inputs and regenerate this file."
)
INVOCATIONS_NOTICE = (
    "GENERATED by extensions/python/tools/doororder.py --write from the stdlib\n"
    "stubs of mypy's typeshed: the door-order lane refuses drift. Upgrade mypy\n"
    "and regenerate this file."
)

Invocation = tuple[frozenset[int], frozenset[str]]


def _mentions_callable(node: ast.expr | None) -> bool:
    return node is not None and any(
        (isinstance(part, ast.Name) and part.id == "Callable")
        or (isinstance(part, ast.Attribute) and part.attr == "Callable")
        for part in ast.walk(node)
    )


def _stub_branches(node: ast.If) -> list[ast.stmt]:
    """The statements a stub's `if sys.version_info ...:` selects for this interpreter."""
    try:
        chosen = eval(compile(ast.Expression(node.test), "<stub>", "eval"), {"sys": sys})  # noqa: S307 -- a typeshed version guard, evaluated against the running interpreter
    except Exception:  # noqa: BLE001 -- an unreadable guard keeps both branches
        return [*node.body, *node.orelse]
    return list(node.body if chosen else node.orelse)


def _declared_invocations(statements: Iterable[ast.stmt], prefix: str, *, method: bool,
                          table: dict[str, Invocation]) -> None:
    for node in statements:
        if isinstance(node, ast.If):
            _declared_invocations(_stub_branches(node), prefix, method=method, table=table)
        elif isinstance(node, ast.ClassDef):
            _declared_invocations(node.body, prefix + node.name + ".", method=True, table=table)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            signature = node.args
            positional = [*signature.posonlyargs, *signature.args]
            if method and positional and positional[0].arg in {"self", "cls"}:
                positional = positional[1:]
            positions = frozenset(index for index, parameter in enumerate(positional)
                                  if _mentions_callable(parameter.annotation))
            names = frozenset(parameter.arg for parameter in (*signature.args, *signature.kwonlyargs)
                              if parameter.arg not in {"self", "cls"} and _mentions_callable(parameter.annotation))
            if not (positions or names):
                continue
            keys = [prefix + node.name]
            if method and node.name in {"__init__", "__new__"}:
                keys.append(prefix[:-1])
            for key in keys:
                previous = table.get(key, (frozenset(), frozenset()))
                table[key] = (previous[0] | positions, previous[1] | names)


def invocations() -> dict[str, Invocation]:
    """Every stdlib callable whose parameters typeshed declares Callable.

    Read from the stubs mypy ships, the same declarations the type checker
    verifies calls against, so which library operations invoke a supplied
    callback is derived rather than listed by hand. Positions count
    positional parameters after any receiver; names are the keyword-usable
    ones. A class's __init__ or __new__ is also recorded under the class.
    """
    import mypy  # noqa: PLC0415 -- the checks extra ships typeshed with the checker; a tool, not the core, names it

    base = Path(mypy.__file__).resolve().parent / "typeshed" / "stdlib"
    table: dict[str, Invocation] = {}
    for root, _directories, names in os.walk(base):
        for name in sorted(names):
            if not name.endswith(".pyi"):
                continue
            path = Path(root) / name
            module = str(path.relative_to(base).with_suffix("")).replace(os.sep, ".").removesuffix(".__init__")
            _declared_invocations(ast.parse(path.read_text(encoding="utf-8")).body, module + ".",
                                  method=False, table=table)
    return dict(sorted(table.items()))


def render_invocations(table: Mapping[str, Invocation]) -> str:
    """The invocation table as the Python module the analysis imports."""
    lines = [
        '"""Purpose: name the standard-library parameters typeshed declares Callable.',
        "",
        *INVOCATIONS_NOTICE.splitlines(),
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping",
        "from types import MappingProxyType",
        "",
        "# closed-set: generated; by=extensions/python/tools/doororder.py; lane=door-order",
        "INVOCATIONS: Mapping[str, tuple[frozenset[int], frozenset[str]]] = MappingProxyType({",
    ]
    for key in sorted(table):
        positions, names = table[key]
        lines.append(f"    {key!r}: (frozenset({sorted(positions)!r}), frozenset({sorted(names)!r})),")
    lines += ["})", ""]
    return "\n".join(lines)


def derived(root: Path = doorgen.ROOT) -> Mapping[str, Order]:
    """Analyse every declared door body in the actual source tree."""
    rows = doorgen.all_rows(root)
    paths = {module: path for path, module in core_paths(root / "extensions/python/metta")}
    for row in rows:
        if row.body:
            paths.setdefault(row.body.module, doorgen.module_path(row.body.module, root))
    return analyse(rows, source_text(paths))


def report(root: Path = doorgen.ROOT, orders: Mapping[str, Order] | None = None) -> dict:
    """Return every boundary and aggregate count for the actual source tree.

    A site string is listed once under "sites"; each row's native and open
    lists carry its indexes, since one unresolved value reaches hundreds of
    doors and the same text repeated per door made the report gigabytes.
    """
    orders = derived(root) if orders is None else orders
    sites = sorted({site for value in orders.values() for site in (*value.native, *value.open)})
    index = {site: position for position, site in enumerate(sites)}
    counts = Counter("unordered" if value.number is None else str(value.number) for value in orders.values())
    permitted = {name for name, value in orders.items() if value.number is not None}
    candidates = {name: value.blocked_by for name, value in orders.items()
                  if value.number is None and not (value.mixed or value.cycles or value.defect_open)}
    for name in TopologicalSorter(candidates).static_order():
        if name in candidates and candidates[name] <= permitted:
            permitted.add(name)
    return {
        "analysis": "Possible calls from a context-insensitive source graph. Declared caller-implemented contracts stay open; mixed crossings, recursion and other unresolved dispatch fail the gate. Every open call retains its owning source site.",
        "counts": dict(sorted(counts.items())),
        "first_order": sum(value.number == 1 for value in orders.values()),
        "mixed": [name for name, value in orders.items() if value.mixed],
        "open_dependencies": [name for name, value in orders.items() if value.open],
        "defect_open_dependencies": [name for name, value in orders.items() if value.defect_open],
        "unordered_by_contract": [name for name, value in orders.items()
                                  if name in permitted and value.number is None and value.contracts],
        "unordered_by_dependency": [name for name, value in orders.items()
                                    if name in permitted and value.number is None and not value.contracts],
        "recursive": [name for name, value in orders.items() if value.cycles],
        "sites": sites,
        "rows": {name: {**asdict(value),
                        "native": sorted(index[site] for site in value.native),
                        "open": sorted(index[site] for site in value.open),
                        "contracts": [asdict(call) for call in sorted(value.contracts,
                                      key=lambda call: (call.site, call.parameter, call.annotation))]}
                 for name, value in orders.items()},
    }


def render(verdicts: Mapping[str, Verdict]) -> str:
    """The verdict table as the Python module the running seat imports."""
    lines = [
        '"""Purpose: publish each shipped door\'s order verdict without analysing the tree at boot.',
        "",
        *NOTICE.splitlines(),
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping",
        "from types import MappingProxyType",
        "",
        "from metta.doors._order import Verdict",
        "",
        "# closed-set: generated; by=extensions/python/tools/doororder.py; lane=door-order",
        "VERDICTS: Mapping[str, Verdict] = MappingProxyType({",
    ]
    for key in sorted(verdicts):
        verdict = verdicts[key]
        reasons = "".join(f", {name}=True" for name in ("mixed", "open", "recursive", "dependency")
                          if getattr(verdict, name))
        lines.append(f"    {key!r}: Verdict({verdict.number!r}{reasons}),")
    lines += ["})", ""]
    return "\n".join(lines)


def drift(orders: Mapping[str, Order], table: Path | None = None, invocation_table: Path | None = None) -> str | None:
    """The finding when a shipped table is absent or differs from its derivation."""
    projections = (
        (TABLE if table is None else table, "verdict",
         lambda: render({name: value.verdict for name, value in orders.items()})),
        (INVOCATIONS if invocation_table is None else invocation_table, "invocation",
         lambda: render_invocations(invocations())),
    )
    for path, what, wanted in projections:
        if not path.is_file():
            return f"door-order: missing {what} table {path}; run {Path(__file__).name} --write"
        if path.read_text(encoding="utf-8") != wanted():
            return f"door-order: stale {what} table {path}; run {Path(__file__).name} --write"
    return None


def main(argv: list[str] | None = None) -> int:
    """Print every source-derived boundary and fail on unresolved findings or drift."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--write", action="store_true", help="regenerate the shipped verdict table")
    arguments = parser.parse_args(argv)
    if arguments.write:
        # The invocation table feeds the analysis, so it is written first.
        INVOCATIONS.write_text(render_invocations(invocations()), encoding="utf-8")
    orders = derived()
    if arguments.write:
        TABLE.write_text(render({name: value.verdict for name, value in orders.items()}), encoding="utf-8")
    result = report(orders=orders)
    result["stale"] = drift(orders)
    if arguments.json:
        print(json.dumps(result, default=sorted, sort_keys=True, indent=2))
    else:
        print("door-order GATE:", json.dumps({key: value for key, value in result.items() if key not in {"rows", "sites"}}))
        for name, row in result["rows"].items():
            print(name, json.dumps(row, default=sorted, sort_keys=True))
        for position, site in enumerate(result["sites"]):
            print("site", position, site)
        if result["stale"]:
            print(result["stale"])
    return int(bool(result["stale"]) or any(result[key] for key in ("mixed", "defect_open_dependencies", "recursive")))


if __name__ == "__main__":
    raise SystemExit(main())
