"""Purpose: generate the closed runtime fn namespace and its typed stub.
Assumes:
  - the project interpreter can import the local petta package and start the
    provisioned engine [tested: test_the_fn_namespace_is_generated;
    commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
Guarantees:
  - runtime names and explicit stub members come from the same fresh catalog
    snapshot and generation is deterministic [tested:
    test_the_fn_namespace_is_generated; commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
  - exact-only catalog spellings stay off the attribute surface instead of
    weakening static checks [tested:
    test_generated_aliases_keep_exact_only_spellings_on_the_bracket_door;
    commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None.
"""  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
RUNTIME = ROOT / "bindings" / "python" / "petta" / "_fn.py"
STUB = ROOT / "bindings" / "python" / "petta" / "_fn.pyi"

sys.path.insert(0, str(ROOT / "bindings" / "python"))
from petta._name_mapping import (  # noqa: E402  -- derive the source root before importing it
    generated_aliases,
)


def catalog_names() -> list[str]:
    """Read a fresh runtime's complete function and special-form catalog."""
    source = "import json\nfrom petta import MeTTa\nprint(json.dumps(MeTTa().self.builtins()))\n"
    environment = os.environ | {"PYTHONPATH": str(ROOT / "bindings" / "python")}
    completed = subprocess.run(  # noqa: S603  -- fixed interpreter and source, no untrusted input
        [sys.executable, "-c", source],
        cwd=ROOT,
        env=environment,
        capture_output=True,
        text=True,
        check=True,
    )
    names = json.loads(completed.stdout)
    if not isinstance(names, list) or not names or not all(isinstance(n, str) for n in names):
        msg = "the engine answered no valid function catalog"
        raise RuntimeError(msg)
    return sorted(set(names))


def runtime_text(names: list[str]) -> str:
    """Render the inert runtime namespace from one catalog snapshot."""
    rendered = "\n".join(f"        {json.dumps(name)}," for name in names)
    aliases = generated_aliases(names)
    rendered_aliases = "\n".join(
        f"        ({json.dumps(alias)}, {json.dumps(target)})," for alias, target in aliases.items()
    )
    return f'''"""Purpose: expose the generated static function-mention namespace.

GENERATED by bindings/python/tools/fngen.py from a fresh running engine's
function and special-form catalog. Edit the catalog and rerun with --write,
never edit this file directly.

Guarantees:
  - attribute access is closed over the generated catalog and exact bracket
    access never applies the Python spelling map [tested:
    test_the_fn_namespace_is_generated; commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None.
"""

from ._atom_namespace import _Namespace
from .atoms import Symbol

_NAMES = frozenset(
    {{
{rendered}
    }}
)

_ALIASES: dict[str, str] = {{}}
_ALIASES.update(
    (
{rendered_aliases}
    )
)

fn = _Namespace(
    Symbol,
    allowed=_NAMES,
    aliases=_ALIASES,
    label="target function",
)
'''


def stub_text(names: list[str]) -> str:
    """Render explicit members; no catch-all may erase typo checking.

    PEP 484 makes the colocated .pyi authoritative to type checkers, so the
    generated class lists every safe alias instead of advertising dynamic Any.
    [source: https://peps.python.org/pep-0484/#stub-files; commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
    """
    aliases = generated_aliases(names)
    members = "\n".join(
        f"    {alias}: Symbol"
        + ("  # noqa: N815" if alias[:1].islower() and alias != alias.lower() else "")
        for alias in aliases
    )
    return f"""# Purpose: declare every generated fn attribute to static type checkers.
# Guarantees:
#   - every safe runtime alias is explicit and no dynamic Any fallback exists
#     [tested: test_the_fn_namespace_is_generated; commit=6b77b811c44e1819ed9cd99f3809c0667f289e2e]
# Open Obligations:
#   To Do: None
#   Hacks: None
#   Future Enhancements: None.

from typing import Final

from .atoms import Symbol

class _FunctionNamespace:
{members}
    def __getitem__(self, name: str, /) -> Symbol: ...

fn: Final[_FunctionNamespace]
"""


def main(argv: list[str]) -> int:
    """Check generated outputs, or replace both together from one snapshot."""
    names = catalog_names()
    wanted = {RUNTIME: runtime_text(names), STUB: stub_text(names)}
    stale = [
        path
        for path, content in wanted.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if not stale:
        return 0
    if "--write" in argv:
        for path in stale:
            path.write_text(wanted[path], encoding="utf-8")
            print(f"rewrote {path.name}")
        return 0
    print(
        "petta's fn runtime/stub no longer match the running catalog: "
        "run `python bindings/python/tools/fngen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
