"""Purpose: generate the package stub and its callable-algebra type probe.

``metta.algebra`` is a module whose runtime class implements ``__call__``.
Mypy deliberately does not infer that mutation of a module object,
and a stub beside ``algebra.py`` cannot change the type of the package
attribute.  The package stub is therefore the one place that can state the
callable contract.  It mirrors the package source instead of replacing that
surface by hand, and it reads the carrier attributes from the catalog's
``semiring`` vocabulary.

Assumes:
  - ``metta/__init__.py`` remains the source of truth for package imports,
    functions, overloads, and ``__all__``
  - ``vocabgen.vocabularies`` returns the running catalog's declared order
Guarantees:
  - the checked-in root stub mirrors every package function signature and
    public imported name, while dynamic exports retain mypy's existing module
    or ``Any`` resolution [tested: init-stub; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
  - ``algebra`` is typed as a callable Protocol whose attributes are exactly
    the catalog's semiring members [tested: mypy-algebra-surface;
    commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
  - the generated consumer probe rejects either a non-callable module type or
    an ``Any`` return while checking every carrier attribute [tested:
    mypy-algebra-surface; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
  - typed algebra declarations retain DeclaredAlgebra results in both callable
    and decorator forms [tested: mypy-algebra-surface; commit=074dc0a88b1605c54824de677d586b6f60998bcf]
Fails when: a package callable needs a type contract that its implementation
  annotations do not express.  Add that deliberate refinement here, beside
  ``_algebra_protocol``, rather than silently weakening the whole root.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None.
"""

from __future__ import annotations

import argparse
import ast
import builtins
import copy
import sys
from collections import defaultdict
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parents[2]
SOURCE = ROOT / "extensions" / "python" / "metta" / "__init__.py"
STUB = SOURCE.with_suffix(".pyi")
TYPE_PROBE = ROOT / "extensions" / "python" / "tests" / "typing" / "algebra_surface.py"
WIDTH = 100

sys.path.insert(0, str(TOOLS))
from reference import spaced_default, split_top_level  # noqa: E402
from vocabgen import member_name, vocabularies  # noqa: E402

# Every name in the stub is COPIED from metta/__init__.py, so a lint about a
# name's choice cannot be actioned here: flake8-builtins fires on the shadowing
# def (eval) and parameter (filter) the source already justifies at its own
# site, and the remedy for either is to edit the source.  Suppressing the family
# once is what keeps the generator from needing a hand-kept list of the names
# ruff happens to object to today; RUF100 then holds the list to what actually
# fires, which is why A004 is absent while the root imports no carrier by name.
STUB_HEADER = '''# ruff: noqa: A001, A002, F822, I001 -- mirrored source names; dynamic exports; one source binding per import
# Purpose: declare the complete static surface of the ``metta`` package.
#
# GENERATED by extensions/python/tools/initstubgen.py from ``metta/__init__.py``
# and the catalog's ``semiring`` vocabulary.  Edit those authorities and rerun
# with ``--write``; the ``init-stub`` lane rejects drift.
#
# Guarantees:
#   - package functions, overloads, imported exports, and ``__all__`` mirror the
#     runtime root [tested: init-stub; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
#   - ``algebra`` is callable in both direct and decorator forms, returns
#     ``DeclaredAlgebra``, and exposes every catalog carrier as that type
#     [tested: mypy-algebra-surface; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
'''


PROBE_HEADER = '''"""Purpose: make the callable ``metta.algebra`` contract executable in mypy.

GENERATED by extensions/python/tools/initstubgen.py from the catalog's
``semiring`` vocabulary.  Edit that authority and rerun with ``--write``; do
not add carrier names here by hand.

Guarantees:
  - direct and decorator calls retain their precise result types
  - every catalog carrier resolves through ``metta.algebra`` as
    ``DeclaredAlgebra``, and through the package root as well for each carrier
    the root names in a TYPE_CHECKING import
  - representative function, namespace, and satellite-module exports retain
    the types the source package exposed before the stub existed.  These few
    types are written out rather than derived, so a source type that gains a
    parameter turns this lane red; the remedy is ``probe_text`` in the
    generator, never an edit here
  - an ``Any`` result makes the guarded assignment's ignore unused and fails
    under the repository's ``warn_unused_ignores`` policy
    [tested: mypy-algebra-surface; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]
"""
'''


def _public_names(tree: ast.Module) -> list[str]:
    """Read the literal package export list and reject an ambiguous source."""
    assignments = [
        node
        for node in tree.body
        if isinstance(node, ast.Assign)
        and any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets)
    ]
    if len(assignments) != 1:
        msg = "metta/__init__.py must contain exactly one literal __all__ assignment"
        raise SystemExit(msg)
    try:
        names = ast.literal_eval(assignments[0].value)
    except (TypeError, ValueError) as error:
        msg = "metta/__init__.py __all__ must be a literal list of names"
        raise SystemExit(msg) from error
    if (
        not isinstance(names, list)
        or not all(isinstance(name, str) and name.isidentifier() for name in names)
        or len(names) != len(set(names))
    ):
        msg = "metta/__init__.py __all__ must contain unique Python identifiers"
        raise SystemExit(msg)
    return names


def _is_overload(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(ast.unparse(decorator) == "_overload" for decorator in node.decorator_list)


def _function_groups(tree: ast.Module) -> list[list[ast.FunctionDef | ast.AsyncFunctionDef]]:
    """Top-level functions in source order, overload families kept together."""
    groups: dict[str, list[ast.FunctionDef | ast.AsyncFunctionDef]] = defaultdict(list)
    order: list[str] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name not in groups:
            order.append(node.name)
        groups[node.name].append(node)
    return [groups[name] for name in order]


def _stub_functions(tree: ast.Module) -> list[ast.FunctionDef | ast.AsyncFunctionDef]:
    """Select overload declarations, or the implementation when there are none."""
    selected: list[ast.FunctionDef | ast.AsyncFunctionDef] = []
    for group in _function_groups(tree):
        overloads = [node for node in group if _is_overload(node)]
        selected.extend(overloads or [group[-1]])
    return selected


def _signature_names(nodes: list[ast.FunctionDef | ast.AsyncFunctionDef]) -> set[str]:
    """Names needed to spell signatures without importing implementation bodies."""
    names: set[str] = set()
    for node in nodes:
        annotations = [
            argument.annotation
            for argument in (
                *node.args.posonlyargs,
                *node.args.args,
                *node.args.kwonlyargs,
                *((node.args.vararg,) if node.args.vararg else ()),
                *((node.args.kwarg,) if node.args.kwarg else ()),
            )
            if argument.annotation is not None
        ]
        if node.returns is not None:
            annotations.append(node.returns)
        annotations.extend(node.decorator_list)
        for annotation in annotations:
            names.update(
                child.id for child in ast.walk(annotation) if isinstance(child, ast.Name)
            )
    return names


def _source_imports(tree: ast.Module) -> list[ast.Import | ast.ImportFrom]:
    """Imports visible at the root, including its TYPE_CHECKING declarations."""
    imports: list[ast.Import | ast.ImportFrom] = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imports.append(node)
        elif isinstance(node, ast.If) and ast.unparse(node.test) == "TYPE_CHECKING":
            imports.extend(
                child for child in node.body if isinstance(child, (ast.Import, ast.ImportFrom))
            )
    return imports


def _binding(alias: ast.alias, *, imported: bool) -> str:
    if alias.asname:
        return alias.asname
    return alias.name.split(".", maxsplit=1)[0] if imported else alias.name


def _import_lines(
    tree: ast.Module,
    public: set[str],
    functions: list[ast.FunctionDef | ast.AsyncFunctionDef],
) -> list[str]:
    """Render only imports needed by a signature or a public re-export."""
    needed = _signature_names(functions) | public | {
        "_Any",
        "_Callable",
        "_DeclaredAlgebra",
        "_Iterable",
        "_Protocol",
        "_SemiringOrder",
        "_overload",
    }
    lines: set[str] = {
        "from typing import Protocol as _Protocol",
        "from .algebra import DeclaredAlgebra as _DeclaredAlgebra",
        "from .vocabularies import SemiringOrder as _SemiringOrder",
    }
    for node in _source_imports(tree):
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            continue
        for alias in node.names:
            bound = _binding(alias, imported=isinstance(node, ast.Import))
            if bound not in needed:
                continue
            if isinstance(node, ast.Import):
                rendered = f"import {alias.name}"
                if alias.asname:
                    rendered += f" as {alias.asname}"
            else:
                module = "." * node.level + (node.module or "")
                rendered = f"from {module} import {alias.name}"
                if alias.asname or bound in public:
                    rendered += f" as {bound}"
            lines.add(rendered)
    return sorted(lines, key=lambda line: (not line.startswith("import "), line))


def _carrier_names(rows: list[tuple[str, list[str]]]) -> list[str]:
    """Return the single semiring vocabulary as safe Python attributes."""
    matches = [values for name, values in rows if name == "semiring"]
    if len(matches) != 1 or not matches[0]:
        msg = "the catalog must expose exactly one non-empty (vocabulary semiring ...) row"
        raise SystemExit(msg)
    names = [member_name(value) for value in matches[0]]
    if len(names) != len(set(names)):
        msg = "semiring vocabulary values collide as Python carrier attributes"
        raise SystemExit(msg)
    return names


def _algebra_protocol(carriers: list[str]) -> str:
    attributes = "\n".join(f"    {name}: _DeclaredAlgebra" for name in carriers)
    parameters = """\
        *,
        plus: _Any = ...,
        times: _Any = ...,
        combine: _Any = ...,
        extend: _Any = ...,
        zero: _Any = ...,
        one: _Any = ...,
        laws: _Iterable[str] = ...,
        carrier: _Iterable[_Any] = ...,
        type: _Any = ...,
        requires: _Iterable[str] = ...,
        order: _SemiringOrder | None = ...,"""
    return f"""class _AlgebraModule(_Protocol):
{attributes}

    @_overload
    def __call__(
        self,
{parameters}
    ) -> _Callable[[type], _DeclaredAlgebra]: ...

    @_overload
    def __call__(
        self,
        subject: _Any,
{parameters}
    ) -> _DeclaredAlgebra: ...


algebra: _AlgebraModule
"""


def _export_sort_key(name: str) -> tuple[int, str]:
    """Match Ruff's constants, types, dunders, then lower-case export order."""
    if len(name) > 1 and name.isupper():
        return 0, name
    if name.startswith("__"):
        return 2, name
    if name[:1].isupper():
        return 1, name
    return 3, name


class _QualifyShadowedBuiltins(ast.NodeTransformer):
    """Keep source annotations meaningful when a public carrier has that name."""

    def __init__(self, shadowed: set[str]) -> None:
        self.shadowed = shadowed

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if node.id not in self.shadowed:
            return node
        return ast.copy_location(
            ast.Attribute(
                value=ast.Name(id="_builtins", ctx=ast.Load()),
                attr=node.id,
                ctx=node.ctx,
            ),
            node,
        )


def _qualified(node: ast.AST | None, shadowed: set[str]) -> ast.AST | None:
    if node is None:
        return None
    return _QualifyShadowedBuiltins(shadowed).visit(copy.deepcopy(node))


def _arguments(node: ast.FunctionDef | ast.AsyncFunctionDef, shadowed: set[str]) -> str:
    arguments = copy.deepcopy(node.args)
    for argument in (
        *arguments.posonlyargs,
        *arguments.args,
        *arguments.kwonlyargs,
        *((arguments.vararg,) if arguments.vararg else ()),
        *((arguments.kwarg,) if arguments.kwarg else ()),
    ):
        argument.annotation = _qualified(argument.annotation, shadowed)
    arguments.defaults = [ast.Constant(value=Ellipsis) for _ in arguments.defaults]
    arguments.kw_defaults = [
        None if default is None else ast.Constant(value=Ellipsis)
        for default in arguments.kw_defaults
    ]
    return ", ".join(
        spaced_default(part) for part in split_top_level(ast.unparse(arguments))
    )


def _render_function(
    node: ast.FunctionDef | ast.AsyncFunctionDef, shadowed: set[str]
) -> str:
    """Render one source signature as a stub declaration."""
    decorators = "\n".join(f"@{ast.unparse(item)}" for item in node.decorator_list)
    keyword = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    arguments = _arguments(node, shadowed)
    qualified_return = _qualified(node.returns, shadowed)
    returns = f" -> {ast.unparse(qualified_return)}" if qualified_return is not None else ""
    # The type-checker suppression is the stub's OWN, because the overlap it
    # silences is between two rendered overloads rather than a source name.
    # The prefix match rather than equality: the class overload took a type
    # PARAMETER when the class door started declaring its dataclass transform,
    # and `_builtins.type[_T]` overlaps the callable overload exactly as
    # `_builtins.type` did.
    opening_suffix = ""
    if (
        node.name == "define"
        and _is_overload(node)
        and node.args.posonlyargs
        and ast.unparse(node.args.posonlyargs[0].annotation).startswith("_builtins.type")
    ):
        opening_suffix = "  # type: ignore[overload-overlap]"

    flat = f"{keyword} {node.name}({arguments}){returns}: ..."
    if not opening_suffix and len(flat) <= WIDTH:
        declaration = flat
    else:
        parts = split_top_level(arguments)
        declaration = "\n".join(
            [
                f"{keyword} {node.name}({opening_suffix}",
                *(f"    {part}," for part in parts),
                f"){returns}: ...",
            ]
        )
    return f"{decorators}\n{declaration}" if decorators else declaration


def stub_text(source: str, carriers: list[str]) -> str:
    """Render the deterministic full root stub."""
    tree = ast.parse(source)
    public_names = _public_names(tree)
    public = set(public_names)
    functions = _stub_functions(tree)
    imports = _import_lines(tree, public, functions)
    exports = "\n".join(
        f'    "{name}",' for name in sorted(public_names, key=_export_sort_key)
    )
    shadowed = set(carriers) & set(vars(builtins))
    rendered_functions = "\n\n".join(
        _render_function(node, shadowed) for node in functions
    )
    return (
        STUB_HEADER
        + "\n"
        + "\n".join(imports)
        + "\n\n\n"
        + _algebra_protocol(carriers)
        + "\n__all__ = [\n"
        + exports
        + "\n]\n\n"
        + rendered_functions
        + "\n"
    )


def _root_carriers(tree: ast.Module, carriers: list[str]) -> set[str]:
    """The carriers the root names in a TYPE_CHECKING import, so a checker sees them.

    The root reaches every carrier at runtime through its lazy __getattr__, but
    it deliberately does not IMPORT the two that shadow builtins: binding `bool`
    at module scope would make every `bool` annotation in the file a variable
    annotation. Those two are therefore typed through ``metta.algebra`` only,
    and the probe asks exactly the question the source answers.
    """
    named: set[str] = set()
    for node in _source_imports(tree):
        if isinstance(node, ast.ImportFrom) and node.module == "algebra":
            named.update(alias.asname or alias.name for alias in node.names)
    return named & set(carriers)


def probe_text(carriers: list[str], rooted: set[str]) -> str:
    """Render the static consumer that exercises both calls and every carrier."""
    attributes = "\n".join(
        (
            f"assert_type(metta.algebra.{name}, DeclaredAlgebra)\n"
            f"assert_type(metta.{name}, DeclaredAlgebra)"
            if name in rooted
            else f"assert_type(metta.algebra.{name}, DeclaredAlgebra)"
        )
        for name in carriers
    )
    return f"""{PROBE_HEADER}
from collections.abc import Callable
from types import ModuleType
from typing import assert_type

import metta
from metta._atom_namespace import _Namespace
from metta._fn import _FunctionNamespace
from metta.algebra import DeclaredAlgebra
from metta.atoms import Atom, Symbol

assert_type(metta.S, _Namespace[Symbol])
assert_type(metta.fn, _FunctionNamespace)
assert_type(metta.convert, ModuleType)
assert_type(metta.forms("(x)"), list[Atom])
assert_type(metta.run("!(x)"), list[list[Atom]])
assert_type(metta.algebra(int), DeclaredAlgebra)
assert_type(metta.algebra(), Callable[[type], DeclaredAlgebra])
assert_type(
    metta.algebra(
        "typed-int-product", plus=max, times=lambda a, b: a * b,
        zero=0, one=1, type=int,
    ),
    DeclaredAlgebra,
)
assert_type(metta.algebra(type=int), Callable[[type], DeclaredAlgebra])
{attributes}

_not_an_integer: int = metta.algebra(int)  # type: ignore[assignment]
"""


def main(argv: list[str]) -> int:
    """Check both generated files, or rewrite them together when asked."""
    parser = argparse.ArgumentParser(description="generate metta's package typing surface")
    parser.add_argument("--write", action="store_true", help="rewrite generated files")
    arguments = parser.parse_args(argv)

    carriers = _carrier_names(vocabularies())
    source = SOURCE.read_text(encoding="utf-8")
    wanted = {
        STUB: stub_text(source, carriers),
        TYPE_PROBE: probe_text(carriers, _root_carriers(ast.parse(source), carriers)),
    }
    stale = [
        path
        for path, text in wanted.items()
        if not path.exists() or path.read_text(encoding="utf-8") != text
    ]
    if not stale:
        print(f"init-stub: package stub and {len(carriers)} carrier checks agree")
        return 0
    if arguments.write:
        for path in stale:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted[path], encoding="utf-8")
            print(f"rewrote {path.relative_to(ROOT)}")
        return 0
    names = " and ".join(str(path.relative_to(ROOT)) for path in stale)
    print(
        f"{names} no longer match the package and catalog: run "
        "`python extensions/python/tools/initstubgen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
