"""Purpose: generate the MeTTa-library reference as templates over a catalog query.

The page reads the `(@doc ...)` atoms the MeTTa libraries carry, the same
true-by-construction promise reference.py makes for the Python modules:
both languages' docs come from their own sources through one pipeline.
The coverage table is the burn-down surface, interrogate's role for the
MeTTa side: a library gains entries here by gaining @doc atoms.

The generator is in two halves and neither prints. `catalog()` is the QUERY: it
answers three `Rows` -- one coverage row per library, one row per `@doc` atom,
one row per name a library declares and does not document -- and no text at
all. Everything below `_PAGE` is TEMPLATE: the page's own words are template
literals, `{coverage:table}` renders the coverage rows as the Markdown table
this file used to assemble a cell at a time, and every heading, prose line and
parameter is a hole. A second page over the same rows is a second template
rather than a second generator.

Iteration stays in Python, where the language has it: a template holds one
level, so each row's section is rendered by its own call and the pieces are
joined, which is the composition `{parts:lines}` and a nested template do
inside one template.

Assumes:
  - the engine's own reader parses each MeTTa implementation; forms are READ
    and never run, while a Prolog-only implementation contributes an honest
    zero-documentation row rather than being parsed as MeTTa
    [tested: test_a_prolog_only_library_is_part_of_the_reference;
    commit=1bfad3db85807fff774cad370ff8e57f7400ae99]
Guarantees:
  - the checked-in page equals what this produces, gated on every run
    [tested test_the_metta_library_page_is_up_to_date]
  - the page is byte-identical to the one the hand-assembled generator wrote
    [measured 2026-09-07: sha256 ccff738354c74cffaca4dda113f5a8c63af85760ead048eac8ecb512cf98d2e8
    before and after the rewrite; command=sha256sum website/reference/metta-libraries.md;
    fixture=lib/ at this commit; commit=adb831d29a48596d3068a3087115b216c18b5b38]
  - the library roster comes from the runtime's shared `.metta`/`.pl` source
    discovery, with one row when a library has both halves
    [tested: test_metta_and_prolog_halves_share_one_library_row;
    commit=1bfad3db85807fff774cad370ff8e57f7400ae99]
  - `@doc` parts render in the order the atom writes them, so a library that
    puts `@return` before `@desc` reads as it was written
    [tested: test_a_doc_atom_renders_its_parts_in_written_order; commit=adb831d29a48596d3068a3087115b216c18b5b38]
Fails when:
  - a library defines names only through runnable `!(...)` side effects;
    the static reading cannot see those, so they go uncounted
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import pathlib
import sys

_REPO = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO / "extensions" / "python"))

from typing import Any  # noqa: E402

from metta import Expression, Symbol, parse, render  # noqa: E402
from metta._library import _library_source_files  # noqa: E402
from metta._source_forms import positioned_forms  # noqa: E402
from metta.results import Rows  # noqa: E402

_PAGE = _REPO / "website" / "reference" / "metta-libraries.md"

#: The whole page: prose, the coverage rows as a table, and the sections.
_TEMPLATE = """# The MeTTa libraries

`!(import! &self (library lib_x))` loads one. The entries below reproduce
each library's own `(@doc ...)` atoms, generated by
`extensions/python/tools/libdoc.py`, so they are true by construction; `help!` and
`get-doc` answer the same atoms live. The coverage table is the
burn-down surface: a library appears below it by gaining `@doc` atoms
beside its definitions.

{coverage:table}

{sections}"""

#: One library's heading, above its documented names.
_SECTION = """## {library}

"""

#: One `@doc` atom's heading: the name it documents and where it is written.
_ENTRY = """### `{name}`

*{where}*

"""

#: The declared type, when the library states one for that name.
_DECLARED = """```metta
(: {name} {type})
```

"""

#: `(@desc ...)`, and `(@return ...)`, each one paragraph of the entry.
_DESCRIPTION = """{text}

"""

_RETURNS = """Returns: {text}

"""

#: `(@params (...))`, numbered from one, one line each.
_PARAMETERS = """{parameters:lines}

"""

_PARAMETER = "{position}. {detail}"

#: The names a library declares and does not document: the burn-down list.
_GAPS = """Undocumented: {names}

"""

_COVERAGE_COLUMNS = ("library", "names", "documented")
_ENTRY_COLUMNS = ("library", "name", "where", "parts")
_GAP_COLUMNS = ("library", "name")


def _forms(source: str) -> list[tuple]:
    """Read every non-runnable form with its source line.

    This is the engine reader the boot manifest uses, which lets a library
    whose backend is absent still document itself.
    """
    return [
        (parse(form.text), form.line)
        for form in positioned_forms(source)
        if form.kind != "runnable"
    ]


def _named(atom) -> str | None:
    """The name a (= ...) or (: ...) form defines or declares."""
    if not isinstance(atom, Expression) or len(atom.children) < 3:
        return None
    head, subject = atom.children[0], atom.children[1]
    if head == Symbol("="):
        if isinstance(subject, Expression) and subject.children and isinstance(subject.children[0], Symbol):
            return subject.children[0].name
        if isinstance(subject, Symbol):
            return subject.name
    if head == Symbol(":") and isinstance(subject, Symbol):
        return subject.name
    return None


def _sources(root: pathlib.Path) -> dict[str, list[pathlib.Path]]:
    """Every discovered library implementation, by the name it is imported as."""
    sources: dict[str, list[pathlib.Path]] = {}
    for path in _library_source_files(root):
        sources.setdefault(path.stem, []).append(path)
    return sources


def _metta_source(name: str, paths: list[pathlib.Path]) -> pathlib.Path | None:
    """The one MeTTa half of a library, or None when it has only a Prolog one."""
    metta_sources = [path for path in paths if path.suffix == ".metta"]
    if len(metta_sources) > 1:
        joined = ", ".join(str(path) for path in metta_sources)
        message = f"{name} has multiple MeTTa documentation sources: {joined}"
        raise ValueError(message)
    return metta_sources[0] if metta_sources else None


def catalog(root: pathlib.Path) -> tuple[Rows, Rows, Rows]:
    """The library catalog as rows: coverage, documented entries, and gaps.

    The query half of this generator. It reads every library's source once and
    answers data, so the page below is a template over it: coverage counts one
    row per library, entries one row per `@doc` atom carrying that atom's parts
    in the order they were written, and gaps one row per declared name no
    `@doc` covers.
    """
    coverage: list[tuple[Any, ...]] = []
    entries: list[tuple[Any, ...]] = []
    gaps: list[tuple[Any, ...]] = []
    for name, paths in sorted(_sources(root).items()):
        library = Symbol(name)
        source = _metta_source(name, paths)
        if source is None:
            coverage.append((library, 0, 0))
            continue
        forms = _forms(source.read_text(encoding="utf-8"))
        docs = [
            (form, line)
            for form, line in forms
            if isinstance(form, Expression)
            and form.children
            and form.children[0] == Symbol("@doc")
            and len(form.children) > 1
        ]
        declared = {
            str(form.children[1]): form.children[2]
            for form, _line in forms
            if isinstance(form, Expression)
            and len(form.children) == 3
            and form.children[0] == Symbol(":")
            and isinstance(form.children[1], Symbol)
        }
        defined = {name for form, _line in forms if (name := _named(form)) is not None}
        documented = {str(doc.children[1]) for doc, _line in docs}
        entries += [
            (
                library,
                doc.children[1],
                f"{source.name}:{line}",
                (declared.get(str(doc.children[1])), doc.children[2:]),
            )
            for doc, line in docs
        ]
        if docs:
            gaps += [
                (library, Symbol(missing))
                for missing in sorted(defined - documented)
            ]
        coverage.append((library, len(defined | documented), len(documented)))
    return (
        Rows(_COVERAGE_COLUMNS, coverage),
        Rows(_ENTRY_COLUMNS, entries),
        Rows(_GAP_COLUMNS, gaps),
    )


def _entry(row) -> str:
    """One `@doc` atom as Markdown: its heading, then one block per part.

    The parts render in the order the atom writes them, and a part this page
    has no template for is skipped rather than guessed at.
    """
    type_atom, parts = row.parts
    text = render(_ENTRY, name=row.name, where=row.where)
    if type_atom is not None:
        text += render(_DECLARED, name=row.name, type=type_atom)
    for part in parts:
        if not (isinstance(part, Expression) and part.children):
            continue
        head, *rest = part.children
        if head == Symbol("@desc") and rest:
            text += render(_DESCRIPTION, text=rest[0])
        elif head == Symbol("@params") and rest and isinstance(rest[0], Expression):
            numbered = [
                render(
                    _PARAMETER,
                    position=position,
                    detail=parameter.children[1]
                    if (
                        isinstance(parameter, Expression)
                        and len(parameter.children) > 1
                    )
                    else parameter,
                )
                for position, parameter in enumerate(rest[0].children, start=1)
            ]
            if numbered:
                text += render(_PARAMETERS, parameters=numbered)
        elif head == Symbol("@return") and rest:
            text += render(_RETURNS, text=rest[0])
    return text


def sections(entries: Rows, gaps: Rows) -> str:
    """Every documented library's section, in the catalog's own order."""
    by_library = entries.group_by("library")
    missing = gaps.group_by("library")
    text = ""
    for library, rows in by_library.items():
        text += render(_SECTION, library=library)
        text += "".join(_entry(row) for row in rows)
        absent = missing.get(library)
        if absent:
            text += render(
                _GAPS, names=", ".join(f"`{row.name}`" for row in absent)
            )
    return text


def page() -> str:
    """Render the complete checked-in library reference page."""
    coverage, entries, gaps = catalog(_REPO)
    return (
        render(_TEMPLATE, coverage=coverage, sections=sections(entries, gaps)).rstrip()
        + "\n"
    )


def main(argv: list[str]) -> int:
    """Check the page, or regenerate it when ``--write`` is requested."""
    wanted = page()
    current = _PAGE.read_text(encoding="utf-8") if _PAGE.exists() else ""
    if current == wanted:
        return 0
    if "--write" in argv:
        _PAGE.write_text(wanted, encoding="utf-8")
        print(f"rewrote {_PAGE.name}")
        return 0
    print(
        f"{_PAGE.name} no longer matches the libraries' @doc atoms: "
        f"run extensions/python/tools/libdoc.py --write"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
