"""Purpose: generate the MeTTa-library reference from source documentation.

The page reads the `(@doc ...)` atoms the MeTTa libraries carry, the same
true-by-construction promise reference.py makes for the Python modules:
both languages' docs come from their own sources through one pipeline.
The coverage table is the burn-down surface, interrogate's role for the
MeTTa side: a library gains entries here by gaining @doc atoms.

Assumes:
  - the engine's own reader parses each MeTTa implementation; forms are READ
    and never run, while a Prolog-only implementation contributes an honest
    zero-documentation row rather than being parsed as MeTTa
    [tested: test_a_prolog_only_library_is_part_of_the_reference;
    commit=WORKTREE]
Guarantees:
  - the checked-in page equals what this produces, gated on every run
    [tested test_the_metta_library_page_is_up_to_date]
  - the library roster comes from the runtime's shared `.metta`/`.pl` source
    discovery, with one row when a library has both halves
    [tested: test_metta_and_prolog_halves_share_one_library_row;
    commit=WORKTREE]
Fails when:
  - a library defines names only through runnable `!(...)` side effects;
    the static reading cannot see those, so they go uncounted
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import pathlib
import sys

_REPO = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO / "extensions" / "python"))

from metta import Expression, Grounded, Symbol, parse  # noqa: E402
from metta._library import _library_source_files  # noqa: E402
from metta._source_forms import positioned_forms  # noqa: E402

_PAGE = _REPO / "website" / "reference" / "metta-libraries.md"

_PREAMBLE = """# The MeTTa libraries

`!(import! &self (library lib_x))` loads one. The entries below reproduce
each library's own `(@doc ...)` atoms, generated by
`extensions/python/tools/libdoc.py`, so they are true by construction; `help!` and
`get-doc` answer the same atoms live. The coverage table is the
burn-down surface: a library appears below it by gaining `@doc` atoms
beside its definitions."""


def _forms(source: str) -> list[tuple]:
    """Read every non-runnable form with its source line.

    This is the engine reader the boot manifest uses, which lets a library
    whose backend is absent still document itself.
    """
    return [
        (parse(form.text), form.line)
        for form in positioned_forms(source)
        if form.kind != "runnable"
    ]


def _named(atom) -> str | None:
    """The name a (= ...) or (: ...) form defines or declares."""
    if not isinstance(atom, Expression) or len(atom.children) < 3:
        return None
    head, subject = atom.children[0], atom.children[1]
    if head == Symbol("="):
        if isinstance(subject, Expression) and subject.children and isinstance(subject.children[0], Symbol):
            return subject.children[0].name
        if isinstance(subject, Symbol):
            return subject.name
    if head == Symbol(":") and isinstance(subject, Symbol):
        return subject.name
    return None


def _text(atom) -> str:
    """Render the prose inside a documentation part.

    A string value decodes; anything else renders as written.
    """
    if isinstance(atom, Grounded) and isinstance(atom.value, str):
        return atom.value
    return str(atom)


def _entry(doc: Expression, declared: dict[str, str], where: str) -> list[str]:
    """Render one ``@doc`` atom as Markdown.

    Include its heading, source line, declared type, description, parameters
    and return value, omitting parts that were not written.
    """
    name = doc.children[1]
    lines = [f"### `{name}`", "", f"*{where}*", ""]
    if str(name) in declared:
        lines += [f"```metta\n(: {name} {declared[str(name)]})\n```", ""]
    for part in doc.children[2:]:
        if not (isinstance(part, Expression) and part.children):
            continue
        head, *rest = part.children
        if head == Symbol("@desc") and rest:
            lines += [_text(rest[0]), ""]
        elif head == Symbol("@params") and rest and isinstance(rest[0], Expression):
            for position, parameter in enumerate(rest[0].children, start=1):
                detail = parameter.children[1] if (
                    isinstance(parameter, Expression) and len(parameter.children) > 1
                ) else parameter
                lines.append(f"{position}. {_text(detail)}")
            lines.append("")
        elif head == Symbol("@return") and rest:
            lines += [f"Returns: {_text(rest[0])}", ""]
    return lines


def _library(path: pathlib.Path) -> tuple[str, int, int, list[str]]:
    """One library's coverage numbers and rendered section."""
    forms = _forms(path.read_text(encoding="utf-8"))
    docs = [
        (f, line)
        for f, line in forms
        if isinstance(f, Expression) and f.children and f.children[0] == Symbol("@doc")
    ]
    declared = {
        str(f.children[1]): str(f.children[2])
        for f, _line in forms
        if isinstance(f, Expression) and len(f.children) == 3 and f.children[0] == Symbol(":")
        and isinstance(f.children[1], Symbol)
    }
    names = {name for form, _line in forms if (name := _named(form)) is not None}
    documented = {str(d.children[1]) for d, _line in docs if len(d.children) > 1}
    section: list[str] = []
    if docs:
        section = [f"## {path.stem}", ""]
        for doc, line in docs:
            section += _entry(doc, declared, f"{path.name}:{line}")
        missing = sorted(names - documented)
        if missing:
            section += [
                "Undocumented: " + ", ".join(f"`{name}`" for name in missing),
                "",
            ]
    return path.stem, len(names | documented), len(documented), section


def _libraries(root: pathlib.Path) -> list[tuple[str, int, int, list[str]]]:
    """One documentation row per discovered library implementation name."""
    sources: dict[str, list[pathlib.Path]] = {}
    for path in _library_source_files(root):
        sources.setdefault(path.stem, []).append(path)

    rows: list[tuple[str, int, int, list[str]]] = []
    for name, paths in sorted(sources.items()):
        metta_sources = [path for path in paths if path.suffix == ".metta"]
        if len(metta_sources) > 1:
            joined = ", ".join(str(path) for path in metta_sources)
            message = f"{name} has multiple MeTTa documentation sources: {joined}"
            raise ValueError(message)
        rows.append(_library(metta_sources[0]) if metta_sources else (name, 0, 0, []))
    return rows


def page() -> str:
    """Render the complete checked-in library reference page."""
    rows = _libraries(_REPO)
    table = ["| library | names | documented |", "|---|---|---|"]
    table += [f"| {name} | {total} | {done} |" for name, total, done, _ in rows]
    body: list[str] = []
    for _name, _total, _done, section in rows:
        body += section
    return "\n".join([_PREAMBLE, "", *table, "", *body]).rstrip() + "\n"


def main(argv: list[str]) -> int:
    """Check the page, or regenerate it when ``--write`` is requested."""
    wanted = page()
    current = _PAGE.read_text(encoding="utf-8") if _PAGE.exists() else ""
    if current == wanted:
        return 0
    if "--write" in argv:
        _PAGE.write_text(wanted, encoding="utf-8")
        print(f"rewrote {_PAGE.name}")
        return 0
    print(
        f"{_PAGE.name} no longer matches the libraries' @doc atoms: "
        f"run extensions/python/tools/libdoc.py --write"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
