"""Purpose: generate the MeTTa-library reference from source documentation.

The page reads the `(@doc ...)` atoms the MeTTa libraries carry, the same
true-by-construction promise reference.py makes for the Python modules:
both languages' docs come from their own sources through one pipeline.
The coverage table is the burn-down surface, interrogate's role for the
MeTTa side: a library gains entries here by gaining @doc atoms.

It renders `metta.library.rows`, the one query a library card renders too, so
a card and this page cannot disagree about what a library declares
[source: extensions/python/metta/library.py, rows].

Assumes:
  - the engine's own reader parses each MeTTa implementation; forms are READ
    and never run, while a Prolog-only implementation contributes a
    zero-documentation row rather than being parsed as MeTTa
    [tested: test_a_prolog_only_library_is_part_of_the_reference;
    commit=1bfad3db85807fff774cad370ff8e57f7400ae99]
Guarantees:
  - the checked-in page equals what this produces, gated on every run
    [tested test_the_metta_library_page_is_up_to_date]
  - the library roster comes from the runtime's shared `.metta`/`.pl` source
    discovery, with one row when a library has both halves
    [tested: test_metta_and_prolog_halves_share_one_library_row;
    commit=1bfad3db85807fff774cad370ff8e57f7400ae99]
  - a head published through a runnable registration form is counted and named
    among the undocumented, which is what left lib_memo reading as an empty
    library while nine of its heads were callable [tested:
    test_a_registered_head_is_counted_in_the_reference; commit=WORKTREE]
Fails when:
  - a library publishes names through a form whose name list is computed
    rather than written: the engine reports nothing for such a form, so those
    names go uncounted.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import pathlib
import sys

_REPO = pathlib.Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO / "extensions" / "python"))

from metta import Expression, Grounded, Symbol  # noqa: E402
from metta.library import roster, rows  # noqa: E402

_PAGE = _REPO / "website" / "reference" / "metta-libraries.md"

_PREAMBLE = """# The MeTTa libraries

`!(import! &self (library lib_x))` loads one. The entries below reproduce
each library's own `(@doc ...)` atoms, generated by
`extensions/python/tools/libdoc.py`, so they are true by construction; `help!` and
`get-doc` answer the same atoms live. The coverage table is the
burn-down surface: a library appears below it by gaining `@doc` atoms
beside its definitions."""


def _text(atom) -> str:
    """Render the prose inside a documentation part.

    A string value decodes; anything else renders as written.
    """
    if isinstance(atom, Grounded) and isinstance(atom.value, str):
        return atom.value
    return str(atom)


def _entry(row) -> list[str]:
    """Render one documented head as Markdown.

    Include its heading, source line, declared type, description, parameters
    and return value, omitting parts that were not written.
    """
    doc = row.documentation
    name = doc.children[1]
    at = row.documentation_origin or row.origin
    where = f"{pathlib.Path(at.file).name}:{at.line}" if at is not None else row.name
    lines = [f"### `{name}`", "", f"*{where}*", ""]
    if row.types:
        lines += [f"```metta\n(: {name} {row.types[-1]})\n```", ""]
    for part in doc.children[2:]:
        if not (isinstance(part, Expression) and part.children):
            continue
        head, *rest = part.children
        if head == Symbol("@desc") and rest:
            lines += [_text(rest[0]), ""]
        elif head == Symbol("@params") and rest and isinstance(rest[0], Expression):
            for position, parameter in enumerate(rest[0].children, start=1):
                detail = parameter.children[1] if (
                    isinstance(parameter, Expression) and len(parameter.children) > 1
                ) else parameter
                lines.append(f"{position}. {_text(detail)}")
            lines.append("")
        elif head == Symbol("@return") and rest:
            lines += [f"Returns: {_text(rest[0])}", ""]
    return lines


def _where(row) -> tuple[str, int]:
    """A documented head's own position, which is the page's reading order.

    The rows arrive in the order the library first MENTIONS each head, which
    for a registered head is the line of the form that registers it, so a
    library registering ten names in one form would order those ten by the
    list rather than by their documentation. A documentation page reads in the
    order its documentation was written.
    """
    at = row.documentation_origin or row.origin
    return ("", 0) if at is None else (at.file, at.line or 0)


def _library(name: str, root: pathlib.Path) -> tuple[str, int, int, list[str]]:
    """One library's coverage numbers and rendered section."""
    declared = rows(name, root=root)
    documented = sorted(
        (row for row in declared if row.documentation is not None), key=_where
    )
    section: list[str] = []
    if documented:
        section = [f"## {name}", ""]
        for row in documented:
            section += _entry(row)
        missing = sorted(
            row.name
            for row in declared
            if row.carried and row.documentation is None
        )
        if missing:
            section += [
                "Undocumented: " + ", ".join(f"`{head}`" for head in missing),
                "",
            ]
    return name, len(declared), len(documented), section


def page() -> str:
    """Render the complete checked-in library reference page."""
    # _REPO is read at call time, not bound at import: the page's own tests
    # generate it over a planted tree by rebinding it.
    rendered = [_library(name, _REPO) for name in roster(_REPO)]
    table = ["| library | names | documented |", "|---|---|---|"]
    table += [f"| {name} | {total} | {done} |" for name, total, done, _ in rendered]
    body: list[str] = []
    for _name, _total, _done, section in rendered:
        body += section
    return "\n".join([_PREAMBLE, "", *table, "", *body]).rstrip() + "\n"


def main(argv: list[str]) -> int:
    """Check the page, or regenerate it when ``--write`` is requested."""
    wanted = page()
    current = _PAGE.read_text(encoding="utf-8") if _PAGE.exists() else ""
    if current == wanted:
        return 0
    if "--write" in argv:
        _PAGE.write_text(wanted, encoding="utf-8")
        print(f"rewrote {_PAGE.name}")
        return 0
    print(
        f"{_PAGE.name} no longer matches the libraries' @doc atoms: "
        f"run extensions/python/tools/libdoc.py --write"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
