"""Purpose: generate extensions/python/metta/_refusals.py from the engine's own
(refusal ...) rows joined with this seat's spellings in tests/data/error-kinds.json,
so the class a refusal wears, the authority it stands on and the repair it names
all come from one table.

The engine declares one row per refusal kind: the seat-independent class name,
the `(ground ...)` the refusal stands on and the `(remedy ...)` template whose
`<field>` holes a raising site fills. `tests/data/error-kinds.json` adds what
the engine cannot know: which class THIS seat raises, and why where the two
differ. This tool is the join, written out as data so `metta.errors.refuse`
can build a refusal with no engine running, which is the whole reason it is a
generated file rather than a query.

What it does NOT generate is the exception CLASSES. The rows carry no class
hierarchy and no per-class prose, and five of the classes a row names are bare
subclasses whose docstrings say things a row cannot: `SourceNotFound`'s two
bases, `EngineError`'s janus `__cause__`, and the three `ResourceLimitError`
siblings that one `except` groups. Generating them would erase that and would
either drop the grouping or put a Python class hierarchy in the engine's
seat-independent taxonomy. So the classes stay hand-written and this lane holds
every one of them to its row instead: a kind whose class does not exist is a
finding, and a class this seat spells differently must carry its reason.

Assumes:
  - swipl is on PATH and engine/metta.pl consults from the repository root,
    which is how every generator lane already runs it
Guarantees:
  - the checked-in module equals what this produces, gated on every run
    [tested: tests/checks/check_refusal_sync_selftest.py; commit=WORKTREE]
  - every class a row names exists in metta.errors or in builtins, and a
    seat spelling that differs from the row's carries its reason
    [tested: tests/checks/check_refusal_sync_selftest.py; commit=WORKTREE]
  - output is deterministic: kinds in the catalog's own order
    [tested: extensions/python/tests/repository/test_refusal_rows.py::test_the_refusal_table_is_generated;
    commit=WORKTREE]
Fails when:
  - the engine answers no rows, a kind in the fixture has no row or the
    reverse, or a named class is nowhere to be found
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

from __future__ import annotations

import builtins
import inspect
import json
import pathlib
import subprocess
import sys
from typing import Any, NamedTuple

ROOT = pathlib.Path(__file__).resolve().parents[3]
MODULE = ROOT / "extensions" / "python" / "metta" / "_refusals.py"
KINDS = ROOT / "tests" / "data" / "error-kinds.json"

sys.path.insert(0, str(ROOT / "extensions" / "python"))

#: One engine process answers the whole table. The ground and remedy rows
#: cross as JSON, which is nested lists of atoms and strings, so the acts
#: arrive as the terms they are rather than as rendered text.
QUERY = (
    "consult('engine/metta.pl'), use_module(library(http/json)), "
    "findall(_{kind:K, class:C, ground:G, remedy:R}, "
    "        metta_host_refusal_row(K, C, G, R), Rows), "
    "json_write_dict(current_output, _{rows:Rows}, [width(0)])"
)

HEADER = '''"""Purpose: the refusal table: one row per kind, as data with no engine running.

GENERATED by extensions/python/tools/refusalgen.py from the engine's own
`(refusal ...)` rows in engine/spaces/catalog.pl joined with this seat's
spellings in tests/data/error-kinds.json. Edit those two and rerun with
--write, never this file; the `refusal-sync` gate lane fails when they drift.

`metta.errors.refuse(kind, message, **fields)` is the door that reads this: it
takes the class from the row, the ground from the row, and the remedy from the
row's template with the `<field>` holes filled from the fields the site passed.
The engine renders the same template for a ball it raises itself, through
`metta_host_refusal/6`; the two are held to each other by
extensions/python/tests/repository/test_refusal_rows.py.

This module imports nothing from the package on purpose. `metta.errors` is the
base layer and builds `Ground` and `Remedy` from these rows, so a row that
carried either object would be a cycle.

Guarantees:
  - every row here is the engine's own, in the catalog's order
    [tested: test_the_refusal_table_is_generated; commit=WORKTREE]
  - `cls` is the class THIS seat raises and `departure` says why when it is
    not the row's own name [tested: test_every_seat_raises_the_rows_class_or_says_why;
    commit=WORKTREE]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from collections.abc import Mapping
from types import MappingProxyType
from typing import Final, NamedTuple

#: One act of a remedy, as the term it is: the head, then each part, with a
#: nested tuple for a nested expression and `<name>` for a hole. `metta.errors`
#: turns one into `(edit (pragma! max-time 5))` once the holes are filled.
type Act = tuple["str | Act", ...]


class Refusal(NamedTuple):
    """One refusal kind, as every seat's own table needs it.

    `kind` is the engine's word, `cls` the class THIS seat raises for it and
    `declared` the seat-independent name the row gives; `departure` is why the
    two differ, or None when they agree. `origin` is the ball's shape --
    `signal` for the reserved control envelope, `term` for a ball whose functor
    names the refusal, `default` for the one kind nothing shaped, which is the
    taxonomy's catch-all. `fields` are the names this kind's refusal carries,
    which are both the remedy template's holes and the keywords `refuse()`
    passes to the class.
    """

    kind: str
    cls: str
    declared: str
    departure: str | None
    origin: str
    ground_kind: str
    citation: str
    title: str
    remedy_kind: str
    applicability: str
    acts: tuple[Act, ...]
    fields: tuple[str, ...]

'''


class Row(NamedTuple):
    """One joined row, before it is rendered."""

    kind: str
    cls: str
    declared: str
    departure: str | None
    origin: str
    ground_kind: str
    citation: str
    title: str
    remedy_kind: str
    applicability: str
    acts: tuple[Any, ...]
    fields: tuple[str, ...]


def engine_rows() -> list[dict[str, Any]]:
    """Ask the engine itself for its `(refusal ...)` rows."""
    completed = subprocess.run(  # noqa: S603  -- fixed argv, no untrusted input
        ["swipl", "-q", "-g", QUERY, "-t", "halt"],  # noqa: S607  -- PATH swipl, as every lane runs it
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=120,
        check=True,
    )
    payload = json.loads(completed.stdout)
    rows = payload["rows"]
    if not rows:
        msg = "the engine answered no (refusal ...) rows; the catalog presets failed to load"
        raise SystemExit(msg)
    return rows


def _term(part: Any) -> Any:
    """One JSON-carried Prolog term as the nested tuple this table stores."""
    if isinstance(part, list):
        return tuple(_term(inner) for inner in part)
    return str(part)


def join(rows: list[dict[str, Any]], seats: dict[str, Any]) -> list[Row]:
    """Join the engine's rows to this seat's spellings, refusing any gap."""
    engine_kinds = {row["kind"] for row in rows}
    listed = set(seats)
    if engine_kinds != listed:
        missing = ", ".join(sorted(engine_kinds - listed)) or "none"
        extra = ", ".join(sorted(listed - engine_kinds)) or "none"
        msg = (
            f"the (refusal ...) rows and tests/data/error-kinds.json name "
            f"different kinds; only in the rows: {missing}; only in the "
            f"fixture: {extra}"
        )
        raise SystemExit(msg)
    joined: list[Row] = []
    for row in rows:
        kind = row["kind"]
        seat = seats[kind]["python"]
        declared = row["class"]
        spelled = seat["error"]
        if spelled is None:
            msg = (
                f"the {kind} kind has no Python class; every kind the engine "
                f"declares is raised by name on this seat"
            )
            raise SystemExit(msg)
        departure = seat.get("why") if spelled != declared else None
        if spelled != declared and not departure:
            msg = (
                f"the {kind} row names {declared} and this seat raises "
                f"{spelled} with no reason; add a `why` to error-kinds.json"
            )
            raise SystemExit(msg)
        _, ground_kind, citation = row["ground"]
        _, title, remedy_kind, applicability, *acts = row["remedy"]
        joined.append(
            Row(
                kind=kind,
                cls=spelled,
                declared=declared,
                departure=departure,
                origin=seats[kind]["origin"],
                ground_kind=ground_kind,
                citation=citation,
                title=title,
                remedy_kind=remedy_kind,
                applicability=applicability,
                acts=tuple(_term(act) for act in acts),
                fields=tuple(seats[kind]["fields"]),
            )
        )
    return joined


def class_findings(joined: list[Row]) -> list[str]:
    """Where a class a row names is absent, or does not take its own fields.

    The second half is what lets both `metta.errors.refuse` and the crossing
    hand a class the kind's declared fields without asking whether it accepts
    them: a stack overflow carries its ceiling and a missing source its path,
    and the class that will not take the field is a finding here rather than a
    TypeError at the moment something already went wrong.
    """
    from metta import errors  # noqa: PLC0415  -- the package under test, on the path above

    findings: list[str] = []
    for row in joined:
        found = getattr(errors, row.cls, None) or getattr(builtins, row.cls, None)
        if found is None:
            findings.append(
                f"the {row.kind} row names {row.cls}, which is neither in "
                f"metta.errors nor a builtin"
            )
            continue
        if not (isinstance(found, type) and issubclass(found, BaseException)):
            findings.append(f"{row.cls}, named by the {row.kind} row, is not an exception")
            continue
        findings.extend(_field_findings(row, found))
    return findings


def _field_findings(row: Row, held: type) -> list[str]:
    """Where a class does not take a field its kind declares."""
    if not row.fields:
        return []
    parameters = inspect.signature(held.__init__).parameters
    variadic = any(
        parameter.kind is inspect.Parameter.VAR_KEYWORD
        for parameter in parameters.values()
    )
    return [
        f"the {row.kind} refusal carries {name}, which {row.cls} does not take"
        for name in row.fields
        if name not in parameters and not variadic
    ]


def module_text(joined: list[Row]) -> str:
    """Render one deterministic generated refusal table."""
    body = [HEADER, "\n#: Every refusal kind, in the catalog's own order.\n"]
    body.append("REFUSALS: Final[Mapping[str, Refusal]] = MappingProxyType({\n")
    for row in joined:
        body.append(f"    {row.kind!r}: Refusal(\n")
        body.extend(f"        {name}={getattr(row, name)!r},\n" for name in Row._fields)
        body.append("    ),\n")
    body.append("})\n")
    return "".join(body)


def main(argv: list[str]) -> int:
    """Write the module with --write, or report the drift and every finding."""
    write = "--write" in argv
    seats = json.loads(KINDS.read_text(encoding="utf-8"))["kinds"]
    joined = join(engine_rows(), seats)
    text = module_text(joined)
    if write:
        MODULE.write_text(text, encoding="utf-8")
        print(f"refusal table: wrote {len(joined)} row(s) to {MODULE.relative_to(ROOT)}")
        return 0
    findings = class_findings(joined)
    current = MODULE.read_text(encoding="utf-8") if MODULE.is_file() else ""
    if current != text:
        findings.append(
            f"{MODULE.relative_to(ROOT)} is not what the rows produce; rerun "
            f"`python extensions/python/tools/refusalgen.py --write`"
        )
    for finding in findings:
        print(finding)
    print(f"refusal table: {len(joined)} row(s), {len(findings)} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
