"""Purpose: generate website/reference/refusals.md from the engine's own (refusal ...) rows.

The refusal taxonomy is catalog data: one row per kind, carrying the class
name a seat raises, the authority the refusal stands on and the repair as a
template. This page is that table rendered, so the documentation of an error
cannot say something the engine does not, and a kind added to the catalog
reaches the site by running this rather than by being remembered.

That shape is rustc's error index, which is generated from the same list the
compiler emits codes from, and PostgreSQL's errcodes.txt, which generates its
C, PL/pgSQL and documentation spellings from one row list
[source: https://doc.rust-lang.org/error-index.html].

Assumes:
  - swipl is on PATH and engine/metta.pl consults from the repository root,
    which is how vocabgen.py already reads the same catalog
  - tests/data/error-kinds.json names each seat's own class, which the engine
    cannot know [source: tests/data/error-kinds.json, its "//" block]
Guarantees:
  - the checked-in page equals what this produces, gated on every run
    [tested: refusals lane in check.sh; commit=f33b7ab0200e6dc74c88fb4c7f827bf545a447ed]
  - a kind whose row and fixture entry disagree about existing is a finding
    rather than a missing section
    [tested: test_the_refusals_page_is_generated; commit=f33b7ab0200e6dc74c88fb4c7f827bf545a447ed]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
PAGE = ROOT / "website" / "reference" / "refusals.md"
FIXTURE = ROOT / "tests" / "data" / "error-kinds.json"

#: One line per row, tab separated, because a citation carries commas and
#: parentheses and a remedy title carries both. The acts are rendered by the
#: engine's own writer, so the page shows the MeTTa a reader would write.
ROWS_QUERY = (
    "consult('engine/metta.pl'), "
    "forall(metta_host_refusal_row(K, C, [ground, A, Cite], "
    "                              [remedy, T, RK, Ap|Acts]), "
    "       ( maplist(sdisplay, Acts, Rendered), "
    "         atomic_list_concat(Rendered, ' ', ActsText), "
    "         metta_host_error_kind_row(K, Origin, Fields), "
    "         atomic_list_concat(Fields, ' ', FieldText), "
    "         format('~w\\t~w\\t~w\\t~w\\t~w\\t~w\\t~w\\t~w\\t~w~n', "
    "                [K, C, Origin, FieldText, A, Cite, T, RK, Ap]), "
    "         format('~w~n', [ActsText]) ))"
)

HEADER = """# Refusals

Every refusal the engine raises on purpose has a ROW in the `&metta` catalog,
and this page is those rows. A row says four things: the kind word the engine
classifies a raised ball into, the class name a seat raises for it, the
authority the refusal stands on, and the repair.

GENERATED by `extensions/python/tools/refusalsdoc.py` from the running
engine's own rows; edit the declarations in `engine/spaces/catalog.pl` and
rerun it with `--write`, never this page.

Ask the same question yourself, since a row is ordinary data:

```metta
!(match &metta (refusal $kind $class $ground $remedy) ($kind $class))
```

A HOST reads the row at the crossing rather than building a table of its own.
In Python every engine refusal carries `.ground` and `.remedy`; in TypeScript
the same two ride on `MettaError`; in C they are `mt_ground()` and
`mt_remedy()` beside `mt_errmsg()`. The remedy's `<field>` holes are filled
from the refusal that was actually raised, so a tripped bound reads `raise the
bound past 0.05 seconds`. A hole left over is one the engine has no opinion
about, which is what keeps that remedy `prose`. A hole is written here as
code, `` `<limit>` ``, and is a plain word in the rendered sentence.

Each seat spells a class its own way where its own language already owns the
word; `tests/data/error-kinds.json` records what it spells and why.

"""


def rows(root: pathlib.Path) -> list[dict[str, str]]:
    """Every (refusal ...) row, read from a running engine."""
    answered = subprocess.run(  # noqa: S603  -- fixed argv, no untrusted input
        ["swipl", "-q", "-g", ROWS_QUERY, "-t", "halt"],  # noqa: S607  -- PATH swipl, as every lane runs it
        cwd=root, capture_output=True, text=True, timeout=280, check=True,
    ).stdout.splitlines()
    read = []
    for head, acts in zip(answered[0::2], answered[1::2], strict=True):
        kind, klass, origin, fields, authority, citation, title, remedy, level = head.split("\t")
        read.append(
            {
                "kind": kind,
                "class": klass,
                "origin": origin,
                "fields": fields,
                "authority": authority,
                "citation": citation,
                "title": title,
                "remedy": remedy,
                "applicability": level,
                "acts": acts,
            }
        )
    return read


def summary(read: list[dict[str, str]], seats: dict[str, dict]) -> list[str]:
    """One line per kind: the row's class beside what each seat raises."""
    lines = [
        "## The kinds",
        "",
        "| kind | class | Python | TypeScript | fields |",
        "|---|---|---|---|---|",
    ]
    for row in read:
        seat = seats[row["kind"]]
        python = seat["python"]["error"] or "*not classified here*"
        node = seat["node"]["error"] or "*not classified here*"
        fields = " ".join(f"`{name}`" for name in row["fields"].split()) or "none"
        lines.append(
            f"| `{row['kind']}` | `{row['class']}` | "
            f"{python if python.startswith('*') else f'`{python}`'} | "
            f"{node if node.startswith('*') else f'`{node}`'} | {fields} |"
        )
    return [*lines, ""]


#: VitePress compiles markdown through Vue, which reads a bare `<line>` as a
#: custom element rather than as prose. A hole is code anyway: it is the name
#: of a field the renderer fills.
HOLE = re.compile(r"<([a-z][a-z_-]*)>")


def spelled(text: str) -> str:
    """One remedy title with its holes written as code."""
    return HOLE.sub(r"`<\1>`", text)


def entry(row: dict[str, str], seat: dict) -> list[str]:
    """One kind's own section: what it is, what says so and what to do."""
    origin = {
        "signal": "the reserved control envelope",
        "term": "a ball whose own shape names the refusal",
        "default": "a ball this engine did not shape",
    }[row["origin"]]
    lines = [
        f"### `{row['kind']}`",
        "",
        f"Raised as `{row['class']}`, off {origin}.",
        "",
        f"**Ground.** {row['authority']}: {row['citation']}",
        "",
        f"**Remedy.** {spelled(row['title'])}",
        "",
        f"An LSP `{row['remedy']}` at rustc's `{row['applicability']}`"
        + (f", whose act is `{row['acts']}`." if row["acts"] else ", with no act: the repair is a decision."),
        "",
    ]
    departures = [
        (name, seat[name]["error"], seat[name].get("why") or seat[name].get("note"))
        for name in ("python", "node")
        if seat[name]["error"] != row["class"]
    ]
    for name, spelling, why in departures:
        surface = "Python" if name == "python" else "TypeScript"
        said = why if why.endswith(".") else f"{why}."
        opening = (
            f"On {surface} this is `{spelling}`: "
            if spelling
            else f"{surface} does not classify this kind from the ball. "
        )
        lines += [opening + said, ""]
    return lines


def page(read: list[dict[str, str]], seats: dict[str, dict]) -> str:
    """The whole page: the summary table, then one section per kind."""
    lines = [HEADER.rstrip("\n"), "", *summary(read, seats), "## Each kind", ""]
    for row in read:
        lines += entry(row, seats[row["kind"]])
    return "\n".join(lines).rstrip("\n") + "\n"


def findings(read: list[dict[str, str]], seats: dict[str, dict]) -> list[str]:
    """Whatever would make the page say something the tree does not."""
    listed, rowed = set(seats), {row["kind"] for row in read}
    return [
        f"{kind}: {where}"
        for kind, where in sorted(
            [(kind, "has a row and no entry in the shared kind list") for kind in rowed - listed]
            + [(kind, "is in the shared kind list and has no row") for kind in listed - rowed]
        )
    ]


def main(argv: list[str]) -> int:
    """Check the refusals page, or rewrite it."""
    parser = argparse.ArgumentParser(description="the engine's refusal rows, as a page")
    parser.add_argument("--write", action="store_true", help="rewrite the page")
    arguments = parser.parse_args(argv)

    seats = json.loads(FIXTURE.read_text(encoding="utf-8"))["kinds"]
    read = rows(ROOT)
    problems = findings(read, seats)
    if problems:
        for problem in problems:
            print(f"  {problem}")
        return 1
    rendered = page(read, seats)
    if arguments.write:
        PAGE.write_text(rendered, encoding="utf-8")
        print(f"rewrote {PAGE.relative_to(ROOT)}")
        return 0
    if PAGE.is_file() and PAGE.read_text(encoding="utf-8") == rendered:
        print(f"refusals: {len(read)} rows, page up to date")
        return 0
    print(
        "website/reference/refusals.md no longer matches the engine's rows: "
        "run `python extensions/python/tools/refusalsdoc.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
