"""Purpose: generate root exports and door faces from the package declaration.

The declaration-to-runtime direction follows Scientific Python SPEC 1:
https://scientific-python.org/specs/spec-0001/. Named imports identify their
implementations; the directory identifies satellites. Callable module types
remain declarations in the stub and keep their real runtime module objects.

Guarantees: init-stub compares the runtime root, catalog carrier declaration,
door declarations and algebra consumer against these authorities [tested:
init-stub; commit=cd62330ceacc8f1254eed9791c3f6203b48a1c9e].
probe_text checks exact root and callable-algebra result types;
Any and a non-callable module are independently rejected [tested:
test_root_consumer_rejects_any_and_non_callable_exports; commit=cd62330ceacc8f1254eed9791c3f6203b48a1c9e].
"""

from __future__ import annotations

import argparse
import ast
import builtins
import sys
from importlib.util import resolve_name
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parents[2]
CORE = ROOT / 'extensions/python/metta'
SOURCE = CORE / '__init__.py'
STUB = CORE / '__init__.pyi'
TYPE_PROBE = ROOT / 'extensions/python/tests/typing/algebra_surface.py'
sys.path[:0] = [str(TOOLS), str(CORE.parent)]

from doorfaces import (  # noqa: E402 -- the checkout path precedes tool imports
    clean_imports,
    header,
    module_tier,
)
from doorgen import (  # noqa: E402 -- the checkout path precedes tool imports
    all_rows,
    replace_region,
)
from vocabgen import member_name  # noqa: E402 -- the checkout path precedes tool imports

from metta import vocabularies  # noqa: E402 -- read the checkout's vocabulary

PROBE_HEADER = '"""Purpose: type-check root exports and callable algebra carriers.\n\nGenerated by extensions/python/tools/rootgen.py from the semiring vocabulary\nand the root declaration. The generator holds the contract and its evidence.\nCheck with `sh check.sh init-stub mypy`.\n"""\n'


def _carrier_names(rows: list[tuple[str, list[str]]]) -> list[str]:
    """Return the single semiring vocabulary as safe Python attributes."""
    matches = [values for name, values in rows if name == "semiring"]
    if len(matches) != 1 or not matches[0]:
        msg = "the catalog must expose exactly one non-empty (vocabulary semiring ...) row"
        raise SystemExit(msg)
    names = [member_name(value) for value in matches[0]]
    if len(names) != len(set(names)):
        msg = "semiring vocabulary values collide as Python carrier attributes"
        raise SystemExit(msg)
    return names


def _algebra_protocol(carriers: list[str]) -> str:
    attributes = "\n".join(f"    {name}: _DeclaredAlgebra" for name in carriers)
    parameters = """\
        *,
        plus: _Any = ...,
        times: _Any = ...,
        combine: _Any = ...,
        extend: _Any = ...,
        zero: _Any = ...,
        one: _Any = ...,
        laws: _Iterable[str] = ...,
        carrier: _Iterable[_Any] = ...,
        type: _Any = ...,
        requires: _Iterable[str] = ...,
        order: _SemiringOrder | None = ...,"""
    return f"""class _AlgebraModule(_Protocol):
{attributes}

    @_overload
    def __call__(
        self,
{parameters}
    ) -> _Callable[[type], _DeclaredAlgebra]: ...

    @_overload
    def __call__(
        self,
        subject: _Any,
{parameters}
    ) -> _DeclaredAlgebra: ...


algebra: _AlgebraModule
"""


def probe_text(carriers: list[str], rooted: set[str]) -> str:
    """Render the static consumer that exercises both calls and every carrier."""
    attributes = "\n".join(
        (
            f"assert_type(metta.algebra.{name}, DeclaredAlgebra)\n"
            f"assert_type(metta.{name}, DeclaredAlgebra)"
            if name in rooted
            else f"assert_type(metta.algebra.{name}, DeclaredAlgebra)"
        )
        for name in carriers
    )
    return f"""{PROBE_HEADER}
from collections.abc import Callable
from types import ModuleType
from typing import assert_type

import metta
from metta._atoms.factories import Atom, Symbol
from metta._atoms.namespace import _Namespace
from metta.algebra import DeclaredAlgebra

assert_type(metta.S, _Namespace[Symbol])
assert_type(metta.fn.car_atom, Symbol)
assert_type(metta.convert, ModuleType)
assert_type(metta.forms("(x)"), list[Atom])
assert_type(metta.run("!(x)"), list[list[Atom]])
assert_type(metta.algebra(int), DeclaredAlgebra)
assert_type(metta.algebra(), Callable[[type], DeclaredAlgebra])
assert_type(
    metta.algebra(
        "typed-int-product", plus=max, times=lambda a, b: a * b,
        zero=0, one=1, type=int,
    ),
    DeclaredAlgebra,
)
assert_type(metta.algebra(type=int), Callable[[type], DeclaredAlgebra])
{attributes}

_not_an_integer: int = metta.algebra(int)  # type: ignore[assignment]
"""


def exports(source: str) -> tuple[list[str], dict[str, tuple[str, str]]]:
    """Resolve the declaration's explicit named imports, refusing missing exports."""
    tree = ast.parse(source)
    assignments = [node for node in tree.body if isinstance(node, ast.Assign)
                   and any(isinstance(target, ast.Name) and target.id == '__all__' for target in node.targets)]
    if len(assignments) != 1:
        message = 'the root declaration needs exactly one literal __all__'
        raise ValueError(message)
    names = ast.literal_eval(assignments[0].value)
    if not isinstance(names, list) or any(not isinstance(name, str) or not name.isidentifier() for name in names) or len(set(names)) != len(names):
        message = 'root exports must be unique Python identifiers'
        raise ValueError(message)
    imported = {}
    functions = {node.name for node in tree.body if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))}
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                imported[alias.asname or alias.name.partition('.')[0]] = (alias.name, '')
        elif isinstance(node, ast.ImportFrom):
            module = '.' * node.level + (node.module or '')
            if node.level:
                module = resolve_name(module, 'metta')
            for alias in node.names:
                name = alias.asname or alias.name
                if name in names or (alias.asname == alias.name and not name.startswith('_')):
                    imported[name] = (module, alias.name)
    missing = set(names) - imported.keys() - functions
    if missing:
        raise ValueError('root exports lack declarations: ' + ', '.join(sorted(missing)))
    return names, imported


def projections(rows=None, root: Path = ROOT) -> dict[Path, str]:
    """Derive the runtime, marked declarations and executable carrier consumer."""
    if rows is None:
        rows = all_rows(root)
    core = root / 'extensions/python/metta'
    declaration = (core / '__init__.pyi').read_text(encoding='utf-8')
    carriers = _carrier_names([('semiring', [str(value) for value in vocabularies.Semiring])])
    imports, methods = module_tier(rows, root, stub=True)
    for start, end, content in (
        ('# begin generated root imports', '# end generated root imports', imports),
        ('# begin generated root declarations', '# end generated root declarations', methods),
        ('# begin generated algebra declaration', '# end generated algebra declaration', _algebra_protocol(carriers)),
    ):
        declaration = replace_region(declaration, start, end, [start, *content.splitlines(), end])
    declaration = clean_imports(declaration, core / '__init__.pyi')
    names, imported = exports(declaration)
    table = '\n'.join(f'    {name!r}: {value!r},' for name, value in sorted(imported.items()))
    exported = '\n'.join(f'    {name!r},' for name in names)
    runtime = header('root')
    runtime += 'from metta._lazy import package as _package\n'
    runtime += 'from metta._spaces.ambient import engine as engine\n\n'
    imports, methods = module_tier(rows, root)
    runtime += imports + '\n'
    typed_exports = [f'    from {module} import {member} as {name}'
                     + ('  # noqa: A004 -- the declared public spelling' if name in vars(builtins) else '')
                     for name, (module, member) in sorted(imported.items()) if member and name != 'engine']
    if typed_exports:
        runtime += 'if TYPE_CHECKING:\n' + '\n'.join(typed_exports) + '\n\n'
    runtime += '__all__ = [\n' + exported + '\n]\n\n'
    runtime += '__lazy_exports__ = {\n' + table + '\n}\n\n'
    runtime += '__getattr__, __dir__ = _package(__name__)\n\n'
    runtime += '# begin generated module tier\n' + methods + '# end generated module tier\n'
    return {
        core / '__init__.pyi': declaration,
        core / '__init__.py': clean_imports(runtime, core / '__init__.py'),
        root / 'extensions/python/tests/typing/algebra_surface.py': probe_text(carriers, set(imported) & set(carriers)),
    }


def main(argv: list[str] | None = None) -> int:
    """Check the projections, or regenerate them from the declarations."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args(argv)
    stale = []
    for path, wanted in projections().items():
        if path.is_file() and path.read_text(encoding='utf-8') == wanted:
            continue
        if args.write:
            path.write_text(wanted, encoding='utf-8')
            print('wrote ' + str(path.relative_to(ROOT)))
        else:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print('init-stub: stale projections: ' + ', '.join(stale))
        return 1
    print('init-stub: root declarations, runtime exports and carrier consumer agree')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
