"""Purpose: generate extensions/python/metta/vocabularies.py from the running engine's
(vocabulary ...) catalog rows, so the binding's option types and runtime
value sets follow the catalog's one authority.

Every vocabulary renders as one StrEnum class: each member IS its wire string,
so `mode=OnError.keep` autocompletes, renames, enumerates with `list(OnError)`,
survives every `value in ("keep", ...)` membership test a plain word passes,
and crosses the boundary as the symbol it always was through `__metta__`.
Bare words stay the runtime escape hatch at every consuming call; the enum is
what the annotations name, which is the guide's "never strings" rule for
option values made checkable.

Assumes:
  - swipl is on PATH and engine/metta.pl consults from the repository root,
    which is how every gate lane already runs it
Guarantees:
  - the checked-in module equals what this produces, gated on every run
    [tested: test_the_vocabulary_module_is_generated;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - the Node seat's table, extensions/node/src/vocabularies.ts, is written
    from the same rows with the Node package's own casing map, so the two
    seats cannot drift from each other or from the engine (the refinement
    vocabulary reached Python and not Node before this, and the Node test
    caught it on the merged tree) [tested: test_the_vocabulary_module_is_generated;
    commit=a376df6dff8099d6145ace55132c7e30922ea1de]
  - output is deterministic: vocabularies sorted by name, values kept in
    their declared order
    [tested: test_the_vocabulary_module_is_generated;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - the catalog visibility row generates the exact PUBLIC/INTERNAL enum
    [tested: test_visibility_is_a_generated_catalog_vocabulary;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - a catalog name that already uses CamelCase keeps that spelling in its
    Python class [tested: test_generated_alias_preserves_declared_camel_case;
    commit=4d01efe426a5a3b79d404afd993f3260e23a210c]
  - every generated member encodes as its MeTTa symbol [tested:
    test_every_vocabulary_member_crosses_as_its_symbol;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - EffectClass alone carries catalog-order comparison and strongest-member
    join/compose operations [tested:
    test_effect_class_is_the_public_five_rank_join_lattice,
    test_effect_join_obeys_the_lattice_laws;
    commit=3cfbe0d7417b1c453c2dc12d47e2e47e7de461f7]
  - a value that spells a Python keyword takes a trailing underscore as its
    member name and keeps the bare word as its value [tested:
    test_a_keyword_value_takes_a_trailing_underscore; commit=4d01efe426a5a3b79d404afd993f3260e23a210c]
Decides: the on-error-mode vocabulary is exported as OnError, the design
  record's own spelling for the enum beside `Space.on_error`
  (ai-python-first-revamp-discussion.md, the de-stringify ruling:
  "mode=OnError.keep ... list(OnError) enumeration"); the catalog row keeps
  its <head>-<argname> name.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

from __future__ import annotations

import keyword
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
MODULE = ROOT / "extensions" / "python" / "metta" / "vocabularies.py"
TS_MODULE = ROOT / "extensions" / "node" / "src" / "vocabularies.ts"

QUERY = (
    "consult('engine/metta.pl'), "
    "forall(metta_catalog_row([vocabulary, V|Vs]), "
    "       (format('~w', [V]), forall(member(X, Vs), format(' ~w', [X])), nl))"
)

HEADER = '''"""Purpose: expose catalog vocabularies as generated StrEnum classes.

Each class corresponds to one (vocabulary ...) row in &metta.

GENERATED by extensions/python/tools/vocabgen.py from the running engine's catalog
presets; edit the presets in engine/spaces/catalog.pl and rerun with --write, never
this file. The vocab-sync gate lane fails when the two drift.

Each member IS its wire string, so it passes every membership test a bare
word passes and crosses as the symbol it always was; bare words remain the
runtime escape hatch at every consuming call.

Guarantees:
  - every class here exactly matches its catalog vocabulary row, values in
    declared order
    [tested: test_the_vocabulary_module_is_generated;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - every member encodes as its MeTTa symbol
    [tested: test_every_vocabulary_member_crosses_as_its_symbol;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - Visibility is the catalog's exact PUBLIC/INTERNAL discriminator
    [tested: test_visibility_is_a_generated_catalog_vocabulary;
    commit=918e4eaae8b99077f8b8b293b4ec5c3e0e2b2cf6]
  - EffectClass compares by catalog rank and joins a plan to its strongest
    member [tested: test_effect_class_is_the_public_five_rank_join_lattice,
    test_effect_join_obeys_the_lattice_laws;
    commit=3cfbe0d7417b1c453c2dc12d47e2e47e7de461f7]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from collections.abc import Iterable
from enum import StrEnum

from .atoms import Symbol


class _AtomStrEnum(StrEnum):
    """A closed Python option whose wire identity is its MeTTa symbol."""

    def __metta__(self):
        return Symbol(self.value)


class _EffectStrEnum(_AtomStrEnum):
    """One member of an ordered effect lattice, strongest value winning."""

    @property
    def rank(self) -> int:
        """The catalog position, from structural purity to host I/O."""
        return tuple(type(self)).index(self)

    # The reason is here rather than beside the pragma because pylint reads
    # everything after disable= as message names: this is the effect
    # lattice's own operation, which shares a name with str.join on a
    # str-derived enum, and the docstring below says why that is deliberate.
    # pylint: disable-next=arguments-renamed
    def join(self, other):
        """The least upper bound of two effects: their strongest member.

        This shadows ``str.join`` on a str-derived enum deliberately: join
        is the lattice operation's own name and its laws are tested
        (commutative, idempotent, associative, with the weakest rank as
        identity). Anything that is not an effect refuses by naming both
        readings, so a caller who wanted the string operation is told which
        operation they called rather than seeing a bad-enum-value error.
        """
        try:
            other = type(self)(other)
        except ValueError:
            msg = (
                f"{other!r} is not {type(self).__name__} member; this join "
                f"is the effect lattice's least upper bound, not str.join. "
                f"To join strings, call str.join on a plain string."
            )
            raise TypeError(msg) from None
        return self if self.rank >= other.rank else other

    @classmethod
    def compose(cls, effects: Iterable):
        """Join a plan's effects; an empty plan has no observable effect."""
        result = next(iter(cls))
        for effect in effects:
            result = result.join(effect)
        return result

    def _other_rank(self, other):
        try:
            return type(self)(other).rank
        except (TypeError, ValueError):
            return NotImplemented

    def __lt__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank < rank

    def __le__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank <= rank

    def __gt__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank > rank

    def __ge__(self, other):
        rank = self._other_rank(other)
        return NotImplemented if rank is NotImplemented else self.rank >= rank

'''

#: The ledger's ruled surface names where they differ from the mechanical
#: CamelCase of the catalog row (ai-python-first-revamp-discussion.md, the
#: de-stringify ruling: "mode=OnError.keep ... list(OnError) enumeration").
RENAMES = {"on-error-mode": "OnError"}

#: The Node table's fixed text around the generated blocks: the contract
#: header, then the reflection door and the effect-lattice helpers.
TS_HEADER = '/**\n * Purpose: the engine\'s own closed value sets, as TypeScript unions, so a\n *   program that names one of these names it exactly and a typo is a compile\n *   error rather than an answer that never comes.\n * Assumes:\n *   - each block below is one `(vocabulary ...)` row in the `&metta` catalog,\n *     whose presets live in `engine/spaces/catalog.pl`\n * Guarantees:\n *   - this file is GENERATED by extensions/python/tools/vocabgen.py from the\n *     engine\'s own `(vocabulary ...)` rows, beside the Python module the same\n *     tool writes; edit the presets in engine/spaces/catalog.pl and rerun it\n *     with --write, never this file, and the `vocab-sync` lane fails on any\n *     drift [tested: test_the_vocabulary_module_is_generated; commit=a376df6dff8099d6145ace55132c7e30922ea1de]\n *   - every table here matches its catalog row exactly, values in the\n *     catalog\'s own order, and the test that checks it BOOTS the engine and\n *     reads `&metta` rather than reading a copy of this file, so the two\n *     cannot drift [tested: "every vocabulary here matches the engine\'s own";\n *     commit=bbb512316280110a747e31c26adfc31e8c5104be]\n *   - `AlgebraLaw` publishes every accepted declaration spelling, read from\n *     the same live catalog row [tested: "every vocabulary here matches the\n *     engine\'s own"; commit=5e0ae6c22d604c4b980766e3cc4811ee545e5c9e]\n *   - a value\'s KEY is this package\'s own casing map applied to the word, so\n *     `AnswerPolicy.bestFirst` is `"best-first"`, exactly as `S.bestFirst` is\n *     the symbol `best-first`. A word the map leaves alone keeps its exact\n *     spelling, which is why `OpKind.raw_det` carries an underscore the style\n *     guide would otherwise refuse: it is the engine\'s word, not an identifier\n *     this package chose\n * Decides: a const object plus a derived union type, not an `enum`. The\n *   package compiles under `erasableSyntaxOnly`, which refuses `enum` because\n *   an enum emits runtime code that type stripping cannot erase; the const\n *   object is the shape TypeScript\'s own documentation recommends in its\n *   place, and it has the property an enum lacks — the VALUES are the engine\'s\n *   own words, so a bare string still passes every door.\n * Open Obligations:\n *   To Do: None\n *   Hacks: None\n *   Future Enhancements: None\n */\n\n'
TS_TAIL = '/** One vocabulary\'s engine name. */\nexport type VocabularyName = keyof Vocabularies;\n\n/** Every value of one vocabulary, in the catalog\'s own order. */\nexport function valuesOf(vocabulary: VocabularyName): readonly string[] {\n  return Object.values(VOCABULARIES[vocabulary]);\n}\n\n/** Whether a word is a value of one vocabulary. */\nexport function isValueOf(vocabulary: VocabularyName, word: string): boolean {\n  return valuesOf(vocabulary).includes(word);\n}\n\n/**\n * How strong an effect class is, from structural purity to host I/O.\n *\n * The catalog declares the five in RANK ORDER, so the position in the row is\n * the rank and nothing here restates it.\n */\nexport function effectRank(effect: EffectClass): number {\n  return valuesOf("effect-class").indexOf(effect);\n}\n\n/**\n * The strongest of several effect classes: the lattice join.\n *\n * A plan\'s effect is the strongest effect any step of it has, which is what\n * makes this a join rather than a sum. With no arguments the answer is the\n * bottom of the lattice, `pureStructural`, because a plan that does nothing\n * has no effect.\n */\nexport function joinEffects(...effects: readonly EffectClass[]): EffectClass {\n  let strongest: EffectClass = EffectClass.pureStructural;\n  for (const effect of effects) {\n    if (effectRank(effect) > effectRank(strongest)) strongest = effect;\n  }\n  return strongest;\n}\n'


def vocabularies() -> list[tuple[str, list[str]]]:
    """Every (vocabulary Name Value...) row, asked of the engine itself."""
    completed = subprocess.run(  # noqa: S603  -- fixed argv, no untrusted input
        ["swipl", "-g", QUERY, "-t", "halt"],  # noqa: S607  -- PATH swipl, as every lane runs it
        cwd=ROOT, capture_output=True, text=True, timeout=120, check=True,
    )
    rows = []
    for line in completed.stdout.splitlines():
        words = line.split()
        if words:
            rows.append((words[0], words[1:]))
    if not rows:
        msg = (
            "the engine answered no (vocabulary ...) rows; the catalog "
            "presets failed to load, which is its own defect"
        )
        raise SystemExit(msg)
    return sorted(rows)


def alias_name(vocab: str) -> str:
    """Map a catalog vocabulary name to its Python class spelling."""
    if vocab in RENAMES:
        return RENAMES[vocab]
    return "".join(part[:1].upper() + part[1:] for part in vocab.split("-"))


def member_name(value: str) -> str:
    """Map a vocabulary value with the catalog's mechanical transliteration."""
    name = value.replace("-", "_")
    if keyword.iskeyword(name):
        name += "_"
    if not name.isidentifier():
        msg = f"vocabulary value {value!r} has no Python member spelling"
        raise SystemExit(msg)
    return name


def member_suffix(member: str) -> str:
    """The narrow lint/type exemption forced by one authored wire spelling."""
    if member[:1].islower() and any(character.isupper() for character in member[1:]):
        return "  # noqa: N815  -- the member keeps the catalog's public wire spelling"
    if hasattr(str, member):
        return "  # type: ignore[assignment]  # the member deliberately shadows a str method; the word is the API"
    return ""


def ts_alias(vocab: str) -> str:
    """Map a catalog vocabulary name to its TypeScript table spelling.

    CamelCase from the hyphenated word, with no renames: the Node seat spells
    `on-error-mode` as `OnErrorMode`, the mechanical map and nothing else.
    """
    return "".join(part[:1].upper() + part[1:] for part in vocab.split("-"))


def ts_key(value: str) -> str:
    """Map a vocabulary value with the Node package's own casing map.

    A hyphenated word becomes camelCase (`best-first` is `bestFirst`, exactly
    as `S.bestFirst` is that symbol); a word the map leaves alone keeps its
    spelling, underscore and all (`raw_det`). A result that is not a
    TypeScript identifier is written as a quoted key.
    """
    head, *rest = value.split("-")
    key = head + "".join(part[:1].upper() + part[1:] for part in rest)
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", key):
        return key
    return f'"{key}"'


def ts_text(rows: list[tuple[str, list[str]]]) -> str:
    """Render the Node vocabulary table from the same rows as the module."""
    blocks = []
    for vocab, values in rows:
        alias = ts_alias(vocab)
        keys = [ts_key(value) for value in values]
        if len(set(keys)) != len(keys):
            msg = f"vocabulary {vocab!r} has values that collide as TypeScript keys"
            raise SystemExit(msg)
        members = "".join(
            f'  {key}: "{value}",\n' for key, value in zip(keys, values, strict=True)
        )
        blocks.append(
            f"/** The `{vocab}` vocabulary, in the catalog's own order. */\n"
            f"export const {alias} = {{\n{members}}} as const;\n\n"
            f"/** One value of the `{vocab}` vocabulary. */\n"
            f"export type {alias} = (typeof {alias})[keyof typeof {alias}];\n\n"
        )
    interface = "".join(
        f'  readonly "{vocab}": typeof {ts_alias(vocab)};\n' for vocab, _ in rows
    )
    registry = "".join(f'  "{vocab}": {ts_alias(vocab)},\n' for vocab, _ in rows)
    return (
        TS_HEADER
        + "".join(blocks)
        + "/**\n * Every vocabulary, by the engine's own name for it.\n *\n"
        " * The reflection door: a tool that must enumerate the closed sets reads this\n"
        " * rather than a list it keeps itself, and the sync test walks it against\n"
        " * `&metta`.\n */\n"
        f"export interface Vocabularies {{\n{interface}}}\n\n"
        "/** Every vocabulary, by the engine's own name for it. */\n"
        f"export const VOCABULARIES: Vocabularies = {{\n{registry}}};\n\n"
        + TS_TAIL
    )


def module_text(rows: list[tuple[str, list[str]]]) -> str:
    """Render one deterministic generated vocabulary module."""
    body = []
    for vocab, values in rows:
        members = [member_name(value) for value in values]
        if len(set(members)) != len(members):
            msg = f"vocabulary {vocab!r} has values that collide as members"
            raise SystemExit(msg)
        body.append(f"#: (vocabulary {vocab} {' '.join(values)})")
        base = "_EffectStrEnum" if vocab == "effect-class" else "_AtomStrEnum"
        body.append(f"class {alias_name(vocab)}({base}):")
        body.append(f'    """Typed values of the {vocab} vocabulary."""')
        body.extend(
            f'    {member} = "{value}"' + member_suffix(member)
            for member, value in zip(members, values, strict=True)
        )
        body.append("")
    exported = sorted(alias_name(v) for v, _ in rows)
    names = ",\n    ".join(f'"{name}"' for name in exported)
    return (
        HEADER
        + "__all__ = [\n    " + names + ",\n]\n\n"
        + "\n".join(body)
    )


def main(argv: list[str]) -> int:
    """Check both generated tables, or rewrite them when asked."""
    rows = vocabularies()
    stale = []
    for path, wanted in ((MODULE, module_text(rows)), (TS_MODULE, ts_text(rows))):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == wanted:
            continue
        if "--write" in argv:
            path.write_text(wanted, encoding="utf-8")
            print(f"rewrote {path.relative_to(ROOT)}")
        else:
            stale.append(str(path.relative_to(ROOT)))
    if not stale:
        return 0
    print(
        f"{', '.join(stale)} no longer match the engine's (vocabulary ...) "
        f"rows: run `python extensions/python/tools/vocabgen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
