"""Purpose: generate python/petta/vocabularies.py from the running engine's
(vocabulary ...) catalog rows, so the binding's Literal types and runtime
value tuples follow the catalog's one authority.

Before this, every declare_* method repeated its value words three times:
the Literal annotation, the runtime check tuple, and the engine's
consultation site, and the annotations surface was measured advertising six
semirings while the engine acted on two. The catalog presets in
src/spaces.pl are the source now; this asks the engine itself rather than
parsing Prolog text, because the running catalog is what declaration checks
and generated binding surfaces consume.

Assumes:
  - swipl is on PATH and src/metta.pl consults from the repository root,
    which is how every gate lane already runs it
Guarantees:
  - the checked-in module equals what this produces, gated on every run
    [tested test_the_vocabulary_module_is_generated]
  - output is deterministic: vocabularies sorted by name, values kept in
    their declared order
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MODULE = ROOT / "python" / "petta" / "vocabularies.py"

QUERY = (
    "consult('src/metta.pl'), "
    "forall(petta_catalog_row([vocabulary, V|Vs]), "
    "       (format('~w', [V]), forall(member(X, Vs), format(' ~w', [X])), nl))"
)

HEADER = '''"""Purpose: the catalog's value vocabularies as Python constants and
Literal aliases, one per (vocabulary ...) row in &petta.

GENERATED by python/tools/vocabgen.py from the running engine's catalog
presets; edit the presets in src/spaces.pl and rerun with --write, never
this file. The vocab-sync gate lane fails when the two drift.

Guarantees:
  - every tuple and Literal here exactly matches its catalog vocabulary row
    [tested test_the_vocabulary_module_is_generated]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""

from typing import Literal

'''


def vocabularies() -> list[tuple[str, list[str]]]:
    """Every (vocabulary Name Value...) row, asked of the engine itself."""
    completed = subprocess.run(  # noqa: S603  -- fixed argv, no untrusted input
        ["swipl", "-g", QUERY, "-t", "halt"],  # noqa: S607  -- PATH swipl, as every lane runs it
        cwd=ROOT, capture_output=True, text=True, timeout=120, check=True,
    )
    rows = []
    for line in completed.stdout.splitlines():
        words = line.split()
        if words:
            rows.append((words[0], words[1:]))
    if not rows:
        raise SystemExit(
            "the engine answered no (vocabulary ...) rows; the catalog "
            "presets failed to load, which is its own defect"
        )
    return sorted(rows)


def constant_name(vocab: str) -> str:
    return vocab.replace("-", "_").upper()


def alias_name(vocab: str) -> str:
    return "".join(part.capitalize() for part in vocab.split("-"))


def module_text(rows: list[tuple[str, list[str]]]) -> str:
    body = []
    for vocab, values in rows:
        rendered = ", ".join(f'"{value}"' for value in values)
        trailing = "," if len(values) == 1 else ""
        body.append(f"#: (vocabulary {vocab} {' '.join(values)})")
        body.append(f"{constant_name(vocab)} = ({rendered}{trailing})")
        body.append(f"{alias_name(vocab)} = Literal[{rendered}]")
        body.append("")
    # isort-style export order, the shape ruff's RUF022 enforces: the
    # constant group first, the alias group after, each sorted.
    exported = (sorted(constant_name(v) for v, _ in rows)
                + sorted(alias_name(v) for v, _ in rows))
    names = ",\n    ".join(f'"{name}"' for name in exported)
    return (
        HEADER
        + "__all__ = [\n    " + names + ",\n]\n\n"
        + "\n".join(body)
    )


def main(argv: list[str]) -> int:
    wanted = module_text(vocabularies())
    current = MODULE.read_text(encoding="utf-8") if MODULE.exists() else None
    if current == wanted:
        return 0
    if "--write" in argv:
        MODULE.write_text(wanted, encoding="utf-8")
        print(f"rewrote {MODULE.name}")
        return 0
    print(
        f"petta/{MODULE.name} no longer matches the engine's (vocabulary ...) "
        f"rows: run `python python/tools/vocabgen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
