"""Purpose: generate bindings/python/metta/vocabularies.py from the running engine's
(vocabulary ...) catalog rows, so the binding's option types and runtime
value sets follow the catalog's one authority.

Every vocabulary renders as one StrEnum class: each member IS its wire string,
so `mode=OnError.keep` autocompletes, renames, enumerates with `list(OnError)`,
survives every `value in ("keep", ...)` membership test a plain word passes,
and crosses the boundary as the symbol it always was through `__metta__`.
Bare words stay the runtime escape hatch at every consuming door; the enum is
what the annotations name, which is the guide's "never strings" rule for
option values made checkable.

Assumes:
  - swipl is on PATH and engine/metta.pl consults from the repository root,
    which is how every gate lane already runs it
Guarantees:
  - the checked-in module equals what this produces, gated on every run
    [tested: test_the_vocabulary_module_is_generated; commit=WORKTREE]
  - output is deterministic: vocabularies sorted by name, values kept in
    their declared order
    [tested: test_the_vocabulary_module_is_generated; commit=WORKTREE]
  - a catalog name that already uses CamelCase keeps that spelling in its
    Python class [tested: test_generated_alias_preserves_declared_camel_case;
    commit=WORKTREE]
  - every generated member encodes as its MeTTa symbol [tested:
    test_every_vocabulary_member_crosses_as_its_symbol; commit=WORKTREE]
  - a value that spells a Python keyword takes a trailing underscore as its
    member name and keeps the bare word as its value [tested:
    test_a_keyword_value_takes_a_trailing_underscore; commit=WORKTREE]
Decides: the on-error-mode vocabulary is exported as OnError, the design
  record's own spelling for the enum beside `Space.on_error`
  (ai-python-first-revamp-discussion.md, the de-stringify ruling:
  "mode=OnError.keep ... list(OnError) enumeration"); the catalog row keeps
  its <head>-<argname> name.
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""  # noqa: D205  -- the contract is one continuous invariant, not summary-and-body prose

from __future__ import annotations

import keyword
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
MODULE = ROOT / "bindings" / "python" / "metta" / "vocabularies.py"

QUERY = (
    "consult('engine/metta.pl'), "
    "forall(petta_catalog_row([vocabulary, V|Vs]), "
    "       (format('~w', [V]), forall(member(X, Vs), format(' ~w', [X])), nl))"
)

HEADER = '''"""Purpose: the catalog's value vocabularies as StrEnum classes, one per
(vocabulary ...) row in &petta.

GENERATED by bindings/python/tools/vocabgen.py from the running engine's catalog
presets; edit the presets in engine/spaces.pl and rerun with --write, never
this file. The vocab-sync gate lane fails when the two drift.

Each member IS its wire string, so it passes every membership test a bare
word passes and crosses as the symbol it always was; bare words remain the
runtime escape hatch at every consuming door.

Guarantees:
  - every class here exactly matches its catalog vocabulary row, values in
    declared order
    [tested: test_the_vocabulary_module_is_generated; commit=WORKTREE]
  - every member encodes as its MeTTa symbol
    [tested: test_every_vocabulary_member_crosses_as_its_symbol; commit=WORKTREE]
Open Obligations:
  To Do: None
  Hacks: None
  Future Enhancements: None
"""  # noqa: D205  -- the API contract is one continuous invariant, not summary-and-body prose

from enum import StrEnum

from .atoms import Symbol


class _AtomStrEnum(StrEnum):
    """A closed Python option whose wire identity is its MeTTa symbol."""

    def __metta__(self):
        return Symbol(self.value)

'''

#: The ledger's ruled surface names where they differ from the mechanical
#: CamelCase of the catalog row (ai-python-first-revamp-discussion.md, the
#: de-stringify ruling: "mode=OnError.keep ... list(OnError) enumeration").
RENAMES = {"on-error-mode": "OnError"}


def vocabularies() -> list[tuple[str, list[str]]]:
    """Every (vocabulary Name Value...) row, asked of the engine itself."""
    completed = subprocess.run(  # noqa: S603  -- fixed argv, no untrusted input
        ["swipl", "-g", QUERY, "-t", "halt"],  # noqa: S607  -- PATH swipl, as every lane runs it
        cwd=ROOT, capture_output=True, text=True, timeout=120, check=True,
    )
    rows = []
    for line in completed.stdout.splitlines():
        words = line.split()
        if words:
            rows.append((words[0], words[1:]))
    if not rows:
        msg = (
            "the engine answered no (vocabulary ...) rows; the catalog "
            "presets failed to load, which is its own defect"
        )
        raise SystemExit(msg)
    return sorted(rows)


def alias_name(vocab: str) -> str:
    """Map a catalog vocabulary name to its Python class spelling."""
    if vocab in RENAMES:
        return RENAMES[vocab]
    return "".join(part[:1].upper() + part[1:] for part in vocab.split("-"))


def member_name(value: str) -> str:
    """Map a vocabulary value to its member spelling: rung 4's own transliteration."""
    name = value.replace("-", "_")
    if keyword.iskeyword(name):
        name += "_"
    if not name.isidentifier():
        msg = f"vocabulary value {value!r} has no Python member spelling"
        raise SystemExit(msg)
    return name


def module_text(rows: list[tuple[str, list[str]]]) -> str:
    """Render one deterministic generated vocabulary module."""
    body = []
    for vocab, values in rows:
        members = [member_name(value) for value in values]
        if len(set(members)) != len(members):
            msg = f"vocabulary {vocab!r} has values that collide as members"
            raise SystemExit(msg)
        body.append(f"#: (vocabulary {vocab} {' '.join(values)})")
        body.append(f"class {alias_name(vocab)}(_AtomStrEnum):")
        body.append(f'    """Typed values of the {vocab} vocabulary."""')
        body.extend(
            f'    {member} = "{value}"'
            + ("  # type: ignore[assignment]  # the member deliberately shadows a str method; the word is the API"
               if hasattr(str, member) else "")
            for member, value in zip(members, values, strict=True)
        )
        body.append("")
    exported = sorted(alias_name(v) for v, _ in rows)
    names = ",\n    ".join(f'"{name}"' for name in exported)
    return (
        HEADER
        + "__all__ = [\n    " + names + ",\n]\n\n"
        + "\n".join(body)
    )


def main(argv: list[str]) -> int:
    """Check the generated module, or rewrite it when asked."""
    wanted = module_text(vocabularies())
    current = MODULE.read_text(encoding="utf-8") if MODULE.exists() else None
    if current == wanted:
        return 0
    if "--write" in argv:
        MODULE.write_text(wanted, encoding="utf-8")
        print(f"rewrote {MODULE.name}")
        return 0
    print(
        f"metta/{MODULE.name} no longer matches the engine's (vocabulary ...) "
        f"rows: run `python bindings/python/tools/vocabgen.py --write`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
