"""Purpose: type the accessor namespaces declared by installed workspace packages.

Generated by tools/doorgen.py from door rows.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import metta_arrays_doors as _body_0  # type: ignore[import-not-found, unused-ignore]  # ty: ignore[unresolved-import] -- optional provider declarations remain typed when installed
    import metta_live as _body_1  # type: ignore[import-not-found, unused-ignore]  # ty: ignore[unresolved-import] -- optional provider declarations remain typed when installed
    import metta_pandas as _body_2  # type: ignore[import-not-found, unused-ignore]  # ty: ignore[unresolved-import] -- optional provider declarations remain typed when installed
    import metta_polars as _body_3  # type: ignore[import-not-found, unused-ignore]  # ty: ignore[unresolved-import] -- optional provider declarations remain typed when installed
    import metta_remote as _body_4  # type: ignore[import-not-found, unused-ignore]  # ty: ignore[unresolved-import] -- optional provider declarations remain typed when installed
    import metta_tables as _body_5  # type: ignore[import-not-found, unused-ignore]  # ty: ignore[unresolved-import] -- optional provider declarations remain typed when installed

    import metta._spaces.results as _results


class ArraysContext(Protocol):
    """The context members of the arrays accessor."""

    def install(self, default: _body_0.Any=...) -> list[str]:
        """Register the array operation set on the shared engine.

        default names the library the constructors build in: a module, a module
        name, or None for NumPy. Every other operation dispatches on its
        argument's own namespace, so arrays from any conforming library flow
        through the same MeTTa functions, and a mixed binary call converts the
        right operand into the left's library through from_dlpack.

        Every installed name has one or more arrow declarations. Constructors
        with optional or variadic dimensions have one arrow per accepted arity.

        broadcast-shape is the CLP(FD) relation over shape expressions. It can
        compute a result before any tensor exists, infer an unknown input
        dimension from a required result, or reject incompatible shapes:

            !(let True (broadcast-shape (4 1) (3) $shape) $shape)  ; (4 3)
            !(let True (broadcast-shape ($d 1) (1 3) (4 3)) $d)   ; 4
            !(broadcast-shape (2 3) (4 3) (4 3))                  ; no answer

        t-shape remains observation of an existing tensor. Use broadcast-shape
        when compatibility or inference must happen before materialisation.

        ``Shape`` carries those expressions through Python ``Annotated`` claims.
        User operation arrows retain the claim: argument dimensions unify and
        bind shared result dimensions. Live values report the same type expression.
        ``SHAPE_RULES`` names every installed head's behavior; preserving heads
        share their entire input shape with the result. Other transformations
        expose their actual shape when their result value exists.
        A declared ``(Annotated DLTensor (Shape ...))`` remains a valid DLTensor
        argument, elementwise binary operations derive their output shape with
        ``broadcast-shape``, and rank-two matmul unifies the two inner dimensions:

            (: image (Annotated DLTensor (Shape (4 1))))
            (: bias  (Annotated DLTensor (Shape (3))))
            !(get-type (t+ image bias))  ; (Annotated DLTensor (Shape (4 3)))

        m may be a context or a space. The operations are registered into the
        space either way, which is the object whose storage and introspection
        doors this needs; `install(m)` on a context used to raise
        `MeTTa has no 'is_function'` and leave every operation unregistered.

        What this space installed becomes one catalog row,
        ``(array-backend <space> <library> (ops ...))`` in ``&metta``, which
        ``ops(m)`` and ``backend(m)`` read back and a MeTTa program can match for
        itself. Installing again REPLACES that row, the space's constructor
        aliases, and every operation of the outgoing roster that no other space's
        row still names; ``uninstall(m)`` retires the whole installation, and
        dropping the space retires the row with it. Two spaces may therefore hold
        two libraries at once, in either install order, each answering its own.
        """

    def uninstall(self) -> list[str]:
        """Retire this space's array installation; answers what it unregistered.

        The inverse of `install`. The space's roster row goes, with its
        constructor aliases and the bare-name arrows those carried, the `get-type`
        shape equations and the shaped-DLTensor typing rule; then every operation
        the roster named is unregistered UNLESS another space's row still names
        it, because the operation registry is process-wide by name and two spaces
        on numpy share `zeros--numpy` and the whole backend-agnostic set. The
        answer is therefore what actually left the registry, in roster order.

            arrays.install(space, default=numpy)
            arrays.uninstall(space)
            arrays.ops(space)            # refuses: nothing is installed here

        An operation another space claims stays registered, and this space stops
        DECLARING it: `ops.withdraw` releases the rows that would otherwise keep
        the space describing a function it no longer routes to.

        Dropping the space retires the row without this call, the catalog
        retiring a space's declarations with it, but the process-wide operations
        are the registry's and only this door hands them back.

        Two registrations deliberately survive, both keyed on the DLPack
        predicate rather than on a space, so one registration serves every space
        and withdrawing it here would change another space's answers: the
        DLTensor type and array printing hooks, whose own doors are
        `integrate.unregister_object_type` and `integrate.unregister_repr`, and
        the `broadcast-shape` CLP(FD) relation, which `register_prolog` has no
        withdrawal for.

        m may be a context or a space, as `install` takes either.
        """

    def ops(self) -> list[str]:
        """The array operation names installed in this space, in install order.

        `install` returns the same list; this reads it back from the space long
        afterwards, so two spaces on two libraries answer their own rosters
        whatever order they were installed in:

            numpy_space, jax_space = m.space(), m.space()
            arrays.install(jax_space, default=jax.numpy)
            arrays.install(numpy_space, default=numpy)
            arrays.ops(numpy_space)      # ... 'zeros--numpy' ...
            arrays.backend(jax_space)    # 'jax.numpy'

        m may be a context or a space. The longhand is the row itself, which is
        ordinary matchable data: `!(match &metta (array-backend &s $lib $ops) $ops)`.
        A space with no install refuses, naming install as the remedy.
        """

    def backend(self) -> str:
        """The array library this space's constructors build in.

        The fully qualified module name install() recorded, `numpy` or
        `jax.numpy`, which is the same name its constructor registrations carry
        after the `--` in `zeros--numpy`. `ops` answers the roster beside it, and
        the row behind both is `(array-backend <space> <library> (ops ...))` in
        `&metta`.
        """


class ArraysSync(Protocol):
    """The sync members of the arrays accessor."""

    def install(self, default: _body_0.Any=...) -> list[str]:
        """Register the array operation set on the shared engine.

        default names the library the constructors build in: a module, a module
        name, or None for NumPy. Every other operation dispatches on its
        argument's own namespace, so arrays from any conforming library flow
        through the same MeTTa functions, and a mixed binary call converts the
        right operand into the left's library through from_dlpack.

        Every installed name has one or more arrow declarations. Constructors
        with optional or variadic dimensions have one arrow per accepted arity.

        broadcast-shape is the CLP(FD) relation over shape expressions. It can
        compute a result before any tensor exists, infer an unknown input
        dimension from a required result, or reject incompatible shapes:

            !(let True (broadcast-shape (4 1) (3) $shape) $shape)  ; (4 3)
            !(let True (broadcast-shape ($d 1) (1 3) (4 3)) $d)   ; 4
            !(broadcast-shape (2 3) (4 3) (4 3))                  ; no answer

        t-shape remains observation of an existing tensor. Use broadcast-shape
        when compatibility or inference must happen before materialisation.

        ``Shape`` carries those expressions through Python ``Annotated`` claims.
        User operation arrows retain the claim: argument dimensions unify and
        bind shared result dimensions. Live values report the same type expression.
        ``SHAPE_RULES`` names every installed head's behavior; preserving heads
        share their entire input shape with the result. Other transformations
        expose their actual shape when their result value exists.
        A declared ``(Annotated DLTensor (Shape ...))`` remains a valid DLTensor
        argument, elementwise binary operations derive their output shape with
        ``broadcast-shape``, and rank-two matmul unifies the two inner dimensions:

            (: image (Annotated DLTensor (Shape (4 1))))
            (: bias  (Annotated DLTensor (Shape (3))))
            !(get-type (t+ image bias))  ; (Annotated DLTensor (Shape (4 3)))

        m may be a context or a space. The operations are registered into the
        space either way, which is the object whose storage and introspection
        doors this needs; `install(m)` on a context used to raise
        `MeTTa has no 'is_function'` and leave every operation unregistered.

        What this space installed becomes one catalog row,
        ``(array-backend <space> <library> (ops ...))`` in ``&metta``, which
        ``ops(m)`` and ``backend(m)`` read back and a MeTTa program can match for
        itself. Installing again REPLACES that row, the space's constructor
        aliases, and every operation of the outgoing roster that no other space's
        row still names; ``uninstall(m)`` retires the whole installation, and
        dropping the space retires the row with it. Two spaces may therefore hold
        two libraries at once, in either install order, each answering its own.
        """

    def uninstall(self) -> list[str]:
        """Retire this space's array installation; answers what it unregistered.

        The inverse of `install`. The space's roster row goes, with its
        constructor aliases and the bare-name arrows those carried, the `get-type`
        shape equations and the shaped-DLTensor typing rule; then every operation
        the roster named is unregistered UNLESS another space's row still names
        it, because the operation registry is process-wide by name and two spaces
        on numpy share `zeros--numpy` and the whole backend-agnostic set. The
        answer is therefore what actually left the registry, in roster order.

            arrays.install(space, default=numpy)
            arrays.uninstall(space)
            arrays.ops(space)            # refuses: nothing is installed here

        An operation another space claims stays registered, and this space stops
        DECLARING it: `ops.withdraw` releases the rows that would otherwise keep
        the space describing a function it no longer routes to.

        Dropping the space retires the row without this call, the catalog
        retiring a space's declarations with it, but the process-wide operations
        are the registry's and only this door hands them back.

        Two registrations deliberately survive, both keyed on the DLPack
        predicate rather than on a space, so one registration serves every space
        and withdrawing it here would change another space's answers: the
        DLTensor type and array printing hooks, whose own doors are
        `integrate.unregister_object_type` and `integrate.unregister_repr`, and
        the `broadcast-shape` CLP(FD) relation, which `register_prolog` has no
        withdrawal for.

        m may be a context or a space, as `install` takes either.
        """

    def ops(self) -> list[str]:
        """The array operation names installed in this space, in install order.

        `install` returns the same list; this reads it back from the space long
        afterwards, so two spaces on two libraries answer their own rosters
        whatever order they were installed in:

            numpy_space, jax_space = m.space(), m.space()
            arrays.install(jax_space, default=jax.numpy)
            arrays.install(numpy_space, default=numpy)
            arrays.ops(numpy_space)      # ... 'zeros--numpy' ...
            arrays.backend(jax_space)    # 'jax.numpy'

        m may be a context or a space. The longhand is the row itself, which is
        ordinary matchable data: `!(match &metta (array-backend &s $lib $ops) $ops)`.
        A space with no install refuses, naming install as the remedy.
        """

    def backend(self) -> str:
        """The array library this space's constructors build in.

        The fully qualified module name install() recorded, `numpy` or
        `jax.numpy`, which is the same name its constructor registrations carry
        after the `--` in `zeros--numpy`. `ops` answers the roster beside it, and
        the row behind both is `(array-backend <space> <library> (ops ...))` in
        `&metta`.
        """


class LiveContext(Protocol):
    """The context members of the live accessor."""

    def view(
        self,
        *query: _body_1.Any,
        on: _body_1.SubscriptionEdge=...,
        strategy: str | None=...,
    ) -> _body_1.Any:
        """Maintain a query's multiset through this space's committed writes.

        The returned Live owns its subscriptions. close() releases them, and
        changes() reads its progress and deltas. strategy selects pattern, heads,
        or tabled maintenance; omitting it selects from the query's shape.
        """

    def __call__(
        self,
        *query: _body_1.Any,
        on: _body_1.SubscriptionEdge=...,
        strategy: str | None=...,
    ) -> _body_1.Any:
        """Maintain a query's multiset through this space's committed writes.

        The returned Live owns its subscriptions. close() releases them, and
        changes() reads its progress and deltas. strategy selects pattern, heads,
        or tabled maintenance; omitting it selects from the query's shape.
        """


class LiveSync(Protocol):
    """The sync members of the live accessor."""

    def view(
        self,
        *query: _body_1.Any,
        on: _body_1.SubscriptionEdge=...,
        strategy: str | None=...,
    ) -> _body_1.Any:
        """Maintain a query's multiset through this space's committed writes.

        The returned Live owns its subscriptions. close() releases them, and
        changes() reads its progress and deltas. strategy selects pattern, heads,
        or tabled maintenance; omitting it selects from the query's shape.
        """

    def __call__(
        self,
        *query: _body_1.Any,
        on: _body_1.SubscriptionEdge=...,
        strategy: str | None=...,
    ) -> _body_1.Any:
        """Maintain a query's multiset through this space's committed writes.

        The returned Live owns its subscriptions. close() releases them, and
        changes() reads its progress and deltas. strategy selects pattern, heads,
        or tabled maintenance; omitting it selects from the query's shape.
        """


class RemoteContext(Protocol):
    """The context members of the remote accessor."""

    def connect(
        self,
        url: str,
        timeout: float=...,
        *,
        token: str | None=...,
        headers: dict[str, str] | None=...,
        ssl_context: _body_4.Any=...,
    ) -> _body_4.Transport:
        """The HTTP transport for a serve()d engine: one POST per operation,
        JSON both ways, errors surfaced with the remote's own message.

        token sends Bearer authentication, headers adds anything else a
        deployment needs (an API key, a tenant id), and ssl_context is
        Python's own ssl.SSLContext for https urls, certificate pinning
        included, so the transport composes with whatever security the
        serving side asks for. Only absolute http and https URLs are accepted.
        Credentials require https. Each mutation negotiates a replay key through
        GET /health before its POST; authorization policies must permit that read.
        An unadvertised extension leaves mutations unkeyed, and OutcomeUnknown
        refuses to resend those requests after a lost response.
        """  # noqa: D205 -- preserve the declared documentation

    def serve(
        self,
        host: str=...,
        port: int=...,
        spaces: list[str] | None=...,
        *,
        token: str | None=...,
        authorize: _body_4.Callable[[_body_4.Request], bool] | None=...,
        ssl_context: _body_4.Any=...,
        cursor_idle: float=...,
        cursor_limit: int=...,
        mutation_ttl: float=...,
        mutation_limit: int=...,
    ) -> _body_4.Server:
        """Expose this engine's spaces over HTTP; port 0 picks a free one.

        Every operation answers for the space the request names, restricted
        to `spaces` when given. Security is the caller's to define, library
        fashion: token requires Bearer authentication, authorize is the
        general hook (a Request in, carrying the operation, the space and
        the headers, and a verdict out, so read-only, per-space and
        per-tenant policies all fit), and ssl_context, Python's own
        ssl.SSLContext with a certificate loaded, serves TLS directly;
        anything heavier still composes behind a fronting proxy. match runs
        the engine's own match with the pattern as its template, so the
        instantiated atoms cross, and the caller's engine re-unifies them.

        `cursor_idle` and `cursor_limit` bound the ask/next/stop lifecycle's
        server-side state: how long a cursor nobody pulls from survives, and
        how many live at once before a further ask is refused. The defaults
        are pengines' own, 300 seconds and a ceiling.

        mutation_ttl and mutation_limit bound the keyed mutation replay ledger,
        as documented on Gateway. Authorization must admit health for clients
        that negotiate mutation keys.

        A context is a PROCESS: serving and attaching within one process
        cannot join through the local engine, because one runtime lock guards
        both sides of that call and the serving thread would wait on the very
        evaluation that is waiting on it. Two engines, two processes, is the
        deployment this exists for; in-process, spaces already share the
        engine and need no wire. Gateway is the same protocol with no
        transport under it, for a test or a framework that wants the
        operations without a socket.

        m may be a context or a space, as Gateway takes either.
        """


class RemoteSync(Protocol):
    """The sync members of the remote accessor."""

    def connect(
        self,
        url: str,
        timeout: float=...,
        *,
        token: str | None=...,
        headers: dict[str, str] | None=...,
        ssl_context: _body_4.Any=...,
    ) -> _body_4.Transport:
        """The HTTP transport for a serve()d engine: one POST per operation,
        JSON both ways, errors surfaced with the remote's own message.

        token sends Bearer authentication, headers adds anything else a
        deployment needs (an API key, a tenant id), and ssl_context is
        Python's own ssl.SSLContext for https urls, certificate pinning
        included, so the transport composes with whatever security the
        serving side asks for. Only absolute http and https URLs are accepted.
        Credentials require https. Each mutation negotiates a replay key through
        GET /health before its POST; authorization policies must permit that read.
        An unadvertised extension leaves mutations unkeyed, and OutcomeUnknown
        refuses to resend those requests after a lost response.
        """  # noqa: D205 -- preserve the declared documentation

    def serve(
        self,
        host: str=...,
        port: int=...,
        spaces: list[str] | None=...,
        *,
        token: str | None=...,
        authorize: _body_4.Callable[[_body_4.Request], bool] | None=...,
        ssl_context: _body_4.Any=...,
        cursor_idle: float=...,
        cursor_limit: int=...,
        mutation_ttl: float=...,
        mutation_limit: int=...,
    ) -> _body_4.Server:
        """Expose this engine's spaces over HTTP; port 0 picks a free one.

        Every operation answers for the space the request names, restricted
        to `spaces` when given. Security is the caller's to define, library
        fashion: token requires Bearer authentication, authorize is the
        general hook (a Request in, carrying the operation, the space and
        the headers, and a verdict out, so read-only, per-space and
        per-tenant policies all fit), and ssl_context, Python's own
        ssl.SSLContext with a certificate loaded, serves TLS directly;
        anything heavier still composes behind a fronting proxy. match runs
        the engine's own match with the pattern as its template, so the
        instantiated atoms cross, and the caller's engine re-unifies them.

        `cursor_idle` and `cursor_limit` bound the ask/next/stop lifecycle's
        server-side state: how long a cursor nobody pulls from survives, and
        how many live at once before a further ask is refused. The defaults
        are pengines' own, 300 seconds and a ceiling.

        mutation_ttl and mutation_limit bound the keyed mutation replay ledger,
        as documented on Gateway. Authorization must admit health for clients
        that negotiate mutation keys.

        A context is a PROCESS: serving and attaching within one process
        cannot join through the local engine, because one runtime lock guards
        both sides of that call and the serving thread would wait on the very
        evaluation that is waiting on it. Two engines, two processes, is the
        deployment this exists for; in-process, spaces already share the
        engine and need no wire. Gateway is the same protocol with no
        transport under it, for a test or a framework that wants the
        operations without a socket.

        m may be a context or a space, as Gateway takes either.
        """


class TablesContext(Protocol):
    """The context members of the tables accessor."""

    def to_df(self, rows: _body_2.Any) -> _body_2.Any:
        """These rows as a pandas DataFrame; the declared point rows.to('pandas')."""

    def to_pl(self, rows: _body_3.Any) -> _body_3.Any:
        """These rows as a polars DataFrame; the declared point rows.to('polars')."""

    def add(self, head: _body_5.Any, data: _body_5.Any) -> int:
        """Add a tabular source to a space as ``(head column...)`` facts.

        space may be a context or a space.

        The source may offer rows its own way (``iter_rows()`` for polars,
        ``itertuples()`` for pandas, a mapping of columns, any iterable of rows)
        or speak the Arrow PyCapsule Interface, which is how a DuckDB relation, a
        pyarrow Table, a Parquet reader or an Ibis expression hands over rows
        without a row-at-a-time Python door. A source with both keeps its own:
        the two produce identical atoms, and the row door is the faster of them
        [measured 2026-09-06: 10,000 rows, polars 14.07 ms through iter_rows
        against 14.36 ms through the stream, pandas 20.39 ms against 25.11 ms].

        An Arrow source is written one record batch at a time, so a reader larger
        than memory loads, and the writes are one transaction each; wrap the call
        in ``m.transaction(...)`` to make the whole load one.
        """

    def declare(self, name: str, declaration: _body_5.Atom | str) -> _body_5.Atom:
        """Write one ctx-scoped bridge declaration into &metta, where explain
        and any program can read the schema, and from_context will.

        m may be a context or a space.
        """  # noqa: D205 -- preserve the declared documentation

    def accessors(self) -> tuple[str, ...]:
        """Install the metta accessor for every registered frame library already imported.

        Answers the libraries that now carry it, so a program can ask.

        Registration never imports a frame library. `import metta.tables` costs
        15 ms and `import pandas` costs 531 ms [measured 2026-09-06,
        time.perf_counter around each import in a fresh interpreter], so a module
        that registered by importing would charge every tables user for a library
        the program may never touch. It installs for whichever registered module
        is in `sys.modules`, every door in this module calls it first, and a
        program that imports a frame library afterwards and touches nothing else
        here calls this by name. Idempotent, because a library warns when an
        accessor name is replaced.

        Which libraries these are is the `frame` point's rows, not a list here:
        each row says which module it is and how that library spells an accessor,
        so a third one installs `df.metta` by registering
        (`metta.seam.frame.register(...)`, or the `metta.extensions` entry point).
        """

    def sql_function(self, connection: _body_5.Any, head: _body_5.Any, name: str | None=...) -> str:
        """Register a MeTTa head as a scalar SQL function, and answer its SQL name.

            m.run("(: dbl (-> Number Number))  (= (dbl $x) (* 2 $x))")
            tables.sql_function(connection, m.fn.dbl)
            connection.sql("select dbl(age) from people")

        The head is the callable from a space's `fn` namespace, which already
        carries its own name, its arity and its arrow, so nothing about the
        function is restated here; `name=` is the escape for a SQL identifier the
        head's own name cannot be.

        WHICH engines are known is the `sql` point's rows, and the first row that
        claims the connection declares the function its own way: sqlite3 wants the
        arity and no types, DuckDB wants the types and reads them from the head's
        DECLARED arrow, refusing by name when there is none (an arrow
        `inspect.signature` merely infers is a proposal, not a promise). A third
        engine registers rather than being added here. A row that produces no
        answer is SQL NULL and one that produces several refuses, because a scalar
        function has one result per row; a SQL NULL argument reaches the head as
        `Grounded(None)` and MeTTa decides what it means.
        """


class TablesSync(Protocol):
    """The sync members of the tables accessor."""

    def to_df(self, rows: _body_2.Any) -> _body_2.Any:
        """These rows as a pandas DataFrame; the declared point rows.to('pandas')."""

    def to_pl(self, rows: _body_3.Any) -> _body_3.Any:
        """These rows as a polars DataFrame; the declared point rows.to('polars')."""

    def add(self, head: _body_5.Any, data: _body_5.Any) -> int:
        """Add a tabular source to a space as ``(head column...)`` facts.

        space may be a context or a space.

        The source may offer rows its own way (``iter_rows()`` for polars,
        ``itertuples()`` for pandas, a mapping of columns, any iterable of rows)
        or speak the Arrow PyCapsule Interface, which is how a DuckDB relation, a
        pyarrow Table, a Parquet reader or an Ibis expression hands over rows
        without a row-at-a-time Python door. A source with both keeps its own:
        the two produce identical atoms, and the row door is the faster of them
        [measured 2026-09-06: 10,000 rows, polars 14.07 ms through iter_rows
        against 14.36 ms through the stream, pandas 20.39 ms against 25.11 ms].

        An Arrow source is written one record batch at a time, so a reader larger
        than memory loads, and the writes are one transaction each; wrap the call
        in ``m.transaction(...)`` to make the whole load one.
        """

    def declare(self, name: str, declaration: _body_5.Atom | str) -> _body_5.Atom:
        """Write one ctx-scoped bridge declaration into &metta, where explain
        and any program can read the schema, and from_context will.

        m may be a context or a space.
        """  # noqa: D205 -- preserve the declared documentation

    def accessors(self) -> tuple[str, ...]:
        """Install the metta accessor for every registered frame library already imported.

        Answers the libraries that now carry it, so a program can ask.

        Registration never imports a frame library. `import metta.tables` costs
        15 ms and `import pandas` costs 531 ms [measured 2026-09-06,
        time.perf_counter around each import in a fresh interpreter], so a module
        that registered by importing would charge every tables user for a library
        the program may never touch. It installs for whichever registered module
        is in `sys.modules`, every door in this module calls it first, and a
        program that imports a frame library afterwards and touches nothing else
        here calls this by name. Idempotent, because a library warns when an
        accessor name is replaced.

        Which libraries these are is the `frame` point's rows, not a list here:
        each row says which module it is and how that library spells an accessor,
        so a third one installs `df.metta` by registering
        (`metta.seam.frame.register(...)`, or the `metta.extensions` entry point).
        """

    def sql_function(self, connection: _body_5.Any, head: _body_5.Any, name: str | None=...) -> str:
        """Register a MeTTa head as a scalar SQL function, and answer its SQL name.

            m.run("(: dbl (-> Number Number))  (= (dbl $x) (* 2 $x))")
            tables.sql_function(connection, m.fn.dbl)
            connection.sql("select dbl(age) from people")

        The head is the callable from a space's `fn` namespace, which already
        carries its own name, its arity and its arrow, so nothing about the
        function is restated here; `name=` is the escape for a SQL identifier the
        head's own name cannot be.

        WHICH engines are known is the `sql` point's rows, and the first row that
        claims the connection declares the function its own way: sqlite3 wants the
        arity and no types, DuckDB wants the types and reads them from the head's
        DECLARED arrow, refusing by name when there is none (an arrow
        `inspect.signature` merely infers is a proposal, not a promise). A third
        engine registers rather than being added here. A row that produces no
        answer is SQL NULL and one that produces several refuses, because a scalar
        function has one result per row; a SQL NULL argument reaches the head as
        `Grounded(None)` and MeTTa decides what it means.
        """


def _rows_to_df(rows: _results.Rows) -> _body_2.Any:  # pylint: disable=unused-argument # signature-only extension declaration
    """These rows as a pandas DataFrame; the declared point rows.to('pandas')."""

def _answers_to_df(rows: _results.Answers) -> _body_2.Any:  # pylint: disable=unused-argument # signature-only extension declaration
    """These rows as a pandas DataFrame; the declared point rows.to('pandas')."""

def _rows_to_pl(rows: _results.Rows) -> _body_3.Any:  # pylint: disable=unused-argument # signature-only extension declaration
    """These rows as a polars DataFrame; the declared point rows.to('polars')."""

def _answers_to_pl(rows: _results.Answers) -> _body_3.Any:  # pylint: disable=unused-argument # signature-only extension declaration
    """These rows as a polars DataFrame; the declared point rows.to('polars')."""
